### ISSUE TITLE
添付ファイルの容量制限

### ISSUE THREAD

**Issue by itowtips** [shirasagi/shirasagi#102]
■https://github.com/itowtips/shirasagi/commit/1140faca825cc23becc3c410c5b0c531664b459c
ファイルサイズによるバリデーションを追加しました。
デフォルトでは2MBとしています。

**Comment by itowtips** [comment]
■https://github.com/itowtips/shirasagi/commit/3941c2076d75ccf05cb353805526c783dd8a7269
environment.ymlに設定を移行しました。

**Comment by itowtips** [comment]
マージしました

**Comment by MasakiInaya** [comment]
デフォルトの制限の値を100MB程度にしていただいてもよろしいでしょうか。

**Comment by itowtips** [comment]
■https://github.com/shirasagi/shirasagi/commit/00cdf59c765add74551a36ea87951b0b0476cdc1
100MBに変更しました。
