### ISSUE TITLE
読み上げ

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#105]
## 要件

* HTML書き出しのタイミングで処理は行わない。
* クライアントからURLを引数に別プロセスで生成したい。
* 音声再生の頻度は少ない、生成時の負荷を分散できるように留意する。

## 思案点

* Open JTalk しばらく更新がないため、他にライブラリがないか調査する。
* リアルタイム生成＋キャッシュ出力のため、生成にかかる時間を考慮する。
* プレイヤーはFlashではなくHTML5の機能で実装できないか。
* 辞書の統合利用においてもっとスマートは方法がないか。

## 実装イメージ

1. SHIRASAGI側) `http://example.jp/aaa.html` の読み上げがリクエストとされる
2. SHIRASAGI側) `http://example2.jp/.voice/http://example.jp/aaa.html` へアクセス
3. 読み上げAPI側) 
    1. 許可されているサイトか検証
    2. リクエストされたページ（`http://example.jp/aaa.html`）のHTMLを取得
    3. 音声が作成済みでページが更新されていなければ音声を出力
    4. それ以外の場合、音声を作成
4. SHIRASAGI側) *作成中音声* を再生しながら定期的に API 側に作成状態を問い合わせ
5. 読み上げAPI側) 音声の作成が完了
6. SHIRASAGI側) 作成された音声を再生（HTMLをreplace）

シラサギでは現在 [delayed_job](https://github.com/collectiveidea/delayed_job) は使用しておらず、
非同期処理は Rake タスクを起動しています。

**Comment by sunny4381** [comment]
[delayed_job](https://github.com/collectiveidea/delayed_job) は使わないということなので、「#86: Shirasagi Job（仮称）」 を検討。

**Comment by sunny4381** [comment]
## 思案点: Open JTalk について
有償の音声合成ソフトウェアやサービスは数多くあるが、フリーで日本語でということなら [Open JTalk](http://open-jtalk.sourceforge.net/) しか選択肢が見つからない。

Open JTalk は、2014年12月25日に更新されており、年に 1 回程度は更新されているようなので、SHIRASAGI では、Open JTalk を組み込もうと思う。

**Comment by sunny4381** [comment]
## 思案点: HTML5 のオーディオプレーヤー

結論としては MP3 形式の音声データなら、ほぼすべてのブラウザで再生できる。

詳しくは、[HTML5の<audio>タグでサポートされる音声フォーマットとオーディオ コントローラ](http://qiita.com/sunny4381/items/36ca1272fad266d81cf3) に書いている。

**Comment by sunny4381** [comment]
## 思案点: 辞書の統合利用

### MeCab と辞書

SHIRASAGI の *ふりがな* も Open JTalk も [MeCab](https://code.google.com/p/mecab/) を使用している。

SHIRASAGI の [install.txt](https://github.com/shirasagi/shirasagi/blob/master/doc/install.txt) には、ipadic をインストールするように指示がある。
Open JTalk は、naist-jdic を改変したものを使用している。

名称       | MeCab 辞書
-----------|-----------
SHIRASAGI  | IPA DIC
Open JTalk | NAIST JDIC カスタム

## 隠れ要件

隠れ要件として、次が考えられる:

* 「ふりがな」で付与される読みと、「読み上げ」で作成される音声は同じ方が良い。

## 仕様

隠れ要件を考慮し、次のような仕様としたい。

1. MeCab + IPADIC で、漢字仮名交じり文を「かな」に変換する。
2. 変換された「かな」を音声に変換する。

**Comment by sunny4381** [comment]
## naist-jdic カスタムについて補足

Open JTalk は音声を作成するに際して、韻律情報が必要である。
幸いなことに MeCab は辞書データを任意に拡張できるので、
Open JTalk は naist-jdic を拡張し、韻律情報を付与している。

## 韻律情報

韻律情報は、例えば次のようになっている。

```
好々爺,1345,1345,5746,名詞,一般,*,*,*,*,好々爺,コウコウヤ,コーコーヤ,3/5,C1
``` 

分子の 3 はアクセントの位置、分母の 5 は[モーラ](http://ja.wikipedia.org/wiki/モーラ)長、
最後に C1, C2, C3, C4, C5, P1, P2, * のいずれかが設定されているが意味は不明。 

アクセントが 2 箇所にある場合は、次の例に示すように「:」（コロン）で区切って指定する。

```
３０２Ａ,1345,1345,49,名詞,一般,*,*,*,*,３０:２Ａ,サンマル:ニエー,サンマ ル:ニエー,3/4:2/3,C1
``` 

次のように、小さいカナは 0 モーラ、長音「ー」、促音「っ」、撥音「ん」は単独で 1 モーラのようだ。

```
１ｓｔｐｌａｃｅ,1352,1352,1692,名詞,固有名詞,組 織,*,*,*,１ｓｔｐｌａｃｅ,ファーストプレイス,ファーストプレイ ス,6/8,*
１６ミリ,1345,1345,2802,名詞,一般,*,*,*,*,１６ミリ,ジュウロクミリ,ジュー ロクミリ,0/6,C1
```

## 同音・異アクセント語

次のように、同じ読みでもアクセントの異なる語がある。

```
橋,1345,1345,5651,名詞,一般,*,*,*,*,橋,ハシ,ハシ,2/2,C3
端,1345,1345,49,名詞,一般,*,*,*,*,端,ハシ,ハシ,0/2,C1
箸,1345,1345,5211,名詞,一般,*,*,*,*,箸,ハシ,ハシ,1/2,C3
```

Open JTalk は、読み分けられる。

なお、よくあるもう一つの事例を示す。

```
雲,1345,1345,4191,名詞,一般,*,*,*,*,雲,クモ,クモ,1/2,C3
蜘蛛,1345,1345,5292,名詞,一般,*,*,*,*,蜘蛛,クモ,クモ,1/2,C3
```

「クモ」に関して言えば、両方ともアクセントの位置は同じだ。
同音・異アクセント語の整備は十分ではないのかもしれない。

**Comment by sunny4381** [comment]
## 読み上げ範囲の指定

* 読み上げ範囲は HTML コメントで次のように指定する。
    * `<!-- read-voice -->本文<!-- end-read-voice -->`
    * `<!-- skip-voice -->除外<!-- end-skip-voice -->`
* `<div id="main">本文</div>` を抜き出す仕様は廃止。
* `read-voice` が存在しない場合は、`<body>本文</body>` を抜き出す。

以下、将来の拡張：

* サイトごとの設定（システム全体設定ではない）で、id 属性や class 属性指定で読み上げ範囲を抜き出す。
    * id="main" を抜き出す場合、`<div id="main">本文</div>`
    * class="wrap" を抜き出す場合、`<div class="wrap">本文</div>`

**Comment by sunny4381** [comment]
## オーディオ・プレーヤーの表示位置

* `<tag id="ss-voice-player" />` が存在する場合、その位置にプレイヤーを表示する。
* 存在しない場合、既定の位置（`<span id="ss-voice"/>` 内）にプレイヤーを表示する。

**Comment by sunny4381** [comment]
## Open JTalk 高速化案

* サンプリング周波数 48kHz で生成している。これを 22.05kHz, 32kHz に変更すると、高速化するか？
* しゃべり方の早さ normal, fast, slow の 3 種のパラメータを試してみて、速度に違いがあるか？

**Comment by sunny4381** [comment]
## システム構成図

実装イメージにある音声作成を別サーバとした場合のシステム構成図:
![図](https://cacoo.com/diagrams/BKZeP4A5pkh3Rbo7-D6DED.png?t=1419230274341)

* SHIRASAGI側も、音声合成側も MongoDB を持つ。
* ユーザ辞書は、音声合成側の MongoDB に保存する。
* 作成した音声ファイルは、音声合成側に保存する。

**Comment by sunny4381** [comment]
## 読み上げの管理画面

* 音声書き出し: 必須ではないが、あってもよい。
  see: https://moqups.com/pinarello.marvel@gmail.com/JpIGnzjX/p:a8d9e2748

* 音声ファイルの作成状況がみれたらよい（最近作成した音声等）。
  see: https://moqups.com/pinarello.marvel@gmail.com/JpIGnzjX/p:a0aabac53


* [時間があれば] 音声作成パラメータの設定画面。
  see: https://moqups.com/pinarello.marvel@gmail.com/JpIGnzjX/p:ac1cd8970
    * ただし、本機能は公開側のオーディオコントローラのオプションとして要望がある。
    * 本画面のように、サイトの管理機能としての要望はない。

**Comment by sunny4381** [comment]
## かな辞書が更新されたら？

音声を合成する前に、合成する必要があるかどうかをチェックしている。
チェック処理を拡張して、かな辞書が更新されていたら音声を再作成するようにした。

更新チェックは、作成済みの音声ファイルのタイムスタンプと比較することで更新を判定する。

**Comment by sunny4381** [comment]
## 記事の更新チェック

要件に「iii.音声が作成済みでページが更新されていなければ音声を出力」というのがある。
ページの更新チェックには、HTTP Response の Last-Modified を用いて、タイムスタンプが新しくなっていたらページが更新されていると判定していた。

しかし、考慮不足があった。

ページが HTML に書き出されず、あるいは静的ページ削除コマンド `rake cms:remove_pages site=www` が実行された場合、SHIRASAGI はリクエストされたページを動的に生成するようになる。
動的生成モードの時、Last-Modified は出力されず、ETag は時間ベースの ETag でアクセスするたびに変化する。

この点を考慮して、HTML の MD5 を比較することで、ページの更新チェックを実施するようにした。

**Comment by sunny4381** [comment]
#117 参照。

CSRF トークンが、アクセスするたびに変化する。このため動的表示時は、アクセスするたびに ETag が変化していた。

HTML の内容がアクセスするたびに変化していたので、上記で HTML の MD5 を比較するように改修したが無駄だった。

そこで、追加の対策。
読み上げの第 1 弾としては、1) 静的 HTML のみ対応、2) 動的表示は未対応、3) ajax parts は未対応という仕様だが、万が一、動的表示時に音声読み上げが実行されると、現状の実装では、いつまでたっても音声合成が終わらず、無限に音声を合成してしまう。

これはまずい。

そこで、音声ファイル作成から 1 分以内はページの更新をチェックしないようにした。

このような仕様のため、サイト管理者がページを更新しても 1 分以上経過しないと音声を再作成しない。
なお、明示的に管理画面から音声ファイルを削除すると、音声を再作成できる。制限を回避する手段があるので、音声ファイル作成から 1 分以内はページの更新をチェックしないようにした。

**Comment by tany** [comment]
Last-Modified:が出力されている時、ではだめですか？

**Comment by sunny4381** [comment]
以前は Last-Modified でチェックしていましたが、MD5 (= ETag) に変更してしまいました。
Last-Modified に戻すことは可能です。

現状の Last-Modified と ETag (= HTML の MD5) は、次のようになっています。

表示モード | Last-Modified | ETag (= HTML の MD5)
-----------|:--------------|:------
静的 HTML  | あり          | なし
動的表示   | なし          | CSRF トークンの影響でアクセスする毎に異なる

読み上げは、次のような仕様でOKですか？

表示モード | Last-Modified | 読み上げの可否
-----------|---------------|-------
静的 HTML  | あり          | 可能
動的表示   | なし          | 不可

この仕様の場合、エンドユーザから見た場合に「画面に表示されているのに読み上げられないのは何で？」となることが懸念されます。この点を懸念して、現在の実装は次のようになっています。

表示モード | 現在の実装
-----------|:-----------
静的 HTML  | 効率的に読み上げることができる。
動的表示   | 1 分間だけ有効な音声ファイルを作成し読み上げることができる。1 分以上経過すると、また音声ファイルを再作成する。

ただし、設定で `config.action_controller.allow_forgery_protection` を false にすると、動的表示時でも効率的に読み上げることができるようになります。
反面、「1 分以上経過しないと音声を再作成しない」という制限があります。

**Comment by tany** [comment]
現時点で動的ページは問い合わせフォームなど限られているので静的ページ限定でも問題ないと思います。
他に検索ページがありますが、QueryString が付いた場合どうなりますか？
QueryStringも条件にすると無限に作成できてしまうし、含めないと内容と異なる音声になります。
静的ページのみにするとこの問題から開放されますが。

**Comment by sunny4381** [comment]
CSRF トークンの部分を削除 → MD5 を取る → 音声作成時の MD5 と比較、という処理にしましょうか？

これだと動的表示モードでも、効率よく音声を作成できます。変な制限もありません。
こっちのほうがいいですね。

**Comment by sunny4381** [comment]
URL が同一かどうかを判定する処理があります。
この処理には Query String は含めて、Fragment は含めないという実装になっています。

**Comment by tany** [comment]
> トークン除去

これでもいいです。
QueryStringは除去するか、リクエストを無視する方が安全だと思います。

**Comment by sunny4381** [comment]
* トークン除去。
* URL の同一性を判定する処理から Query String を除外する。

この 2 点を修正します。

**Comment by sunny4381** [comment]
プルリクをマージしたのでクローズします。
今後、問題が発生したら別チケットで対応します。
