### ISSUE TITLE
シラサギデモサイトのふりがなで、「丁目」に「ヒノトメ」というルビが打たれる。

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#109]
`Kana::Convertor` クラスの  kana_html メソッドの次の置換で、半角数字が `\r` に置換される。

```
        text.gsub!(/[ -~]/m, "\r")
```

`"\r丁目"` という文字列を MeCab で解析すると、「丁目」が「丁▲目」と分割され、読みが「ヒノト▲メ」と出力される。
MeCab で「1丁目」を解析すると、「チョウメ」という正しい読みを出力する。

see: [IPA、NAIST、UniDic、JUMANの辞書実演比較（Mecab）](http://www.mwsoft.jp/programming/munou/mecab_dic_perform.html)

**Comment by tany** [comment]
形態素解析前のテキスト整形を調整しました。
https://github.com/shirasagi/shirasagi/commit/76bd21f5326851cb7786c78f53bd8565c7c45fd4

### これまでの対応
文字間にスペースや記号などの"未知語"が含まれると解析結果が変わってしまう。
　例： `委託 次のとおり` => `イタク ジのとおり`
シングルバイト文字を、未知語として扱われない復帰記号に置換する。

### 問題点
数字＋漢字が適切に解析されないケースがある。
　例： `1丁目` => `1ヒノトメ`
英字＋漢字が適切に解析されないケースがある。
　例： `A型` => `Aカタ`

### 追加の対応
英数字以外のシングルバイトを復帰記号に置換。
　例： `委託 次のとおり` => `イタク ツギのとおり`
　例： `1丁目` => `1チョウメ`
　例： `A型` => `Aガタ`

ASCII印字可能文字
http://ja.wikipedia.org/wiki/ASCII
