### ISSUE TITLE
spec_helper.rbの`rake db:drop`がイケてないのでdatabase_cleanerを使いたい

### ISSUE THREAD

**Issue by kaosf** [shirasagi/shirasagi#113]
具体的には

```rb
before do
  create :nantoka_model
end
```

等とする度に，

```rb
after do
  Nantoka::Model.destroy_all
end
```

等と書いて回らないとダメになるので，それは余りにも辛いので，database_cleanerという勝手にやってくれるgemを使いたい．

使ってみたのですが大量のテストが落ちてしまうのでまだPR出せません．

https://github.com/kaosf/shirasagi/tree/database_cleaner このブランチで実験を重ねていきます．

**Comment by sunny4381** [comment]
## 昨日の進捗で出た課題

`config.order = "order"` の指定があり、テストがシーケンシャルに実行されるが、`config.order = "random"` の方が好ましい。
理由は（色々とあるが）要約すると次の点:

* 暗黙のデータを仮定しており、テストに必要なデータがパッと見てわかりにくい。
* テストの構造が、1) データを設定し、2) テストする、というとても見やすい構造になる。
* テストのバグが減り、テストが堅牢になる。

**Comment by kaosf** [comment]
補足ありがとうございます．

**Comment by sunny4381** [comment]
database_cleaner の最新版は 1.4.0 ですが、mongoid との組み合わせで致命的な問題があり使用できません。使うなら一つ前の 1.3.0 です。

以下、@kaosf を引用:

    DatabaseCleaner
  
    ref.
      https://github.com/DatabaseCleaner/database_cleaner
      http://stackoverflow.com/questions/6583618/clean-out-or-reset-test-database-with-rspec-and-mongoid-on-rails-3
  
    Version 1.4.0 is latest now, but that version contaions an error.
  
    Error message:
      DatabaseCleaner::UnknownStrategySpecified:
           The 'truncation' strategy does not exist for the mongoid ORM!  Available strategies: truncation
     ref.
      https://github.com/DatabaseCleaner/database_cleaner/issues/322
      https://github.com/DatabaseCleaner/database_cleaner/issues/299

**Comment by sunny4381** [comment]
昨日、あるテストでデータベースが不整合状態になって、別のテストが失敗するという現象が発生し、原因の究明にかなりの時間がかかったので、database cleaner を導入して、次のような対策を実施しました。

* example 毎に database cleaner を実行するのではなく、top level description 毎に database cleaner を実行。
* つまり、spec ファイルが異なれば、データベースがまっさらの状態からテストが始まります。
* top level description 毎にイベントを実行する仕組みは標準の RSpec では提供されていないので、RSpec::Core::ExampleGroup.subclass メソッドを差し替えました。

最終目標:

* example 毎に database を初期化する。
* ランダムにテストを実行しても、テストに成功する。

は、遠い目標なので、まずは、第一歩として、spec ファイルごとに database を初期化します。

**Comment by sunny4381** [comment]
### 機能拡張

* RSpec::Core::ExampleGroup.subclass メソッドを差し替えていましたが、もっといい方法が見つかりました。RSpec の標準的な方法を使用して RSpec を拡張するようにしました。
* :dbscope オプションを追加しました。

### dbscope オプション

次のように先頭の describe に `dbscope: :example` と指定すると、テストを実行する毎にデータベースを初期化するようになります。

```
describe Cms::User, dbscope: :example do
  ...
end
```

これは、spec_helper.rb に次のように書いたのと同じ動作となります。

**Comment by sunny4381** [comment]
wiki にまとめました。
https://github.com/shirasagi/shirasagi/wiki/RSpec

チケットをクローズします。
