### ISSUE TITLE
Bodyにクラスがつかない <body id="body--index-html" class="">

### ISSUE THREAD

**Issue by tany** [shirasagi/shirasagi#116]
ディレクトリがある場合（/dir/page.html）にページを書き出すとディレクトリ名が消えてしまいます。

**Comment by itowtips** [comment]
■https://github.com/shirasagi/shirasagi/commit/d2c0189600b1020dd242de5883a57cb11f551dd9
修正しました。
置換の箇所で@cur_pathを使うようにしました。

**Comment by tany** [comment]
IDのすべてに付く -html は冗長なので除去しました。
https://github.com/shirasagi/shirasagi/commit/a60af5f92fa702d7d7fbb4f014ebd7d089c55431
