### ISSUE TITLE
読み上げの ajax parts 対応

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#117]
#105 の拡張として、ajax parts への対応を実施する。

**Comment by sunny4381** [comment]
## ページ更新チェック

現状 5 分間隔で定期的に MongoDB に登録された記事を html 化している。
ajax parts にする意図としては、この 5 分を待たずに新着記事などが反映されることにある。

html 化されていない記事がアクセスされると、動的に html を生成する処理が SHIRASAGI にはあるので、html 化されていなくても適切に記事が閲覧できる。

前提条件を定義する:

* html 化された記事は:
    * Last-Modified が適切に設定されている。
    * ETag を持たない。

* html 化されていない記事 (つまり動的に生成された html) は:
    * Last-Modified を持たない。
    * ETag がアクセスするたびに変わる。

* ajax parts を埋め込まれた元記事では、ajax parts の内容が変化しても:
    * Last-Modified は変化しない。
    * ETag を持たない。

ここで問題点がある:

* 音声合成処理は記事が更新されたかどうかを判定し、更新されている場合は再作成する。
    * html 化されていない記事に対して音声を合成する場合、ETag が常に変化するので無限に音声合成し、いつまでたっても読み上げられない。
    * ajax parts を埋め込まれた記事に対して音声を合成する場合、永久に ajax parts の内容変化を検知することができず、常に更新前のテキストを読み上げる。

**Comment by tany** [comment]
ETagは無効にするケースが多いです。
ヘッダーのみで判断できない場合、コンテンツの内容orハッシュ値などで比較するしかないかと。
Ajax Parts対応は現実的な実装が無理なら代替案を考えます。

**Comment by sunny4381** [comment]
上記の前提条件に少し誤りがあった。

* 現状、記事を公開保存すると `public/sites/` ディレクトリ以下に HTML が書きだされる。
* これを `rm`（例: `rm public/sites/w/w/w/_/index.html`) しても、動的に html を生成する処理が SHIRASAGI にはあるので、記事の閲覧は問題ない。
* このように rm した記事 (= html 化されていない記事 (つまり動的に生成された html)) は、次のような特徴がある:
    * Last-Modified を持たない。
    * ETag がアクセスするたびに変化する (おそらく時間ベースの ETag)。

**Comment by sunny4381** [comment]
（本番環境で）ETag を無効にする件は御意。

**Comment by sunny4381** [comment]
パーツ `attention/recent.part.json` を調査した。
パーツは次のような特性がある。

* Last-Modified を持たない。
* ETag を持つ。

ETag が時間ベースの ETag かどうかが気になる。
追加の調査を実施した。

* 記事を投稿しない場合（つまりパーツの内容が変化しない場合）1 時間たっても ETag は変化しなかった。
* 記事を投稿すると ETag は変化した。

おそらく、内容ベースの ETag が使用されている。

ただし、（本番環境で）ETag を無効にする場合が多いのなら、ETag でコンテンツが更新されたかどうかを判定することができない。
パーツに Last-Modified を出力することができるか？

* `guide.part.html` も調査したが、同様の結果を得た。内容ベースの ETag だ。
* 簡単な印象の ajax parts 対応だが根が深い。

**Comment by sunny4381** [comment]
## HTML 化されていない記事に関する問題の整理

HTML 化されていない記事 (= 書きだされていない記事) にアクセスすると次のような特徴がある:
* Last-Modified が出力されない。
* ETag が出力されるが、アクセスするたびに変化する。時間ベースの ETag である。

問題点を整理する:

1. そもそもアクセスするたびに ETag が変化するので、同一性を判定できず、いつまでたっても音声合成が終わらない。
2. （本番環境で）ETag を無効にする場合が多いのなら、Last-Modified も ETag も存在しないことになる。現状 Last-Modified も ETag も得られない場合、音声合成は 404 Page Not Found エラーを返している。

1 の問題点に対して、音声合成後 n 分以内なら記事の更新チェックを実施せず、合成済みの音声を無条件に返すという案がある。しかし、この案は、サイト管理者から見ると、記事を更新したのに音声が再作成されないという問題が発生する。

2 の問題点に対して、HTML 化されていない記事 (= 書きだされていない記事) に対して Last-Modified を付与できるか？
1 つの HTML は複数のレコードからなるので、単純に updated フィールドを用いればいいという話じゃないのは理解できるんだけど、なんとか Last-Modified を付与できないか？

※2 の問題で Last-Modified が付与できれば、1 の問題は半自動的に解決する。

**Comment by sunny4381** [comment]
## ajax parts に関する問題の整理

* 元記事 (ajax parts が埋め込まれている側) の特徴:
    * HTML 化されている (= 書きだされている) 場合:
        * Last-Modified を持つが ajax parts の内容が変化しても Last-Modifed は変化しない。
        * ETag を持たない。
    * HTML 化されていない (= 書きだされていない) 場合:
        * Last-Modified を持たない。
        * ETag はアクセスするたびに変化する。時間ベースの ETag。

* ajax parts の特徴:
    * Last-Modified を持たない。
    * ETag を持つ。ETag は内容ベースの ETag で、内容が変化しない限り変化しない。

考慮点:

* ETagは無効にするケースが多い。

問題点:

* ETag は無効にされるケースが多いので、ajax parts の内容の変化を検知できない。
* ETag が有効にされた場合:
    * Model クラスを拡張し、parts の ETag を持てるようにする。
    * 記事が更新されたかどうかを判定する際、すべてのパーツの ETag を照合する。

* ETagは無効にするケースが多いので、ajax parts に Last-Modifed を出力するように改変する。
  この場合:
    * Model クラスを拡張し、parts の Last-Modified を持てるようにする。
    * 記事が更新されたかどうかを判定する際、すべてのパーツの Last-Modified を照合する。

すべてのパーツの ETag や Last-Modified の照合には時間がかかるかもしれない。
1 パーツあたり 1 秒で照合できるとしても、30 パーツあれば 30 秒かかる。

現状は Controller クラスで記事が更新されているかどうかを判定しているので、
あまりにも時間がかかりすぎるとタイムアウトしてしまう。

**Comment by sunny4381** [comment]
読み上げ側の都合のみを考えれば、次のようになるのが理想。

1. SHIRASAGI側) `http://example.jp/aaa/bbb.html` の読み上げがリクエスト。
2. 読み上げ側) `http://example.jp/aaa/bbb.html?static=true` にアクセスする。
3. SHIRASAGI 側) `static=true` が設定されていると、次のようなレスポンスを応答する。
    1. すべての ajax parts を展開
    2. 必ず適切な Last-Modified を設定

**Comment by tany** [comment]
ググっただけですがこういうので付与してみますか？
> Rack::ETag は、response.body の MD5 の値を ETag を付与します。

nginx/apache の設定と競合するときどうなるかはわかりません。
第一弾リリースとしては静的ファイル（ヘッダー検証が可能な時）のみ音声生成でも問題ないです。

**Comment by sunny4381** [comment]
「第一弾リリースとしては静的ファイル（ヘッダー検証が可能な時）のみ音声生成でも問題ない」について了解です。

**Comment by sunny4381** [comment]
`public_filter.rb` を読んでみました。mobile モードの場合、ajax parts であっても、HTML に展開しているようです。
代案として、音声合成は「モバイルページを読み上げる」という仕様でどうでしょう？

**Comment by tany** [comment]
今後、「長文時にページを分割する」仕様が入ると複数リクエストは発生してしまうかもしれません

**Comment by sunny4381** [comment]
`Rack::ETag` は標準で有効でした。

なぜ、アクセスするたびに ETag が変化するか追加調査してみました。
アクセスするたびに、CSRF 対策の次の部分が変化するからでした。

```html
<meta content="sSIA0pU5YhHudriUiC1W413zdnVVzW/zWvRMmjQhYLU=" name="csrf-token" />
```

`config/environments/production.rb` で `allow_forgery_protection` を `false` に設定すると、上記は出力されなくなります。

```ruby
  config.action_controller.allow_forgery_protection = false
```

このように設定すると、毎回同じ ETag が出力されるようになりました。

現在、`allow_forgery_protection` を `false` にすると、どんな悪影響があるのか不明です。
`allow_forgery_protection` は、`false` にしていいもんなんでしょうか？

**Comment by sunny4381** [comment]
CSRF は公開側は無効にしても良さそうです。

理由は、Rails の CSRF 対策を有効なものとするためには、csrf-token はリクエストのたびに変更する必要があります。
静的に書き出すページでは、攻撃者は予め token がわかるため、Rails の CSRF 対策を回避できる可能性が高まります。

次のようなコードで、CSRF 対策を実施するメソッドを制限できるようです。

```
protect_from_forgery :only => [:update, :delete, :create]
```

これによく似たコードを、どっか (public_filter.rb ?) に実装すれば、公開側の HTML に csrf-token を出力させなくできそうです。

**Comment by tany** [comment]
公開画面の静的ファイルはCSRFトークを出力していないと思います。
https://github.com/shirasagi/shirasagi/blob/master/app/views/layouts/cms/page.html.erb

**Comment by tany** [comment]
CSRF対策はあればよいくらいに考えています。

**Comment by sunny4381** [comment]
静的ファイルには CSRF トークンが存在しないことを確認しました。

静的ファイルには CSRF トークンが存在しないのに、動的生成時に CSRF トークンが出力されるのは変なので、別のチケットで管理したいと思います。

第 1 弾の音声読上げは、静的ファイルのみ対象で、動的生成は非対応、ajax parts は非対応としたいと思います。
そして、動的生成時に CSRF トークンが出力されなくなったら、音声読み上げも自動で対応できるように考慮しておきます。

現時点では、ajax parts 対応については voice モードのようなモードを新規に追加し、ajax parts を HTML に展開するのが良さそうに思います。

**Comment by sunny4381** [comment]
補足: `ActionController::RequestForgeryProtection` を読んでみました。

"csrf-token" は、秘密鍵で暗号化されることもなく、form の CSRF トークンと、session の CSRF トークンを単純な文字列比較で検証しています。
このため、事前に CSRF トークンが入手できると、Rails の CSRF 対策を容易に回避できそうです。

**Comment by tany** [comment]
静的ファイルにトークンがないのは、動的処理への遷移が（いまのところ）無いことと、
ファイル書き出し時に更新すべきかの判断基準にしているからです。

**Comment by sunny4381** [comment]
第 1 弾での対応は不要となったのでクローズします。
今後、問題が発生したら別チケットで対応します。
