### ISSUE TITLE
広告バナーページ編集エラー

### ISSUE THREAD

**Issue by itowtips** [shirasagi/shirasagi#121]
■https://github.com/itowtips/shirasagi/commit/f1d3bcbdc482ee3acf73cd5ced10c54702afec81
なんらかの原因で
```@item.file_id``` は存在するが
```@item.file``` が```nil```になり
編集ができなくなってしまう不具合があるみたいです。
上記の修正でとりあえず動作するようには直りました。

**Comment by MasakiInaya** [comment]
公開、非公開を切り替えると編集画面が500エラーになり、画像が削除されてしまうようです。

**Comment by tany** [comment]
修正しました。
https://github.com/shirasagi/shirasagi/commit/6281f27f85c32382214dd61b95431a684001468b
コールバックメソッド名が被っていたのでリネームしました。
