### ISSUE TITLE
ファイルアップロード画面でページネーションを行うとデザインが崩れる

### ISSUE THREAD

**Issue by itowtips** [shirasagi/shirasagi#122]
添付ファイルのモーダルで「次へ」ボタンを何回か押すと、
モーダルで表示されずにデザインが崩れてしまう。

**Comment by itowtips** [comment]
class="cboxElement"　のイベントで一度遷移すると
遷移先ではこのclassが消えてしまい、modal出力に失敗する。

classを振れば遷移できるようですが
https://github.com/itowtips/shirasagi/commit/566a2516e0f8df7df9d7437e4f4ab490beff9de0

この方法だと遷移先のmodalの大きさが変わってしまいます。
```{ fixed: true, width: "90%", height: "90%" }```
のオプションがない為

**Comment by itowtips** [comment]
遷移のイベントはss.coffee.erbの
``` SS.render(box=nil) ```
において ``` box ``` が ``` nil ``` でない場合に
``` if box ... ```
のブロックで設定されているようです。

https://github.com/itowtips/shirasagi/commit/b87915878d9cf4966d40166870094c1faa13fae9
ここのelem.colorboxにコールバックを設定しページネーションに対応するようしてみました。

**Comment by tany** [comment]
pagination に限った実装ではないなら関数名変えた方がいいです。（キャメルケースで）

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/commit/049b1872730b1f527f8e51d9c94148131894f94b
関数名を``` anchorCallback ```としマージしました。
