### ISSUE TITLE
メルマガエントリ確認メールの文面

### ISSUE THREAD

**Issue by kaosf** [shirasagi/shirasagi#128]
現状: https://github.com/shirasagi/shirasagi/blob/115cc09b30abe64566d5c7b2e467f35074a89f39/app/views/ezine/mailer/verification_mail.ja.text.erb

確認メールの文面に必要になりそうなものをとりあえず出しているだけになっています．

どういう文面にすればいいのかご教授下さい．

**Comment by kaosf** [comment]
理想はこの文面も管理画面から設定出来ることですかね？

**Comment by tany** [comment]
```
[node.name] entry_type確認

メールドレスのentry_typeを受け付けました。
以下のアドレスをクリックして、entry_typeを完了してください。
url

メールアドレス: email
配信形式: email_type

このメールに心当たりのない方はお手数ですが本メールを破棄してください。
```
設定できる機能か、署名設定があるといいですね。

**Comment by kaosf** [comment]
文面変更したので shirasagi/shirasagi の master を更新しました．
