### ISSUE TITLE
携帯プレビュー表示のリンクがおかしい

### ISSUE THREAD

**Issue by itowtips** [shirasagi/shirasagi#129]
http://demo.ss-proj.org/.demo/preview/mobile/
一覧で出ている箇所のリンクがおかしくなってしまうようです。

現状　：http://demo.ss-proj.org/mobile/.demo/preview/guide/kekkon/
正しい：http://demo.ss-proj.org/.demo/preview/mobile/guide/kekkon/

**Comment by itowtips** [comment]
問題は
```Mobile::PublicFilter``` の ```render_mobile```　が
```preview_controller``` の ```render_preview``` より後に呼ばれてしまう為。
どちらも```after_action```。

現状　：　```render_preview```　→　```render_mobile```　
正しい：　```render_mobile``` →　```render_preview```

次のように```preview_controller```にコールバックを記述すれば回避可能のようです。
https://github.com/itowtips/shirasagi/commit/21438f105b9fd507e78f9dc561ce3c89f2f5a031

``` Cms::PreviewFilter ``` を作成し、こちらにロジックを移して
```
include Cms::PublicFilter
include Cms::PreviewFilter
```
としてみましたが、呼ばれる順番が変わらず。
```include do```　の中にコールバックを書いた時の優先度が今一つ把握できていない状況です。

**Comment by tany** [comment]
render_mobileのロジック直したほうがよくないですか？

**Comment by itowtips** [comment]
ロジック側を直したものを作成しました。
次のようになりました。
https://github.com/itowtips/shirasagi/commit/c4ac0ac57f826d269ce238e49ded6ec80e184648

**Comment by itowtips** [comment]
filterからcallbackをそれぞれのcontrollerに移すパターンは
次のようになりました。
https://github.com/itowtips/shirasagi/commit/2037c3c48d6a0baa5733d57eafaeb6553a41f8ce

**Comment by itowtips** [comment]
マージしました。
