### ISSUE TITLE
メルマガ不具合

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#131]
■公開画面
index.htmlが配信登録でないですが問題ないでしょうか。

・一覧画面
　日付は「○年○月○日」にしてください。
　「Ezine.more」は消してください。
　配信していない記事も出ますが問題ないでしょうか。

・記事詳細画面
　本文が表示されません。

・配信登録画面
```<div class="ezine-html"> 配信登録 </div>```
を
```<h2 class="ezine-html"> 配信登録 </h2>```
に変更してください。

■管理画面
一覧部分で記事タイトルやメールアドレス等がリンクになっていません。

・設定
　上部、ループ、下部HTMLが反映されません。
　ページレイアウトが反映されません。

**Comment by mizoki** [comment]
配信登録のパスについてですが、
`/%メルマガのパス%/entry/new` で配信登録に遷移しますが、
`/%メルマガのパス%/entry/` で配信登録に遷移した方がよろしいでしょうか？

**Comment by kaosf** [comment]
NOTE

#131 で解消していない問題列挙

* 公開画面系
  * index.htmlが配信登録でないが問題がないか
  * 配信していない記事も出るが問題がないか
  * 記事詳細画面 本文が表示されない
* 管理画面系
  * 設定
    * 上部，ループ，下部HTMLが反映されない
    * ページレイアウトが反映されない

**Comment by kaosf** [comment]
@MasakiInaya 確認したいのですが，

> 上部、ループ、下部HTMLが反映されません。

というのはメールマガジンモジュールとしてのフォルダを作成して，そのフォルダの「設定」のところで設定するものですよね．それが例えば `http://host/ezinetest/index.html` において表示されなかったということでしょうか？

今の master ですと反映されて表示されていると私は認識しているのですが…

**Comment by kaosf** [comment]
@MasakiInaya すみません，恐らくこのコミット https://github.com/shirasagi/shirasagi/commit/a82b1adedeb2ab18728ab1cde389b744e26787a3 で `reder_page_list` を使うように書き換えたから今出るようになってるのですね．ということで現状では

> 上部、ループ、下部HTMLが反映されません。

は修正されています．ご確認お願いします．

**Comment by tany** [comment]
希望構成としては...
/magazine/ => 登録・変更・解除（･バックナンバー）へのリンク
/magazine/backnumber/ => 配信記事リスト（別途フォルダーを作成）
```
get "page/(index.:format)" => "public#index", cell: "nodes/page"
get "page/new.:format" => "public#new", cell: "nodes/form"
get "page/update.:format" => "public#update", cell: "nodes/form"
get "page/remove.:format" => "public#remove", cell: "nodes/form"
post "page/confirm.:format" => "public#confirm", cell: "nodes/form"
get "page/verify.:format)" => "public#verify", cell: "nodes/form"
get "backnumber/(index.:format)" => "public#index", cell: "nodes/backnumber"
```

**Comment by tany** [comment]
少し曖昧仕様を含みますが、
- 初めに、ベースとなるメールマガジンフォルダーを作成して管理する。
- 会員登録/解除へのリンクは自動で表示される。
- 動的処理するパスにはフォルダーを含みたくない。（静的で上書きするケース）
- バックナンバーは公開したい場合のみバックナンバーフォルダーを作成する。
- バックナンバーは親フォルダの記事を参照する。
```
# config/locales/ezine/ja.yml
cms.nodes.ezine/page: メールマガジン
cms.nodes.ezine/backnumber: バックナンバー
```

**Comment by kaosf** [comment]
`Ezine::Agents::Nodes::BacknumberController` を追加して，既存の `Ezine::Agents::Nodes::PageController` の `index` メソッドの処理を移植してやる．

移植されて空いた方の `index` メソッドに登録・変更・解除(・バックナンバー)へのリンクを貼ったページを描画するアクションを追加する．

という感じですか？

あとバックナンバーを公開するしないの設定はメルマガモジュールとしてのフォルダの設定で出来るようにする，という感じですか？

**Comment by tany** [comment]
移植はその通りです。
記事は`非公開`を初期値にしておき、`公開`にした記事だけがバックナンバーの一覧に表示される。
バックナンバーフォルダーが作成されていない場合はバックナンバー（一覧）は存在しない。
```
get "backnumber.:format" => "public#index", cell: "nodes/backnumber"
```

**Comment by kaosf** [comment]
#143 で

> 記事詳細画面 本文が表示されない

に対応しました．master 更新しています．

**Comment by kaosf** [comment]
#153, #154 で

> ■管理画面
> ・設定
> 　ページレイアウトが反映されません。

に対応しました．master 更新しています．

**Comment by kaosf** [comment]
NOTE

#131 で解消していない問題列挙

* 公開画面系
  * index.htmlが配信登録でないが問題がないか
  * 配信していない記事も出るが問題がないか

**Comment by kaosf** [comment]
> 配信していない記事も出ますが問題ないでしょうか。

デフォルトで `Ezine::Page` を非公開とし(#131 で対応)，バックナンバーフォルダを作り更に公開に変更しなければ記事は表示されない，という仕様に変更したので解消したとみなします．

> index.htmlが配信登録でないですが問題ないでしょうか。

配信登録画面などへのリンクがフォルダの index で表示されるようにしたので解消したとみなします．
