### ISSUE TITLE
ドキュメントの不備

### ISSUE THREAD

**Issue by rikoroku** [shirasagi/shirasagi#1385]
## issue内容
* Centosインストールマニュアルの「新規サイトの作成」項目に不備がある。
  * サイトとユーザーを追加しただけでは管理画面上でサイトを編集できない。
  * グループを作成後、サイトにグループを設定し、グループにユーザーを追加しないといけない。

## 改善案
* Centosのインストールマニュアルの「新規サイトの作成」項目に、グループ追加の流れを記載する。

## 対象ページ
http://shirasagi.github.io/installation/manual.html

**Comment by tany** [comment]
サンプルデータを利用する場合、利用しない場合の両方を記載しました。
http://shirasagi.github.io/installation/manual.html
