### ISSUE TITLE
アクセシビリティチェック機能のリンクテキストのチェック

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#1388]
a タグ内に img しかない場合に警告が出るが、alt属性に文字がある場合は警告対象外としたい。

**Comment by y-teraz** [comment]
本件対応の優先度上げていただきたいです。

画像をサムネイル配置した時、元画像へのリンクになるわけですが、保存すると必ずリンクテキストのアクセシビリティ警告が出ます。
しかし、適切にaltが設定済みの場合には警告する必要がありません。

同HTMLをmiCheckerで確認した場合は、altにテキストがあるため、警告とはなりません。

警告の対象外となるように、変更願います。

**Comment by itowtips** [comment]
alt属性に文字がある場合は警告対象外に変更しました。 #3103
