### ISSUE TITLE
オープンデータで日本語URLのクローリング

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#1460]
日本語部分がパーセントエスケープされた URL をクローリングした場合、
次のような問題点がある。

1. 管理画面のクローリングファイルがパーセントエスケープされた状態で設定され
  1-1. 長過ぎる
  1-2. 日本語に変更しようとしてもできない
2. 公開側からダウンロードできない

URLの例: http://awa.od-db.jp/dataset/ef4588f8-7761-4e2a-a7a0-5aeeb0fb8fe1/resource/fa4b0bca-b375-457b-8f55-de2685d56aec/download/01.%E4%BA%BA%E5%8F%A3%E3%83%BB%E4%B8%96%E5%B8%AF%E3%80%80%E7%94%BA%E5%88%A5%E5%AD%90%E3%81%A9%E3%82%82%E4%BA%BA%E5%8F%A30226_2.xlsx

**Comment by ShinjiTanimoto** [comment]
[Modify]url-resource #1486
