### ISSUE TITLE
サイト固有のNginx設定を設定ファイルとして書き出したい

### ISSUE THREAD

**Issue by itowtips** [shirasagi/shirasagi#1466]
管理画面からサイト固有の項目をnginxの設定として書き出したい

■ホスト名
nginx の root 句 
ex.)　www → "root /var/www/tkssc/public/sites/w/w/w/_/;"

■ドメイン
nginx の server_name 句
ex.)　example.jp → "server_name example.jp;"

**Comment by sunny4381** [comment]
随分と前から Rake タスク `ss:write_nginx_config` で可能。
また、サイトの作成・更新時などで自動で nginx の設定ファイルが反映されるようです。
