### ISSUE TITLE
 公開日に関する要望

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#1471]
- 表示位置/フォーマット
  - 自動で本文の頭に追加されますが、レイアウト上で設定できる方が望ましいと考えます。あるいは、サイト設定で、上か下か選べるように出来ないでしょうか。
  - フォーマットもレイアウトでループHTML同様にコード指定できればサイトに適切な指定が可能となると考えます。
- 固定ページ
  - 記事ではなく固定ページのとき、公開日の表示ができるようにならないでしょうか。
  - 必要に応じて選択できるか、レイアウトで表示設定できるならレイアウトの切替で対処できると考えます。

**Comment by ShinjiTanimoto** [comment]
92c57d31edfd2a2f91b4f29944dab2450e9a71b1
