### ISSUE TITLE
固定ページに関する要望

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#1472]
- サイト内の固定ページ一覧
  - フォルダ以下に固定ページを作った場合、確認しづらいです。
  - 作成者でも間が開くと分からなくなると考えますし、管理者を引き継いだあと確認がしづらいのはCMSとして問題が在ると考えます。

**Comment by ShinjiTanimoto** [comment]
73ff88c99a4d7634ff5f6727fefcf906a58f12b3
48844bb0441685b753b323f039c7fb4c536bf485
eac68160c5c1db5661dcb22f3c04edbb6ff1683a
439da63b0842c0c778e52ef2cdd6542834ccf68d
54da0e297cf7642c5947254a32b542342f256b5f
4f33f3ce5c486fc8d4709c19713b7ba23f00bc13
