### ISSUE TITLE
記事の編集に関する要望

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#1473]
- 連絡先欄
  - 電話番号、ファックス、メールアドレス以外に、リンクの設定をできるようにして欲しいです。メールフォームへのリンクを記載したい場合などがあるため、リンクを設定できればと思います。
- ファイル・アップロードのUI
  - ファイルアップロードは複数選択で行えますが、そのあと、編集画面に登録→本文エディタに登録という2つの手順で、複数選択して登録できないのが不便に感じました。
  - UIとしてファイル欄と、本文エディタが離れているため、大量に添付するときに、迷いやすいと思います。モーダルなどでスクロール位置をずらさずに入力できると使いやすいかと思います。
- 画像の加工
  - 画像のリサイズがアップロード時のみですが、アップロード後の[編集]ボタンからファイル名変更など出来ますが、ここでリサイズもできないでしょうか。
  - リサイズのサイズを手動で数値入力もできようにならないでしょうか。
  - CMSの要件として、画像のリサイズとトリミングを指定されることがあります。
- 下書き保存
  - 「非公開状態で保存しようとしています」という警告表示がありますが、毎回表示されるため、表示の有無を選べるようにできないでしょうか。よく見られるような、「今後、この警告を表示しない」のチェック選択などを追加するなど、ご検討願います。
  - ショートカット(Ctrl+S等)で下書保存できると便利なのでご検討願います。
  - 公開権限有りのユーザが敢えて、承認を利用する場合や、予備作業として下書きとしておきたい場合に、都度警告されるのがうっとおしく感じます。移行作業時や、基本的には承認を利用するが場合によっては逐次公開にも対応する必要があるユーザには公開権限を与えて運用したいと考えますので、ご検討願います。

**Comment by ShinjiTanimoto** [comment]
eb72d03cd100bece3ea49a7c68b21172b69d682f
8bf507eda1e73ef06808b4bda96218429e8a48c3
8f79d83c12038fc1de6ecac59b74e1fcff99c631
d88867963d657208ea3bd914fc0f2e4254a02896
b08fd137b3a99197643a8d1a27c5ca31960b9802
96c8f588ad1241c59ba7e02dff10d3084b966e62
