### ISSUE TITLE
本文レイアウトに関する要望

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#1475]
- 制限
  - フォルダかレイアウトに対して使用可能な本文レイアウトを制限できるのであれば、拡張版である本文レイアウトの運用がし易いのではないかと考えます。
  - 現状では、使用目的ではない記事ページても追加設定した本文レイアウトが選択可能な為、利用者の選択ミスを防げません。
- 記事のCSVの本文レイアウト対応
  - 記事をcsvダウンロードすると、csvに”本文レイアウト”の選択値がなく、本文も空となりインポート/エクスポートの対象になっていないようです。
  - 選択可能であるならCSVにも対応するか、記事の場合本文レイアウトの選択をシステム的に不可としてしまうのが適当であるように思います。

**Comment by ShinjiTanimoto** [comment]
Add body_layouts permission (#1514) d1771d078f2a786023bad56d5dd3ea704f8d67aa
