### ISSUE TITLE
カレンダーに関する要望

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#1476]
- 月別/日別の一覧ページのタイトル(同一タイトルの解消)
  - URLとして個別のアドレスとなっているのであれば、titleタグにフォルダ名+年月or年月日を自動追加するなど個別のタイトル化するようにお願いします。
  - 同一タイトルの別ページが大量にあることになるので、重複コンテンツのように見えます。
  - 現在のイベントカレンダーのタイトルではウェブアクセシビリティ試験を実施すると、達成基準2.4.2ページタイトルの達成基準 (適合レベルA) のG88「ウェブ ページに対して、コンテンツの内容が分かるページタイトルを提供する。」という項目で不適合になり、ウェブアクセシビリティを確保することができません。
- 「イベント/カレンダー」パーツの月切替後のタグ
  - 前/次の月と、今月の.calendar-nav内のリンクで切り替えると、div.event-calendarの中に、更にdiv.event-calendarができます。
  - スタイル調整を間違いやすい為、.event-calendar自体を置き換えるなどに変更頂きたいです。
- イベント情報の収集/表示
  - 「イベント日(未終了)」の条件はありますが、現在日時から「今日のイベント」「明日の」「今週の」などの現在日を基準としたの相対日数条件もあると、利用用途が広がります。
  - 自動で動的生成がつくれますが、より深いカスタマイズとしてAPIとして直接javascriptからイベントデータの問い合せ抽出ができるように提供していただけれると表現の幅が出て助かります。

**Comment by ShinjiTanimoto** [comment]
bba73a1aaac495cd70ee5717f1a632b448be4432
7e0c867a71bef844d90696c709005c88d0d586a4
