### ISSUE TITLE
関連記事

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#151]
記事作成画面の関連記事のモーダルウィンドウが記事件数が多い場合に、IE、FFで開けなくなります。

**Comment by itowtips** [comment]
■https://github.com/itowtips/shirasagi/commit/41fc032e14a520088a27d2f9267d468f2244abec
関連記事モーダル中にページネーションを作成しました。

**Comment by itowtips** [comment]
■https://github.com/shirasagi/shirasagi/commit/29c2ad3ee679fe4a551087f27168944bb29fab07
マージしました。

**Comment by itowtips** [comment]
■https://github.com/shirasagi/shirasagi/commit/96a4016f7256a8afeb22f5218b89eca518ec43d7
colorboxの画像スライダー?を非表示としました。

![colorbox_image_slide](https://cloud.githubusercontent.com/assets/6094043/6034164/d18f63e6-ac62-11e4-8c18-1791ac17090a.png)
