### ISSUE TITLE
イベントカレンダーのアクセシビリティ対応

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#1536]
# 一覧表示(月別一覧)
行事のない日のdlからddが抜けているため、W3Cのvalidator(https://
validator.w3.org/)にて、エラーとなる。
行事がないため、ddでイベントの無い旨を通知する文言を用意するのが適切。
このとき読み上げ用文言として、class属性とstyle設計により見た目上非表示とするなどの調整が可能とする。

# イベントカレンダー(表)
列ヘッダ「日」「月」「火」…の部分がスクリーンリーダーで正しく読み上げられない。
abbrを使用して「日曜日」「月曜日」「火曜日」…と読み上げるようにしたい。

**Comment by ShinjiTanimoto** [comment]
0fc2656cf7e907305c6b5b79c56813bf304edf70
