### ISSUE TITLE
施設のアクセシビリティ対応

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#1540]
# 施設情報の一覧表
## キャプション
施設の地域の公開画面場合、施設情報の一覧で表のキャプションが見出しと同じなので読み上げ上、冗長である。
表であることも分かりづらいので表のキャプションを自分で設定するようにしたい。

## 見出しセル(scope属性)
列見出し(theadのth)のscope属性が不足している。

# 施設の分類(種類/用途/地域)
種類/用途/地域のそれぞれに公開O、非公開を選択できるようにしてたい。
ひとまず種類のみで運用を開始し、後日用途を設定する、あるいは、見直しのために一次非公開にするなどができると利便性が在る。

**Comment by itowtips** [comment]
## 施設の分類(種類/用途/地域)
施設情報の検索フォルダーと一覧フォルダーに、種類、用途、地域を設定できる。
種類、用途、地域フォルダーを非公開にした際に、公開側へ表示しないようにしたい。

**Comment by ShinjiTanimoto** [comment]
8a7353e45b49bea9ba9861810f7519826b1141cc
