### ISSUE TITLE
インストール時に公開鍵の取得に失敗する

### ISSUE THREAD

**Issue by ftakao2007** [shirasagi/shirasagi#1556]
公開鍵を取得する際に以下のようなエラーが発生していました。

```
$ gpg2 --keyserver hkp://keys.gnupg.net:80 --recv-keys D39DC0E3
================================================
gpg: 鍵D39DC0E3をhkpからサーバkeys.gnupg.netに要求
gpgkeys: key D39DC0E3 can't be retrieved
gpg: 有効なOpenPGPデータが見つかりません。
gpg:         処理数の合計: 0
================================================
```

以下のようにすると鍵の取得が成功し、サービスが起動するところまでは確認できましたので共有させていただきます。
https://github.com/ftakao2007/shirasagi/commit/068749fe9c9ffe0bb7c4abfa0ac61f19c6cfb647

**Comment by sunny4381** [comment]
@ftakao2007 修正有難うございます。
動作の確認が取れましたので、プルリクエストを送っていただければ取り込みますので、お手数ですがプルリクエストの送付をお願いします。

**Comment by ftakao2007** [comment]
@sunny4381 
https://github.com/shirasagi/shirasagi/pull/1558
プルリクエストを作成しました。
お手数ですが取り込みをよろしくお願いいたします。

**Comment by ftakao2007** [comment]
マージいただけましたのでCLOSEします。
ご対応ありがとうございました。
