### ISSUE TITLE
カテゴリーリストパーツ

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#158]
カテゴリーリストパーツを記事リストフォルダーのレイアウトに配置し、ページネーションで2ページ目以降に遷移するとリストが表示されなくなります

**Comment by tany** [comment]
パーツ上でのページネーションを無効にしました。
https://github.com/shirasagi/shirasagi/commit/76016165127c07ccc9cf6c72ca47fd89c89d0148
