### ISSUE TITLE
公開日時

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#168]
記事の公開日時に未来の日時が設定されている場合に、記事ページ自体は公開されるのですが、カテゴリーページ一覧などに表示されなくなります。

**Comment by tany** [comment]
未来の日時で公開するのはどんなケースですか？

**Comment by MasakiInaya** [comment]
一般公開前のサイトでページ公開日をサイト公開日に合わせるために未来日時にしております。

**Comment by tany** [comment]
その場合はプレビュー機能で公開日の状態を見れば表示されます。未来の記事を常に表示させるとプレビューが機能しなくなります。

**Comment by MasakiInaya** [comment]
ページ自体は公開されているようですがこれは問題ないでしょうか。

**Comment by tany** [comment]
公開できないようにすることはできますが、そこまで制限する必要はないと思います。

**Comment by MasakiInaya** [comment]
承知しました。
今確認したところ、一覧にも表示されるようになっていましたが何か作業されましたでしょうか。

**Comment by tany** [comment]
何も触ってませんし、全部憶測です。

**Comment by MasakiInaya** [comment]
分かりました。
公開画面の一覧には表示されていました。
プレビューの場合は未来日時で表示すれば表示されました。
