### ISSUE TITLE
メールアドレス以外でのログイン

### ISSUE THREAD

**Issue by tany** [shirasagi/shirasagi#174]
メールアドレス&パスワードでログインしている現仕様を、
別定義のアカウント名&パスワードでログインしたい。

**Comment by sunny4381** [comment]
#201 と同時対応。

**Comment by sunny4381** [comment]
## 前提

* #201 にて、複合キー (uid, password) でユニークに出来ないことがわかった。
* マルチテナントサポートを考えた場合、組織間で uid が重複する可能性があるので、uid 単独でユニークとする仕様は避けたい。
* @tany より「グループごとの専用ログイン画面を用意する」という案が出た。

上記課題の深堀り検討結果である。

## AWS に見るマルチテナント・ログイン

先行事例として AWS を紹介する。
AWS では、ルートアカウントでのログインと、通常アカウントでのログイン画面が異なる：

| root account loing |
|-------------------------|
| ![aws-root-account-login-min](https://cloud.githubusercontent.com/assets/3593466/6321511/a5f0d7f8-bb42-11e4-82a1-38dea8716168.png) |

| 通常account login |
|-------------------------|
| ![aws-indivisual-account-login-min](https://cloud.githubusercontent.com/assets/3593466/6321512/aa6f7d2a-bb42-11e4-9836-f4f09626e987.png) |

* ルートアカウント
    * email のみ。
    * 全世界でユニーク。
* 通常アカウント
    * アカウント内でユニーク。
    * 英数字であれば、何でも良い。
    * ルートアカウントと同じ email でも良い。
* URL 設計
    * `https://${account_id}.signin.aws.amazon.com/console` にアクセスすると、通常アカウントログイン画面が表示される。
    * `https://console.aws.amazon.com/` にアクセスすると:
        * Cookie にアカウントIDがあれば、通常アカウントログイン画面へ。
        * Cookie に何も無ければ、ルートアカウントログイン画面へ。

「グループごとの専用ログイン画面を用意する」という案はこれに近いか？

**Comment by sunny4381** [comment]
## user_ldap_accounts/ss_user_accounts について

### 前提

* `user_ldap_accounts` というテーブルを新規作成し、`user_ldap_accounts` で (uid, group) の複合キーのユニークネスをチェックするという案を頂戴した。
* ldap に限定するのも変なので、`ss_user_accounts` というテーブルに名称変更し、sns ユーザの uid のユニークネスもチェックできるように考慮する。
* `ss_user_accounts` は、`ss_users` の子テーブルである。

![ss_user_accounts-min](https://cloud.githubusercontent.com/assets/3593466/6322141/e7c10b62-bb51-11e4-9c84-cb8692339e98.png)

### MongoDB の場合

MongoDB の場合トランザクションがないので、`ss_users.create(...)` -> `ss_user_accounts.create(...)` という Rails の普通の親子テーブルの保存処理の中で、`ss_user_accounts` に制約違反があっても `ss_users` に該当文書が保存される気がする。
本来、作成すべきではない文書が保存されてしまう。

なんかいい方法がないだろうか？

`ss_users` に embed で情報を保存し、index を張って、scope でユニークネスをチェックするのが良さそうだけど、`ss_users` は複数のグループを持てる。

**Comment by sunny4381** [comment]
## [予備実験] embed で配列を保持し、その配列に uniq index を作成すると、制約違反エラーとなるか？

結論を述べると Yes だった。

以下、予備実験の詳細。

* 次のコマンドで uniq index を作成する。

  ```
  > db.ss_users.ensureIndex( { "uid": 1, "group_ids": 1 }, { unique: true } );
  ```

* どんなユーザが存在するか、確認してみる。

  ```
  > db.ss_users.find({ "uid" : "user1" }, { "uid" : 1, "group_ids" : 1 })
  { "_id" : 3, "group_ids" : [ 3, 6 ], "uid" : "user1" }
  ```

  ユーザが 1 件見つかった。

* 重複したユーザを追加してみる。

  ```
  > db.ss_users.insert({ "name": "テスト", "uid": "user1", "email" : "xyz@example.jp", "group_ids": [ 3 ] });
  WriteResult({
          "nInserted" : 0,
          "writeError" : {
                  "code" : 11000,
                  "errmsg" : "insertDocument :: caused by :: 11000 E11000 duplicate key error index: ss.ss_users.$uid_1  dup key: { : \"user1\" }"
          }
  })
  ```

  想定通り制約違反エラーとなった。
* 他にも次のようなユーザを追加してみたが、想定通り制約違反エラーとなった。
  ```
  db.ss_users.insert({ "name": "テスト", "uid": "user1", "email" : "xyz@example.jp", "group_ids": [ 6 ] });
  WriteResult({
          "nInserted" : 0,
          "writeError" : {
                  "code" : 11000,
                  "errmsg" : "insertDocument :: caused by :: 11000 E11000 duplicate key error index: ss.ss_users.$uid_1  dup key: { : \"user1\" }"
          }
  })

  db.ss_users.insert({ "name": "テスト", "uid": "user1", "email" : "xyz@example.jp", "group_ids": [ 3, 6 ] });
  WriteResult({
          "nInserted" : 0,
          "writeError" : {
                  "code" : 11000,
                  "errmsg" : "insertDocument :: caused by :: 11000 E11000 duplicate key error index: ss.ss_users.$uid_1  dup key: { : \"user1\" }"
          }
  })
  ```

`ss_users` に embed で情報を保持し、uniq index を作成するのが実装上は良さそう。

ただし、本実験のように group_ids に uniq index を作成するのはマズい。
テナントを表す何か別の情報を新規追加して、それに対して uniq index を作成する必要がある。

**Comment by sunny4381** [comment]
## ss_users の拡張案

`ss_users` に uid と root_group_ids を追加する案でどうでしょうか？

![new-ss_users-min](https://cloud.githubusercontent.com/assets/3593466/6323379/499aa824-bb6c-11e4-812f-f83c16c39b31.png)

* root_group_ids は、before save か何かで group_ids から自動で生成します。
* `index({ uid: 1, root_group_ids: 1 }, { unique: true })` というインデックスを作成します。
* `validates :uid, uniqueness: { scope: :root_group_ids }, if: ->{ uid.present? }` という validation を追加します。
* 予備実験では、想定通り動作しました。
* 複合キー (uid, group) でユニークとなることを目的としています。
* グループごとの専用ログイン画面を用意する場合、グループ ID をpath parameter として指定してもらうか host parameter として指定してもらい、uid を HTML 入力フォームでしてしてもらい、root_group_ids と uid を and 検索します。
* （#174とは調節関係はないですが）LDAP 接続情報は、root_group_ids から取得します。

**Comment by sunny4381** [comment]
## 要件再確認

* [SNS 要件] email はグループ固有の属性ではなく、全体でユニーク＝プライマリー・キーとしたい。
* [マルチテナント要件] uid はグループ固有としたい。
* サポートしたいユーザは次のようなユーザ

![-min](https://cloud.githubusercontent.com/assets/3593466/6363130/32b06ff0-bcd8-11e4-89e3-b4aad9e6085d.png)

**Comment by sunny4381** [comment]
## 要件再確認の考察

インデックス `{ email: 1, groups: 1 }, { uniq: true, sparse: true }` を作成すれば、
次のようなデータを持つことが可能となる:

```
{ name: "井口 幸平", email: "iguchi_kouhei@example.com", uid: "kiguchi", groups: [ "シラサギ市" ] }
{ name: "井口 幸平", email: "iguchi_kouhei@example.com", uid: "iguchi_kohei", groups: [ "株式会社シラサギ" ] }
```

このような構造にすれば「シラサギ市の井口幸平」は「記事編集者」で、「株式会社シラサギの井口幸平」は「サイト管理者」というように別々のロールを付与することが可能だが、反面、このような構造にすれば、email がプライマリー・キーではなくなるので、上記の「SNS要件」を満たせない。

**Comment by sunny4381** [comment]
## 予備実験

次のようなドキュメントを持つコレクションを作成した。

```
db.ss_users.drop();
db.ss_users.insert({ "name": "テスト", "email" : "xyz@example.jp", "accounts" : [ { "uid": "xyz", "group_id": 1 }, { "uid": "user1", "group_id": 3 } ]});
db.ss_users.ensureIndex( { "email": 1 }, { unique: true, sparse: true } );
db.ss_users.ensureIndex( { "accounts.uid": 1, "accounts.group_id": 1 }, { unique: true, sparse: true } );
```

#### 重複した (uid, grouup_id) をもつユーザを追加してみる

```
db.ss_users.insert({ "name": "テスト", "email" : "abc@example.jp", "accounts" : [ { "uid": "xyz", "group_id": 1 } ]});
→エラー。想定通りである。
db.ss_users.insert({ "name": "テスト", "email" : "abc@example.jp", "accounts" : [ { "uid": "user1", "group_id": 3 } ]});
→エラー。想定通りである。
```

#### 重複しない (uid, group_id) をもつユーザを追加してみる

```
db.ss_users.insert({ "name": "テスト", "email" : "abc@example.jp", "accounts" : [ { "uid": "xyz", "group_id": 3 } ]});
→成功。想定通りである。
db.ss_users.insert({ "name": "テスト", "email" : "def@example.jp", "accounts" : [ { "uid": "user1", "group_id": 1 } ]});
→成功。想定通りである。
```

#### accounts を省略してみる

```
db.ss_users.insert({ "name": "テスト", "email" : "ghi@example.jp"});
→成功。想定通りである。
db.ss_users.insert({ "name": "テスト", "email" : "jkl@example.jp"});
→成功。想定通りである。
```

#### accounts に null を指定してみる

```
db.ss_users.insert({ "name": "テスト", "email" : "mno@example.jp", accounts: null });
→成功。想定通りである。
db.ss_users.insert({ "name": "テスト", "email" : "pqr@example.jp", accounts: null });
→成功。想定通りである。
```

#### accounts に [] を指定してみる

```
db.ss_users.insert({ "name": "テスト", "email" : "stu@example.jp", accounts: [] });
→成功。想定通りである。
db.ss_users.insert({ "name": "テスト", "email" : "vwx@example.jp", accounts: [] });
→成功。想定通りである。
```

以上、予備実験で確認完了した。

**Comment by sunny4381** [comment]
## uid でのログイン

uid でログインするには、事前にどのグループにログインするのかを決めてもらう。
「シラサギ市」にログインするのか、「株式会社シラサギ」にログインするのかを決めてもらわないと、(uid, group) でユニークなので、一意にユーザが決まらない。

### 実装案

例えば sns.yml にログイングループを設定し、login.html.erb に隠しフィールドを持つ。

```erb
<%= hidden_field_tag "item[in_group_id]", SS.config.sns.login_group_id %>
```

uid でログインする際は、in_group_id に設定されたグループにログインするようにする。
なお、email でログインする際は、in_group_id は使用しない。

**Comment by sunny4381** [comment]
デモデータを拡張し、ユーザ ID でログインできるようにしました（下表）。

| メールアドレス | ユーザID |
|----------------|----------|
| sys@example.jp | sys |
| admin@example.jp | admin |
| user1@example.jp | user1 |
| user2@example.jp | user2 |

パスワードに変更はありません。

**Comment by sunny4381** [comment]
| 検索文字列                       | Google ヒット数 | 
|----------------------------------|------------|
| ユーザーIDかメールアドレス       |      36 件 |
| ユーザーIDもしくはメールアドレス |      46 件 |
| ユーザーIDまたはメールアドレス   |  30,000 件 |

**Comment by sunny4381** [comment]
merged #260.

**Comment by sunny4381** [comment]
## UID でのログインに関する仕様変更

仕様変更内容:

* マルチテナントのため、ということで実装が複雑になっている。
* twitter や facebook をみても uid はグローバルにユニークとなっているので、シラサギでも uid をユニークに変更したい。
* uid をユニークにすると、実装が単純になる。

考慮点:

* LDAP がオフラインの場合でもログインできるようにしたい。
* LDAP がオフラインの場合にログインできるユーザを限定したい。
* ログイン権限 (login_roles) というフィールドを新規追加する。
* login_roles に "dbpassword" があれば、ss_users.password でログインできる。
* login_roles に "ldap" があれば、LDAP でログインできる。
    * LDAP 同期した場合は、login_roles に "ldap" が自動で追加される。
* 将来の拡張として、login_roles に "oauth" があれば、OAuth でログインできる。

**Comment by sunny4381** [comment]
#322 をマージしたら承認申請でエラーが出たが #332 で修正した。
#328 でも少し修正した。
