### ISSUE TITLE
ページ書き出しが失敗する

### ISSUE THREAD

**Issue by tany** [shirasagi/shirasagi#176]
要調査

**Comment by itowtips** [comment]
以下、開発環境で出たエラーログです。
<pre>
-- Error
404
/var/www/toki/app/controllers/concerns/cms/node_filter/view.rb:23:in `render_with_pagination'
/var/www/toki/app/controllers/category/agents/nodes/page_controller.rb:19:in `index'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/abstract_controller/base.rb:189:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/rendering.rb:10:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `block in instrument'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `instrument'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/abstract_controller/base.rb:136:in `process'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionview-4.1.6/lib/action_view/rendering.rb:30:in `process'
/var/www/toki/lib/ss/agent.rb:21:in `invoke'
/var/www/toki/app/controllers/application_controller.rb:27:in `invoke_agent'
/var/www/toki/app/controllers/cms/agents/parts/tabs_controller.rb:33:in `block in index'
/var/www/toki/app/controllers/cms/agents/parts/tabs_controller.rb:9:in `each'
/var/www/toki/app/controllers/cms/agents/parts/tabs_controller.rb:9:in `index'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/abstract_controller/base.rb:189:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/rendering.rb:10:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `block in instrument'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `instrument'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/abstract_controller/base.rb:136:in `process'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionview-4.1.6/lib/action_view/rendering.rb:30:in `process'
/var/www/toki/lib/ss/agent.rb:27:in `render'
/var/www/toki/app/controllers/concerns/cms/public_filter/layout.rb:30:in `render_part'
/var/www/toki/app/controllers/concerns/cms/public_filter/layout.rb:89:in `render_layout_part'
/var/www/toki/app/controllers/concerns/cms/public_filter/layout.rb:66:in `block in render_layout'
/var/www/toki/app/controllers/concerns/cms/public_filter/layout.rb:63:in `gsub'
/var/www/toki/app/controllers/concerns/cms/public_filter/layout.rb:63:in `render_layout'
/var/www/toki/app/controllers/concerns/cms/public_filter/node.rb:49:in `generate_node'
/var/www/toki/app/controllers/concerns/cms/public_filter/node.rb:69:in `block in generate_node_with_pagination'
/var/www/toki/app/controllers/concerns/cms/public_filter/node.rb:66:in `upto'
/var/www/toki/app/controllers/concerns/cms/public_filter/node.rb:66:in `generate_node_with_pagination'
/var/www/toki/app/controllers/article/agents/tasks/node/pages_controller.rb:6:in `generate'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/abstract_controller/base.rb:189:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/rendering.rb:10:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `block in instrument'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `instrument'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/abstract_controller/base.rb:136:in `process'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionview-4.1.6/lib/action_view/rendering.rb:30:in `process'
/var/www/toki/lib/ss/agent.rb:21:in `invoke'
/var/www/toki/app/controllers/cms/agents/tasks/nodes_controller.rb:33:in `block in generate'
/usr/local/rvm/gems/ruby-2.1.2/bundler/gems/mongoid-e93a4837b026/lib/mongoid/contextual/mongo.rb:648:in `yield_document'
/usr/local/rvm/gems/ruby-2.1.2/bundler/gems/mongoid-e93a4837b026/lib/mongoid/contextual/mongo.rb:123:in `block in each'
/usr/local/rvm/gems/ruby-2.1.2/gems/moped-2.0.0.beta/lib/moped/query.rb:80:in `block in each'
/usr/local/rvm/gems/ruby-2.1.2/gems/moped-2.0.0.beta/lib/moped/cursor.rb:27:in `block in each'
/usr/local/rvm/gems/ruby-2.1.2/gems/moped-2.0.0.beta/lib/moped/cursor.rb:27:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/moped-2.0.0.beta/lib/moped/cursor.rb:27:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/moped-2.0.0.beta/lib/moped/query.rb:79:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/moped-2.0.0.beta/lib/moped/query.rb:79:in `each'
/usr/local/rvm/gems/ruby-2.1.2/bundler/gems/mongoid-e93a4837b026/lib/mongoid/contextual/mongo.rb:122:in `each'
/usr/local/rvm/gems/ruby-2.1.2/bundler/gems/mongoid-e93a4837b026/lib/mongoid/contextual.rb:20:in `each'
/var/www/toki/app/controllers/cms/agents/tasks/nodes_controller.rb:20:in `generate'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/abstract_controller/base.rb:189:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/rendering.rb:10:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `block in instrument'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.1.2/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `instrument'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionpack-4.1.6/lib/abstract_controller/base.rb:136:in `process'
/usr/local/rvm/gems/ruby-2.1.2/gems/actionview-4.1.6/lib/action_view/rendering.rb:30:in `process'
/var/www/toki/lib/ss/agent.rb:21:in `invoke'
/var/www/toki/app/models/concerns/ss/task/model.rb:111:in `process'
/var/www/toki/app/models/cms/task.rb:33:in `block (2 levels) in process_with_node'
/var/www/toki/app/models/concerns/ss/task/model.rb:40:in `block in ready'
/usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/var/www/toki/app/models/concerns/ss/task/model.rb:40:in `ready'
/var/www/toki/app/models/cms/task.rb:32:in `block in process_with_node'
/usr/local/rvm/gems/ruby-2.1.2/bundler/gems/mongoid-e93a4837b026/lib/mongoid/contextual/mongo.rb:648:in `yield_document'
/usr/local/rvm/gems/ruby-2.1.2/bundler/gems/mongoid-e93a4837b026/lib/mongoid/contextual/mongo.rb:123:in `block in each'
/usr/local/rvm/gems/ruby-2.1.2/gems/moped-2.0.0.beta/lib/moped/query.rb:80:in `block in each'
/usr/local/rvm/gems/ruby-2.1.2/gems/moped-2.0.0.beta/lib/moped/cursor.rb:27:in `block in each'
/usr/local/rvm/gems/ruby-2.1.2/gems/moped-2.0.0.beta/lib/moped/cursor.rb:27:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/moped-2.0.0.beta/lib/moped/cursor.rb:27:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/moped-2.0.0.beta/lib/moped/query.rb:79:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/moped-2.0.0.beta/lib/moped/query.rb:79:in `each'
/usr/local/rvm/gems/ruby-2.1.2/bundler/gems/mongoid-e93a4837b026/lib/mongoid/contextual/mongo.rb:122:in `each'
/usr/local/rvm/gems/ruby-2.1.2/bundler/gems/mongoid-e93a4837b026/lib/mongoid/contextual.rb:20:in `each'
/var/www/toki/app/models/cms/task.rb:28:in `process_with_node'
/var/www/toki/app/models/cms/task.rb:40:in `generate_nodes'
/var/www/toki/lib/tasks/cms/page.rake:3:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-2.1.2/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.1.2/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
</pre>

**Comment by itowtips** [comment]
https://github.com/shirasagi/shirasagi/blob/master/app/controllers/cms/agents/parts/tabs_controller.rb#L31-37

**Comment by tany** [comment]
原因： ページネーションが発生するページに新着タブパーツを置いた場合に
タブから呼ばれるコントローラに params[:page] が伝播してしまう。
`リクエストページ数＞タブ先ページの最大ページ数` の場合に404例外が発生してこける。

**Comment by tany** [comment]
- params を引き継がないように修正
- 念のためrescue&error_log
https://github.com/shirasagi/shirasagi/commit/5118d40c7969ec59a4606a00540e16526d2db6b0
