### ISSUE TITLE
SNS自動投稿でページの全文を投稿するのではなく、定型テキストとURLを投稿したい

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#1775]

**Comment by sunny4381** [comment]
記事ページに OGP 情報が書き出されます。この OGP 情報を元に Facebook が自動で投稿の表示を決めます。Facebook での見た目がどのようになるかは以下のFacebook Sharing Debugger で確認することができます。

参考: [Facebook Sharing Debugger](https://developers.facebook.com/tools/debug/sharing/)

**Comment by sunny4381** [comment]
対応済み。
