### ISSUE TITLE
施設データベースのインポート機能が欲しいです

### ISSUE THREAD

**Issue by nton1111** [shirasagi/shirasagi#179]
施設データベースは利用頻度が高く、新規に構築しているサイトでは、全て利用したい機能となっています。
現状、インポート機能がないため、毎回手動で対応していることもあり改善したいです。

**Comment by itowtips** [comment]
施設一覧フォルダーに施設情報と地図座標の ダウンロード/インポート を作成しました。
以下のようなcsvを ダウンロード/インポート できます。

フォルダー名|施設名|レイアウト|URL、住所など|施設の種類|施設の地域|施設の用途|座標|管理グループ|追加情報：備考|追加情報：定員
-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----
facility1|施設1|施設レイアウト|http://...|小学校|○○市|学校|34.071309,134.563971|管理者|避難場所です|○○人

* インポート
 * 施設のデータ数が多いためJob機能を利用しました。
 * 座標等を複数設定する場合は改行区切りで記述します。
 * インポートはcsvのフォルダー名(filename)をキーとしてfind_or_create行いますが、
サイト構築時に何度か登録を繰り返す前提として、
フォルダー名が見つからなかった施設は削除するようにしています。

**Comment by itowtips** [comment]
マージしました。

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/commit/ec761ad56165530bb0b905cef3c95d7a5a1a4483
* インポート開始時に前処理としてフォルダ内の施設情報を削除するよう変更しました。
* インポート開始ボタンに警告をつけました
