### ISSUE TITLE
グループの空の項目に対し組織変更で情報を入力しても、記事には変更内容が反映されない。

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#1875]
グループの項目と記事の該当項目が双方空の場合には上書きしてほしい

**Comment by sunny4381** [comment]
ページに設定されている「リンク名」や「リンクURL」が空の場合、新しい値で上書きされない。
※置換はできるが、正規表現がマッチしないため空に新しい値を設定するような動作が考慮されていない。

**Comment by ShinjiTanimoto** [comment]
[modify] chorg/substitutor overwrite some fields #2088
