### ISSUE TITLE
グループですが、市の表示順に合わせたいそうです。

### ISSUE THREAD

**Issue by nton1111** [shirasagi/shirasagi#188]
グループが漢字コード順になっているので、市の表示順にしてもらいたいそうです。
今すぐではありませんが、たぶんそういう自治体は多いと思います。

**Comment by sunny4381** [comment]
#201 で、LDAP で取り込んだグループを導入先固有の順で表示したいという要望があり、グループの表示順フィールドを設けるかもしれません。

**Comment by tany** [comment]
フォルダー一覧なんかも、
```
order_by(order: 1, updated: -1)
```
とか
```
order_by(order: 1, filename: 1)
```
とかを初期値にしておけばいいのかな？

**Comment by sunny4381** [comment]
`SS::Group::Model` に `order` フィールドと `default_scope` を追加：

```ruby
field :order, type: Integer
default_scope -> { order_by(order: 1, name: 1) }
```

コントローラ側の order_by を削除し、既定の order_by を使用するように修正しました。

**Comment by sunny4381** [comment]
シラサギのデモグループに order (10 から 10 刻みで連番) を設定しました。

**Comment by sunny4381** [comment]
merged #260.
