### ISSUE TITLE
施設情報フォルダーのプレビューで画像が表示されない。

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#194]
施設情報フォルダーのプレビュー表示で施設画像のパスに「/.www/preview」とつくため表示されなくなります。

**Comment by itowtips** [comment]
現状のプレビューのロジックでサムネイル表示(`fs/thumb/:id`)
が考慮されておらず、エラーとなってしまいました。
https://github.com/itowtips/shirasagi/commit/b988065246846598589e5ace295d3123ede88079

**Comment by tany** [comment]
コードの複製ではなくてオリジナルを流用できた方がよいです。
