### ISSUE TITLE
メルマガ機能について修正依頼

### ISSUE THREAD

**Issue by tany** [shirasagi/shirasagi#195]
■必須
管理画面からメルマガ読者を削除（無効）にできるようにしてください。
エラーメールなどを確認して削除したいのと、管理者が削除したことがわかるよ
うにしたいです。
削除するため、検索機能をつけてください。

公開時のＵＲＬが管理画面で見えるようにしてください。
今は、普通の人はわかりません。

本配信の履歴がわかるようにしてください。
一覧で、いつ配信したかわかるようにしてください。

■要望
記事タイトル、レイアウトに説明が欲しいです。
※ヘルプ機能は、どこまで対応できていますか？

メールアドレス登録時に、性別、市町村名、年代などが同時に登録できるように
してください。できれば、その都度項目を設定できる方がいいです。

登録しているアドレス一覧を出力する機能が欲しいです。

テスト配信の履歴がわかるようにしてください。

**Comment by tany** [comment]
cms_pages, cms_nodes の _show にURLを表示させました。
https://github.com/shirasagi/shirasagi/commit/05691c1e4f650be24d7eb14046e244e21881c198

**Comment by kaosf** [comment]
@tany ということは

> 公開時のＵＲＬが管理画面で見えるようにしてください。
> 今は、普通の人はわかりません。

は解消ということですね．

**Comment by tany** [comment]
既存の _show, _form.html.erb を削除してcms_pagesを参照するようにしました。
https://github.com/shirasagi/shirasagi/commit/def485073b8993a5e6f5586964f99a4bf5bd9f9b

**Comment by tany** [comment]
@kaosf URLは対応完了です。
テキスト版プレビューってテキスト出してるだけですけど意味ありますかね？
それなら入力フォームを等幅フォントにすればいいんじゃないかと思ったり。

**Comment by tany** [comment]
というのも、プレビューリンクを基本情報枠に移したのでかぶってしまいました。

**Comment by kaosf** [comment]
@tany 

> 入力フォームを等幅フォントにすればいい

一応仕様書にあったのでテキスト版プレビューは作った形ですね．消えて入力フォームで等幅フォントでも良いです．

**Comment by kaosf** [comment]
今日のミーティングでこってり忘れていたのが

> 登録しているアドレス一覧を出力する機能が欲しいです。

についてです．CSVでエクスポート出来れば良いでしょうか？出力するカラムは

* email
* email_type
* created

で良いでしょうか？(※とりあえずこのコメントの時点では名前や住所などのことは考えないとします)

**Comment by tany** [comment]
CSVはそれでOKです、お願いします。

プレビューリンクを消しました。
https://github.com/shirasagi/shirasagi/commit/bd69a48eb8354527704a31f6a21dea2f09e98a55

レイアウトを親から引き継ぐように修正しました。
https://github.com/shirasagi/shirasagi/commit/d0e1fca60365a36b5ad229cc54f76df321454c54

404になるのでURLとroutingを修正しました。
https://github.com/shirasagi/shirasagi/commit/a33937c2dbfbec928523742d459a111bb78a0cee

画面周りを修正しました。
https://github.com/shirasagi/shirasagi/commit/2c0b24388cbbce21cc5bcbee8ce0df84437d1aca

**Comment by kaosf** [comment]
ボロボロ修正が出てきましたね…お手数おかけします…

**Comment by kaosf** [comment]
a9118c05fb34a8e50eb493a3dc59b6cfe0c043f0
e7eb99ad86fd7c6e66f6a590231d15f471b11ab4

でCSVダウンロード機能を実装しました．

> 登録しているアドレス一覧を出力する機能が欲しいです。

が解決されたものとします．(カラム名日本語に変換してるのをやめるのはまた後ほど)

**Comment by kaosf** [comment]
962ab351380cdb6d2fdecfb5758641b1df87e26b

でカラム名を日本語にせず出力するよう変更

**Comment by tany** [comment]
- テスト配信の履歴がわかるようにしてください。

**Comment by tany** [comment]
一旦〆
