### ISSUE TITLE
外部プログラムを非同期実行する場合について

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#197]
現在、シラサギでは外部プログラムを非同期実行する場合、
以下の様なコードで実行する場合が多いと思います。

```ruby
require "open3"
stdin, stdout, stderr = Open3.popen3(cmd)
```

この方法は、次のような問題があります。

* stdin, stdout, stderr は、GC 発生時に閉じられる。
* 閉じられた stderr に cmd (子プロセス) が書き込むと EPIPE 例外が発生し、cmd が異常終了する。
* cmd の実行に時間がかかる場合、stdin, stdout, stderr が GC により閉じられる確率が高くなる。

上記のような問題があるため、stdin, stdout, stderr が不要な場合は閉じておく方が、長期の運用に耐えられ、手離れがいいです。

## stdin, stdout, stderr を閉じる方法 その1

```ruby
require "open3"
Open3.popen3("#{cmd} > /dev/null 2>&1")
```

この方法では stdin は閉じられませんが、stdout と stderr は閉じられます。

## stdin, stdout, stderr を閉じる方法 その2

次のように spawn を直接使用してもいいです。

```ruby
pid = spawn("#{cmd} > /dev/null 2>&1")
Process.detach(pid)
```

この方法も stdin は閉じられませんが、stdout と stderr は閉じられます。

Process.detach が必要かどうかは不明。
CentOS の場合、Process.datch を呼び出しても、呼び出さなかっても結果、同じだった。

## stdin, stdout, stderr を閉じる方法 その3

次のように spawn を直接使用してもいいです。

```ruby
pid = spawn(cmd, in: "/dev/null", out: "/dev/null", err: "/dev/null")
Process.detach(pid)
```

この方法では stdin も閉じられます。

**Comment by kaosf** [comment]
:+1:
