### ISSUE TITLE
フォームの label、legend 要素

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#1977]
お問い合わせフォームやよくある質問検索などで label による dt のテキストと input が label により関連づけられていない。
https://waic.jp/docs/WCAG-TECHS/H44.html
https://waic.jp/docs/WCAG-TECHS/H65.html

また、ラジオボタンやチェックボックスはラベル名（dt）と input を含むHTMLを fieldset 要素でグループ化し、ラベルは legend 要素でマークアップする必要がある
https://waic.jp/docs/WCAG-TECHS/H71.html

##フォルダー
メールフォーム/フォーム
FAQ/FAQ記事検索
施設/施設検索
オープンデータ/データセットグループ検索,データセット検索,アプリ検索,アイデア検索

##パーツ
イベント/イベント検索
FAQ/FAQ記事検索

**Comment by sunny4381** [comment]
対応しました: 5b23b00cb581ef04be5835b394941785354995b5
