### ISSUE TITLE
サイトのデータ移行で移行できないものがある

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#2011]
サイト設定の定型フォーム、ループHTMLが移行されない。
データ移行なのでグループやユーザーも移行したい

**Comment by sunny4381** [comment]
ユーザー、グループの移行に際しては #2004 の問題が起きないように注意する必要がある。

**Comment by ShinjiTanimoto** [comment]
[modify] copy cms/forms in site_copy #2174
