### ISSUE TITLE
組織変更

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#202]
大きな組織であればあるほど、組織変更時に全てのコンテンツを正しく変更するのが難しくなる。
コンピュータ プログラムのアシストによる半自動的な組織変更を開発する。

**Comment by sunny4381** [comment]
## グループ名の置換処理

1. 前提条件その1
  * グループ名を `組織名/部署名/部署名 課名` としているお客様がいる。
2. 前提条件その2
  * グループ名は通常スラッシュで区切られており、グループ名を記事に表示する場合、グループ名の末端を表示する。
  * 上記の例で言えば、記事に `部署名 課名` が表示される。
3. 前提条件その3
  * 組織変更ではグループ名を置換する。
  * グループ名を置換する際 `組織名/部署名/部署名 課名` というフルパスのみならず、末端の `部署名 課名` も置換することが望ましい。
4. 前提条件その4
  * 次の移動ケースを考える。
    * `シラサギ市/企画政策部` が `シラサギ市/健康管理部` へ移動する。
    * `シラサギ市/企画政策部/企画政策部 長生き課` が `シラサギ市/健康管理部/健康管理部 地域連携課` へ移動する。
  * 記事には `企画政策部 長生き課` が表示されている。
  * 組織変更の結果、記事には `企画政策部 長生き課` が表示されることが望ましい。

## 問題点

1. 前提条件から、次の 4 つの置換処理を実行する。
  1. `シラサギ市/企画政策部` --> `シラサギ市/健康管理部`
  2. `企画政策部` --> `健康管理部`
  3. `シラサギ市/企画政策部/企画政策部 長生き課` --> `シラサギ市/健康管理部/健康管理部 地域連携課`
  4. `企画政策部 長生き課` --> `健康管理部 地域連携課`
2. 1 の順番で置換処理を実行すると:
  1. 1-i では、置換対象がないので何もしない。
  2. 1-ii では、記事の `企画政策部 長生き課` が `健康管理部 長生き課` に置換される。
  3. 1-iii では、置換対象がないので何もしない。
  4. 1-iv では、2-ii の処理で記事の `企画政策部 長生き課` が `健康管理部 長生き課` に置換されるているのでマッチせず置換できない。
3. 結果 `健康管理部 長生き課` が残る。これは望ましい結果ではない。

## 改善方法

文字列を置換する際、長い方から置換しようと思う。
上記の例で言えば:

1. 問題点の 1 の置換処理を長い方から実行する。つまり次の順で実行する。
  1. `シラサギ市/企画政策部/企画政策部 長生き課` --> `シラサギ市/健康管理部/健康管理部 地域連携課`
  2. `シラサギ市/企画政策部` --> `シラサギ市/健康管理部`
  3. `企画政策部 長生き課` --> `健康管理部 地域連携課`
  4. `企画政策部` --> `健康管理部`
2. 1 の順番で置換処理を実行すると:
  1. 2-i と 2-ii では置換対象がない。
  2. 2-iii では、記事の `企画政策部 長生き課` が `健康管理部 地域連携課` に変換される。
  3. 2-iv では、`企画政策部` を `健康管理部` に置換しようとするが、2-ii の処理で記事の `企画政策部 長生き課` が `健康管理部 地域連携課` に変換されるているのでマッチせず置換しない。
3. 結果 `健康管理部 地域連携課` が残る。正しい置換結果が得られる。

また、他の改善方法もあって、グループが子を持つ場合、末端では置換しないという案もあるが、本案で進めたいと思う。

**Comment by sunny4381** [comment]
## 置換対象フィールド

手当たり次第に置換すると `site_id` や `permission_level` なども置換してしまって問題が多い。

* 案1: ブラックリスト方式か、ホワイトリスト方式のどちらかで、置換対象フィールドを選別する。
* 案2: String 型フィールドの場合は手当たり次第。Fixnum フィールドの場合はホワイトリスト(group_id を含む) で対応、それ以外の DateTime, Array や Hash フィールドは置換しないとする。
* 案3: ....（もっとうまい方法があるような気がする）。

**Comment by sunny4381** [comment]
## 分割

現状のオーダーは次の通り:

* 新設: グループが新しく追加される。
* 移動: グループ名が変わる。
* 統合: A 課と B 課が C 課になる。
* 廃止: A 課が廃止される。

これに対して野原さんから「分割」があるんじゃないかとコメント有り。

* 分割: A 課が B 課と C 課になる。A 課が持っている記事を B 課と C 課が編集できるようにグループを設定する。
  * 元: 記事A: { group_ids: [ "A課" ] }
  * 先: 記事A: { group_ids: [ "B課", "C課" ] }

**Comment by sunny4381** [comment]
## プレビューの一つのアイデア

現在は「テスト実行」ということで、Ruby の Model を実際にはデータベースに保存せず、バリデーションチェックを実行し、エラーがあればログに出力するのみである。

シラサギはマルチテナントなので、サイトを複製し、複製したサイトで実際に組織変更をすることで組織変更の結果を事前に確認することができる。
ただし、サイトを複製するということは、データベースのデータや private/public 以下のファイル全てを複製することになるので、サーバの負荷が高いことが予想される。

**Comment by tany** [comment]
グループID： belongs_toでSS::Groupsが実装されていれば対象にする、とできれば自動化可能？
ホワイトリストは分割管理が面倒なので、１ファイルで全部羅列するのでもいいかなと妥協したり。

**Comment by sunny4381** [comment]
belongs_to では、metadata の class_name が SS::Group であれば置換対象に。
embeds_ids では、embeds_ids を次のように拡張し、

```ruby
field store, type: SS::Extensions::ObjectIds, default: [], metadata: { elem_class: opts[:class_name] }
```

elem_class が SS::Group であれば置換対象とすることで、自動化します。

**Comment by sunny4381** [comment]
## 置換対象の文字列フィールド

ブラックリスト方式とし、次の文字列/パターンをブラックリストに登録する。

* "filename"
* "state"
" _state で終わる
* "md5"
* "route"
* _route で終わる
* "workflow_state"
* "workflow_comment"
* "url"
* _url で終わる

文字列フィールドのうち、ブラックリストに含まれていないフィールドを置換対象とする。

**Comment by sunny4381** [comment]
## 変更箇所の pretty print と diffy gem の導入に関して

1点目として、変更箇所を:

```
     <tr>
       <td scope="row">管理部<br />
       管理課</td>
-      <td><a href="tel:03-1591-1864">03-1591-1864</a></td>
-      <td>03-1591-1864</td>
-      <td><a href="mailto:bc3nbjsoih@example.jp">bc3nbjsoih@example.jp</a></td>
+      <td><a href="tel:03-1619-8808">03-1619-8808</a></td>
+      <td>03-1619-8808</td>
+      <td><a href="mailto:akctwrs42x@example.jp">akctwrs42x@example.jp</a></td>
     </tr>
```

のようにログに出力しようと考えていますが、どうでしょうかね？

2 点目として、上記のように出力するために diffy gem（内部では diff コマンドを呼び出している）を導入したいんですが、どうでしょうか？

**Comment by sunny4381** [comment]
## email の置換処理

### english name

email の '@' の左側を `english name` とみなし置換するという仕様を頂いた。
この仕様に関する検討結果である。

### 想定されていた事例

秘書課なら `hisyoka@example.jp`、施設課なら `sisetsu@example.jp` などが想定されていたと思う。このような場合、うまく置換できるのかもしれない。

### 実際の事例

政策部/政策課は `foobar@example.jp` を持ち、政策部/観光課は `foobar02@example.jp` を持つ。
ここで、政策部/政策課と政策部/観光課が、政策部/観光課に統合されるケースを考えてみる。
このケースでは次のような置換処理が実行される。

1. `foobar@example.jp` を `foobar02@example.jp` に置換。
2. `foobar` を `foobar02` に置換。

2 の置換は上記の email の '@' の左側を `english name` とみなして置換するという仕様から来ている。
このような順で `foobar02@example.jp` を置換すると `foobar` の部分が `foobar02` に置換されるので、`foobar0202@example.jp` という結果が得られる。これは望ましいい結果ではない。

### 再考

english name を置換するという仕様はやめて、任意の文字列を置換するフィールドを設定できる - (置換元, 置換先) のペアをいくつでも登録できる - 仕様としてはどうだろうか？
そして、任意の文字列を置換するフィールドは、初回リリースでは対応せずに、将来の拡張としてはどうか？

**Comment by sunny4381** [comment]
間違ってクローズしてしまったので再開。

**Comment by sunny4381** [comment]
## シミュレーション結果

組織変更のシミュレーション結果:

* 最大消費メモリ(MAX RES): 390m
* 実行時間: 4分17秒283
* CPU消費: 1 core を 100%
