### ISSUE TITLE
施設機能の地図検索速度

### ISSUE THREAD

**Issue by itowtips** [shirasagi/shirasagi#211]
調整中

DBアクセスを減らすようロジックを修正、先にカテゴリーをhashにためておく
https://github.com/itowtips/shirasagi/blob/bc175e856223e5a4ea1217da33a0d89002b9267d/app/controllers/facility/agents/nodes/search_controller.rb#L37-68
これでは改善されず、むしろ施設数が多い場合は遅くなった

**Comment by itowtips** [comment]
施設のフォルダ系の書き出しを追加
map-all.html に全件施設を表示するルートを追加、書き出し可能
https://github.com/itowtips/shirasagi/commit/c8386ed1be5de8d683f7c09e4f0ccbedb6bfcc7b

**Comment by tany** [comment]
100回find allするより100回find parentする方がマシな気がする。画像のurlはIDから算出できるようにしてfindしないとか。

**Comment by itowtips** [comment]
画像をループの中でfindするのは良くなさそうなので、これは直せます。
https://github.com/itowtips/shirasagi/blob/ab87e8293df314f0154f0604bb4f6587741b2b17/app/controllers/facility/agents/nodes/search_controller.rb#L30

検索順序を
施設地図(Facility::Map)　→　施設情報(Facility::Node::Page)
に変更するのは施設情報のカテゴリで絞り込んでいるので、見た感じ難しそうです。

**Comment by itowtips** [comment]
施設地図(Facility::Map)　→　施設情報(Facility::Node::Page)
下のような感じにしたらできたかも。（穴がなければ
https://github.com/itowtips/shirasagi/blob/c03884372cfa823b5b9af6d2b7dce976062f0b44/app/controllers/facility/agents/nodes/search_controller.rb#L59-104

こちらの方が早い気がする。

**Comment by itowtips** [comment]
https://github.com/shirasagi/shirasagi/commit/ccb83d335ed7168020f68bd6b9f3156850c87728
ここまでに調整したロジックをマージしました。
