### ISSUE TITLE
ショートカットURL

### ISSUE THREAD

**Issue by itowtips** [shirasagi/shirasagi#214]
アクセスを受けたコントローラーからリダイレクトし、
ショートカット用のURLを生成する機能。

ゆくゆくは他の箇所でも利用できるようにしたい。
まずは、優先度の高い施設地図部分用に以下を作成
https://github.com/itowtips/shirasagi/commit/3cf2875d336db6ddefa80c7a964ee049c4fbf6ff

app/models/cms/short_url.rb
を作成し、ここに
site_id、url、paramsを貯める仕組みを作成してみました。
コレクションはcms_short_url

**Comment by tany** [comment]
明示的に`store_in`で単数形にしているのはなにか意味があるのですか？

**Comment by tany** [comment]
URL固定でいくならフィールドをシンプルにしてSSへ移動ですかね。

  # class SS::UrlShortner
  field :url, type: String
  validates :url, uniquness: true
  
  # contents controller
  short = SS::UrlShorter.shorten(request.url)
  url = short.short_url(base_url: ss_url_shortner_path)
  
  # redirection controller
  short = Cms::UrlShorter.site(@cur_site).find(url: request.url)
  raise if short.domain != request.domain
  redirect_to short.url

**Comment by itowtips** [comment]
`store_in collection: "cms_short_urls"`
としてもよかったかもしれません。
次はミスです、すみません。
`permit_params cms_role_ids: []`

**Comment by itowtips** [comment]
# contents controller
これは各コンテンツのコントローラーでurlが短縮されていないほうにアクセスしたときに
`short_url`を生成or検索して(`shorten(request.url)`) 短い方にredirectする認識であっていますか。
　
filterを作って必要なコンテンツにincludeすることで、短縮URLを
有効にできるようにしようと考えていました。

  # redirection controller
こちらは短縮されたurlのコントローラーでしょうか。

**Comment by itowtips** [comment]
短縮URLのパスは、まずは固定としようと思います。
`ss_url_shortner_path`
app ss は追加すべきではない設計でしたか？

**Comment by tany** [comment]
contents controller
いえ、短いURLから長いURLにリダイレクトする機能です。

redirection controller
そうです

パス
app? ssはコントローラーが作れないですね

**Comment by tany** [comment]
url_controller

`/url/ID`
- 元URLのHTMLをAjaxで拾ってきて表示するページ。
- 取得できなければリダイレクト。

`/url/ID/redirect`
- 元URLにリダイレクトするページ。

とか。

**Comment by tany** [comment]
url ex.
```
/url/0001
/url-0001
/-url-0001
/-url/0001
/-0001
```

**Comment by tany** [comment]
ペンディングのようなので閉じます。
