### ISSUE TITLE
フォルダー取込を行うとhtmlタグの外側が<article class="body">で囲われてしまう。

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#2162]

**Comment by itowtips** [comment]
公開側の不要なHTMLを修正しました #2162
取り込みページ編集ですが、WYSIWYGエディタで編集するようになっていました。
取り込んだHTMLを変換してしまう為、コードエディタに変更しました。
WYSIWYGエディタで編集したり、リンクチェックを実行する場合は「固定ページに変換する」を実行してください。
