### ISSUE TITLE
記事の差し替え更新

### ISSUE THREAD

**Issue by tany** [shirasagi/shirasagi#222]
記事が公開されている状態で、承認依頼→承認→公開→差し替えを行う機能。

case1: with collection
----------------------------------------
複製用のコレクションを作成する
- cms_pages
- cms_cloned_pages

実装の容易さ：×
- コレクションごとにコレクションが必要
- リレーション情報が必要 or 同一のIDを使用する
- モデルorコレクション名を変更したコントローラーが必要

case2: with document
----------------------------------------
複製用のドキュメントを作成する
- id: 1, filename: "index.html"
- id: 2, filename: "_index.html", original_id: 1

実装の容易さ：○
- コントローラーを共用できる
- リレーション情報が必要
- 同一のファイル名を保存できない

case3: with field
----------------------------------------
複製用のフィールドを作成する
- name: "string"
- html: "string"
- draft [{
  - name: "string"
  - html: "string"

実装の容易さ：×
- リレーション情報が不要
- 設計がスマート
- Embedsモデルが必要？なためロジックが複雑

所感
----------------------------------------
case3がかっこいいけど難しそう。
手早くやるならcase2。

**Comment by tany** [comment]
case4: keep html file
------------------------------
出力したHTMLファイルを残しておき、DBは通常通り使用する。
- name: "modify string"
- html: "modify string"

実装の容易さ：○
- HTMLファイルを残すだけでロジックはそのまま使える
- 動的表示時やDB検索時に作成中の情報が対象にされる
- 添付ファイルを削除すると公開中のファイルも削除される

**Comment by tany** [comment]
case2 の実装方法しか思い浮かばない。

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/tree/page-clone
頂いた仕様を基に記事の複製と差し替えを作成
* 複製後のfilenameはcopy + md5文字列としました。
* 課題
  * duplicate の名称変更

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/commit/7ac629a03f001116e2f599ec3c76d00ba120208c

* 複製後のfilenameを変更、  ```"copy-" + rand(0xffff_ffff_ffff_ffff).to_s(32)```
* 複製の action は ```copy``` とし モデル側の ```duplicate``` メソッドは ```clone_document``` としました
