### ISSUE TITLE
「カテゴリー/ページリスト」フォルダーは不要？

### ISSUE THREAD

**Issue by tany** [shirasagi/shirasagi#235]
デフォルトの表示画面（フォルダー「カテゴリー/ページリスト」）
https://github.com/shirasagi/shirasagi/issues/94

上記の対応でデフォルト表示画面が変更できるようになったので、
「カテゴリー/ページリスト」フォルダーは「標準機能/ページリスト」フォルダーで賄える気がします。

**Comment by itowtips** [comment]
既に使っているサイトがあるかもしれないので、残す方に一票いれます。

**Comment by tany** [comment]
保留にします。
