### ISSUE TITLE
無効状態のユーザーを削除時に 500 エラー

### ISSUE THREAD

**Issue by ShinjiTanimoto** [shirasagi/shirasagi#2351]
- 有効状態のユーザーを検索するための default_scope が原因で発生している
    - set_selected_items で scope を解除すれば 500 エラーは解消される
- 無効状態のユーザーに disable を使用すると nil が返る
    - render_destroy の result が nil になる
    - エラーメッセージなどが表示されないため、分かりづらい
    - 無効状態のユーザーの削除ボタンなどを非表示にする

**Comment by sunny4381** [comment]
v1.13.0で修正しました。
