### ISSUE TITLE
非公開の記事一覧画面で一括削除を行うと404になる

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#2493]
1. 管理画面で記事フォルダーにアクセス
2. 左メニュー「非公開」を選択し非公開状態の記事ページに絞り込み
3. 一覧の記事にチェックを入れ「削除する」をクリック
4. 404ページが表示される

「公開待ち」や「公開終了間近」の一覧の場合も同様です。

**Comment by ShinjiTanimoto** [comment]
#2511
