### ISSUE TITLE
施設地図・施設写真ページで承認申請できない

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#251]
Not Found エラーが発生する。

**Comment by itowtips** [comment]
workflow addon js部分ですが、
 `uri = "<%= workflow_page_path(id: @item.id) %>"`
のようにしようと思いましたが、
ルートのページの時（親フォルダーが無い場合）のpathが違うようなので
他の箇所を見習い
 `uri[3] = "pages"`
としました。
https://github.com/shirasagi/shirasagi/commit/e0a13f78f4d469af47a182aeb1b0ffef43fabd11
