### ISSUE TITLE
Error with Maximum file multiparts in content reached

### ISSUE THREAD

**Issue by itowtips** [shirasagi/shirasagi#254]
デフォルトの設定では、HTTPマルチパートを使用する通信にて制限があるようです。
記事や施設情報の更新postがエラーになる場合が発生しました。

unicornのエラーログ
<pre>
E, [2015-03-05T18:50:02.076631 #32164] ERROR -- : app error: Too many open files - Maximum file multiparts in content reached (Rack::Multipart::MultipartPartLimitError)
</pre>

http://stackoverflow.com/questions/27773368/rails-4-2-internal-server-error-with-maximum-file-multiparts-in-content-reached

以下の記述を`initializer`に付けるなどすれば、エラーは回避できます。
`Rack::Utils.multipart_part_limit = 0`

`unicorn_rails` コマンドには該当のオプションが無い様子
`rack`のオプションはどこに記述すべきでしょうか。
https://github.com/rack/rack/blob/b0b5fb9467e6ed777d3eaf35afc81d758e308aab/lib/rack/utils.rb#L71-74

**Comment by sunny4381** [comment]
`config/initializers/multipart_part_limit.rb` を新規追加し、上記のオプションを追加してはどうでしょうか？

なお、`ENV['RACK_MULTIPART_PART_LIMIT']` の設定が優先されるので、unicorn:start タスクに設定することも出来ます。
https://github.com/shirasagi/shirasagi/blob/master/lib/tasks/unicorn.rake#L3-7

**Comment by itowtips** [comment]
`config/initializers/rack.rb`
はどうでしょうか。

**Comment by tany** [comment]
rack は大きすぎるので `config/initializers/multipart_part_limit.rb` でいいかと。

**Comment by itowtips** [comment]
@tany わかりました。
