### ISSUE TITLE
リンクチェック

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#257]
本文のリンクチェックで相対パスの場合、結果が失敗となります。

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/commit/73f5e1c950c6b0b466f56c11f3af223a2f978ed7
相対パスに対応しました。
アンカーリンクについては未対応です。

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/commit/7b7be142ae860abbdefc7c1ab4b58e2c64914d51
リンクをURL エンコード

https://github.com/itowtips/shirasagi/commit/add381845f52a7fc2972fe85a49a0f4ee8a5d3da
アンカーリンクに対応
