### ISSUE TITLE
SCSSのデバッグ

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#259]
Source Mapsを導入することは可能でしょうか

https://github.com/vhyza/sass-rails-source-maps

**Comment by tany** [comment]
https://github.com/vhyza/sass-rails-source-maps
https://github.com/markbates/coffee-rails-source-maps
これら入れてみましたが sass の方は動かないですね。
とりあえず sass は update しておきます。

**Comment by tany** [comment]
5.0.0.beta1 を使うと少し書き出せましたが、コンパイルでcompassが読み込めないエラー発生。

Gemfile
```
gem 'sass-rails-source-maps', git: 'https://github.com/vhyza/sass-rails-source-maps.git',
                              branch: "sass-rails-5.0.0.beta1"
```
$ rake assets:precompile
```
Sass::SyntaxError: File to import not found or unreadable: compass/css3.
Load paths:
  /mnt/hgfs/www/ss/app/assets/images
  /mnt/hgfs/www/ss/app/assets/javascripts
  /mnt/hgfs/www/ss/app/assets/stylesheets
  /mnt/hgfs/www/ss/vendor/assets/javascripts
  /mnt/hgfs/www/ss/vendor/assets/stylesheets
  /usr/local/rvm/gems/ruby-2.2.1/gems/jquery-cookie-rails-1.3.1.1/vendor/assets/javascripts
  /usr/local/rvm/gems/ruby-2.2.1/gems/jquery-turbolinks-2.1.0/vendor/assets/javascripts
  /usr/local/rvm/gems/ruby-2.2.1/gems/turbolinks-2.5.3/lib/assets/javascripts
  /usr/local/rvm/gems/ruby-2.2.1/gems/jquery-rails-4.0.3/vendor/assets/javascripts
  /usr/local/rvm/gems/ruby-2.2.1/gems/coffee-rails-4.1.0/lib/assets/javascripts
```

**Comment by itowtips** [comment]
sass-rails-source-maps　調査中
これを入れても変化が見られず、master、5.0.0.beta1は同様に上記と同じエラー

また、sass-rails-source-mapsを使用しなくても
development で管理画面のstyle.css等見てみると、以下のようなコメントが付き
<pre>/* line 16, /var/www/hagukumi/app/assets/stylesheets/ss/_pc.scss */</pre>

sass-rails-source-mapsのusageにある画像のように、
クローム、firefoxでscssを展開して見ることができるようです。

**Comment by itowtips** [comment]
Sprockets が3になったら assets precompile で source map をサポート。
https://github.com/rails/sprockets-rails
> `config.assets.debug`
> This feature will eventually be deprecated and replaced by Source Maps in Sprockets 3.x.

とりあえず、
https://github.com/vhyza/sass-rails-source-maps
が動かないのであれば今はいい方法がないのかもしれません。
