### ISSUE TITLE
アップローダー　.coffee アップロード時にエラー

### ISSUE THREAD

**Issue by tany** [shirasagi/shirasagi#268]
test.coffee
```
$ ->
  console.log "test"
```

エラーメッセージ。
> 問題が発生しました。
次の項目を確認してください。
Form coffee:undefined method `sub' for nil:NilClass

ファイルはアップロードできている。

**Comment by itowtips** [comment]
#356
`@saved_path = @path` を行ってから
`compile_scss`　を呼び出すよう修正
<pre>
def compile_scss
  path = @saved_path.sub(/(\.css)?\.scss$/, ".css")
  Fs.binwrite path, @css
end
</pre>

**Comment by itowtips** [comment]
上記の test.coffee をアップロードしコンパイルされた test.js の保存を確認しました。
