### ISSUE TITLE
施設情報のプレビュー

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#269]
施設情報のフォルダーに施設画像を登録し、施設情報をプレビューで閲覧するとサムネイルの画像のパスにプレビュー用のパスが入り、リンク切れとなります。

**Comment by itowtips** [comment]
#194 #225

**Comment by itowtips** [comment]
既存のコードを流用しつつ、filterに纏めてみました。
https://github.com/itowtips/shirasagi/commit/c845b6c1255e6409fca98a57232e1a96846d1d23

**Comment by itowtips** [comment]
引数はhash渡しのままですが、関数名を変更し調整を加えてみました。
上記のコミットでは.find_byが失敗するので修正しています。
https://github.com/itowtips/shirasagi/commit/fba73ba69a74943fa1921f123ff6101573fbf06d
