### ISSUE TITLE
CentOS7 インストールについて

### ISSUE THREAD

**Issue by mikkun0626** [shirasagi/shirasagi#2746]
初めまして、SHIRASAGIインストールについて質問させて頂きます。

インストールの過程で、サイトの制作とありますが、その際に入力する
$ rake ss:create_site data='{ name: "サイト名", host: "www", domains: "localhost:3000" }'

に関して、上記そのまま入力するのでしょうか？
サイト名＝運用サイト名
host = www
domains = ****.com などの運用ドメイン

と言う感じで書き換えての入力になるのでしょうか？

因みに上記の入力で行くと、 ***.com/.mypage を表示しようとするとサイトは表示されませんでした。
また、***.com のトップページは、Welcome to nginx!　の表示がされます。

◆動作環境
KAGOYA VPS KVM CentOS7 64bit
CPU 2コア メモリ 2GB ストレージ 30GBSSD

上記OSインストール後、そのままSHIRASAGIのインストールを行っております。

素人な質問で申し訳ありませんがお教えください。

**Comment by tany** [comment]
@mikkun0626
domains: は公開サイトとして利用する際のドメインを入力してください。
host: は内部的なものなのでwwwのままで問題ありません。
このコマンドで設定したものは管理画面から変更可能です。

ただ、//domain/.mypage （管理画面）にこの設定は関係ないため、
Nginx であれば proxy_pass http://127.0.0.1:3000; のように振り分ける必要があります。
http://shirasagi.github.io/installation/nginx.html

**Comment by mikkun0626** [comment]
tany さん

早速教えて頂きありがとうございます！
無事解決でき、ログインページが表示されるようになりました！

何度か初期化しながら何回もインストールを行い、ずーっと該当箇所に疑問を感じ、GitHubを見つけ質問させて頂きました。

本当にありがとうございましたm( . . )m
