### ISSUE TITLE
[CMS] 管理画面の外観を編集する機能がほしい

### ISSUE THREAD

**Issue by ghost** [shirasagi/shirasagi#2766]
サイト設定、システム設定などからベースカラー、ロゴ、アイコンなどを変更できるようにしたい。
さらに複雑な編集の場合はサイト設定、システム設定などで CSS を直接入力できるようにしたい。

**Comment by sunny4381** [comment]
v1.13.0 よりロゴを管理画面で変更可能。
ベースカラーやアイコンなどの変更に関しては、[OEM 開発](http://shirasagi.github.io/settings/oem.html)を参照してください。
