### ISSUE TITLE
[CMS] カテゴリーフォルダーの統合ができない

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#2778]
カテゴリーフォルダーを統合する際に以下のエラーが表示され統合できない。
どちらも必ず存在するファイルのはずなので統合できるべき。

index.html : 統合元フォルダーの下に同名の静的ファイルがあります。
rss.xml : 統合元フォルダーの下に同名の静的ファイルがあります。

**Comment by ShinjiTanimoto** [comment]
修正しました。
#3009
