### ISSUE TITLE
"Theme切り替え"の初期値

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#2884]
"Theme切り替え"機能にて、初期設定(default)を指定あるいは、並び順1つ目をdefaultとしてください。

現状、どのThemeも設定されていない状態が、初期状態となっているようです。
未選択が意図的なのか、不具合なのかがわかりませんが。
これを、ページ読み込み時にクッキーからThemeの選択値が未設定のとき、defaultのThemeを有効として欲しいのです。

また、公開ページのUIとして現在設定中Themeのボタンに、選択中としてのclassも追加いただけると、わかりやすい見た目をつけることもできるので、合わせて検討ください。

**Comment by sunny4381** [comment]
@HiraiY `.css("border", "double")` の部分ですが、`active` という css クラスを付与するようにしてください。

**Comment by sunny4381** [comment]
v1.13.0で修正しました。
