### ISSUE TITLE
 標準機能/ページリストのループHTMLヘルプ誤記?

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#2887]
Liquid 形式で使用例に、下記が含まれるが。
`<p>#{summary}</p>`
実際に書くと、記事のサマリーを取れず、そのまま#{summary}が出力される。
`<p>{{ page.summary}}</p>`
上記でサマリーが取得できましたので、誤記載のようです。

**Comment by sunny4381** [comment]
fixed: https://github.com/shirasagi/shirasagi/pull/3343/files

**Comment by sunny4381** [comment]
v1.13.0 で修正をリリースしました。
