### ISSUE TITLE
フォルダー詳細画面Liquid 形式を選択時の詳細に「子リスト表示」が表示される

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#2896]
フォルダー属性: 標準機能/フォルダーリスト
編集画面にて「リスト表示」Liquid 形式を選択すると、「子リスト表示」のブロックが消えますが、
詳細画面にて「子リスト表示」のブロックが表示されます。

この場合、詳細画面でも「子リスト表示」のブロックは非表示が適切ではないでしょうか。
形式選択間違えたのかと不安になります。

**Comment by sunny4381** [comment]
v1.13.0で修正しました。
