### ISSUE TITLE
記事削除　IE8

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#290]
IE8で記事の詳細画面で「削除する」をクリックし、遷移した画面で「キャンセル」を押すとキャンセルされずに記事が削除されます。

**Comment by itowtips** [comment]
「キャンセル」のbutton typeをresetとし押下時削除されないように修正

**Comment by sunny4381** [comment]
IE8 では、「キャンセル」のbutton type が submit の場合、onclick が無視され form の action が実行されてしまう。type を明示的に reset に変更することで、form の action ではなく onclick を実行するようになる。

**Comment by sunny4381** [comment]
IE8 のイメージは下から入手できる。
https://www.modern.ie/ja-jp/virtualization-tools

このサイトからは、Hyper-V, Virutal PC, VMWare, VirtualBox の各イメージがダウンロードでき、IE8 on Win7, IE8 on XP が選択可能。

**Comment by sunny4381** [comment]
上記のサイトから IE8 on Win7 の VirtualBox イメージをダウンロードし修正を確認した。
`type` を `reset` に変更するだけで、IE8 でも削除のキャンセルができるようになった。
