### ISSUE TITLE
プレビュー時Theme切り替えにて追加されるcssのリンクが公開時と順序が異なる

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#2920]
プレビュー時と公開時でcssのカスケードの順が合わないので、困っています。

Theme切り替えにて追加されるcssのリンクが、公開時と順番が異なり、
レイアウトで設定済みのcssリンクの前に、Theme切り替えのcssリンクがある。

公開時
1. 基本css
2.Teema切り替えcss
プレビュー時は下記の順になる
1.Teema切り替えcss
2. 基本css

公開と同様に、レイアウトで設定済みのcssリンクの後にTheme切り替えのcssリンクの順が維持されないと、プレビューのTeema切り替え機能による表示が公開時と異なってしまう。

**Comment by sunny4381** [comment]
@y-teraz デモサイトのトップページ (https://demo.ss-proj.org/) にて確認しましたが、現在は再現しないようです。

通常時は次の順で CSS が組み込まれています。

1. システム CSS: /assets/cms/public.css
2. サイト CSS: /css/style.css
3. Theme CSS: /css/black.css

これがプレビュー時は次の順でした。

1. プレビューに必要な CSS: /assets-dev/cms/preview/main.css
2. システム CSS: /assets/cms/public.css
3. サイト CSS: /.s1/preview/css/style.css
4. プレビューに必要な CSS: /assets/css/colorbox/colorbox.css
5. プレビューに必要な CSS: /assets/cms/preview/jquery-ui.css
6. Theme CSS: /.s1/preview/css/black.css

合間にプレビューに必要な CSS が挿入されていますが、順番が前後するといったことはなく、ご指摘いただいた現象は、現在は再現しないようなので、本課題を閉じさせていただきます。
