### ISSUE TITLE
携帯表示タグ変換の不具合

### ISSUE THREAD

**Issue by itowtips** [shirasagi/shirasagi#293]
次のようなタグが消されてしまう。
`<p>09:00～17:00</p>`
https://github.com/shirasagi/shirasagi/blob/master/lib/mobile/convertor.rb#L118

**Comment by sunny4381** [comment]
念のための確認ですが、<img> タグの場合、jpeg と png で置換の仕方が異なります。

形式 | 置換前                                | 置換後
-----|---------------------------------------|-----------
jpeg | `<img src="sample.jpg" alt="sample">` | `sample.jpg <a href="sample.jpg" class="tag-img" title="sample.jpg">[画像]</a>`
png  | `<img src="sample.png" alt="sample">` | 左に同じ

こういう仕様で良かったですか？

**Comment by itowtips** [comment]
その仕様で合っていたと思います。
