### ISSUE TITLE
管理画面の一覧系画面(index.html.erb)のチェックボックスを囲うth，tdのclass修正

### ISSUE THREAD

**Issue by kaosf** [shirasagi/shirasagi#295]
本来 `class="checkbox"` であるべきところがそうなっていない箇所が多い．

これが影響して，チェックボックスの幅が足りずに `text-overflow: ellipsis` の点が一個見えてしまう問題がある．

![ss](https://cloud.githubusercontent.com/assets/1495128/6703484/b068aaea-cd7f-11e4-9b17-f16a9e179d67.png)

例えば `views/ezine/members/index.html.erb`．

現状

```html
<th style="width: 20px;"><input type="checkbox" /></th>
```

```html
<td>
  <input type="checkbox" name="ids[]" value="<%= item.id %>" />
</td>
```

あるべき形

```html
<th class="checkbox"><input type="checkbox" /></th>
```

```html
<td class="checkbox">
  <input type="checkbox" name="ids[]" value="<%= item.id %>" />
</td>
```

**Comment by sunny4381** [comment]
merged #375
