### ISSUE TITLE
定型フォームの[表]のHTML不備

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#2964]
最初の行が見出しのとき、
セルは`<th scope="col">`にはなっているが、その行=`<tr>`は、`<thead>`で括られていない。

また、`<tbody>`のあとに`<td>`の無い`<tr>`空行がある。

下記はHTMLの出力例
`<table><caption>一覧表</caption><tbody><tr></tr><tr><th scope="col">区分</th><th scope="col">A</th><th scope="col">B</th><th scope="col">C</th></tr><tr><th scope="row">1</th><td>A1</td><td>B1</td><td>C1</td></tr><tr><th scope="row">2</th><td>A2</td><td>B2</td><td>C2</td></tr><tr><th scope="row">3</th><td>A3</td><td>B3</td><td>C3</td></tr></tbody></table>`

### 備考
エディタで表を生成時とHTMLに差異があります。
エディタの場合は最初の行を見出しとした場合、`<thead>`で括られます。

**Comment by sunny4381** [comment]
@52753e6af76437bc95fdd925932b0404b1e30bc3 にて修正済み。
