### ISSUE TITLE
緊急災害レイアウトにて、携帯無効なのにプレビューに携帯がある

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#2966]
前提
 サイト設定-モバイル設定にて、状態:無効 を設定中

緊急災害レイアウトにて、プレビューのカラムに 
**PC | 携帯** と、プレビュー用リンクが表示される。

モバイル設定無効にしているので、**携帯** は不要ではないか

**Comment by sunny4381** [comment]
@6348465 で修正済み。
