### ISSUE TITLE
定形フォームを使用している記事の編集中プレビューがエラーになる

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#2968]
定形フォームを選択している記事を[編集する]
定形フォーム入力欄末の[プレビュー]で50エラーとなる。

オンライン・デモにて確認可能
「インタビュー」の編集中( https://demo.ss-proj.org/.s1/article146/pages/33/edit )
定形フォーム [インタビュー]
[インタビュー]のブロックの[プレビュー]ボタンでプレビュー用別ウィンドウを開くが、500エラー

他の定形フォームによる記事でも同現象を確認できる。
本文が通常のエディタの場合は、編集中からのプレビューに問題ない。

**Comment by ShinjiTanimoto** [comment]
修正しました。
#3014
