### ISSUE TITLE
CMSのCKEditorカスタマイズについて

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#2969]
https://www.ss-proj.org/faq/docs/552.html
上記FAQにあるように、config.jsを差し替えても一部無効である。

defaultの設定でツールボタンにHTML5廃止タグが含まれている。
使用された場合、サイトをHTML5で作成している場合に、Validationエラーとなる。
アクセシビリティ試験にValidationの結果も含まれるため、アクセシビリティを保証できなくなるため、問題。

### config.jsの指定が一部無効
config.removeButtonsを設定しても、CMSのページ編集時のCKEditorには効いていない。
`config.removeButtons ='Italic,Strike,Style';`

### スタイルボタンstyles.jsにHTML5廃止タグ
スタイルの下記はHTML5廃止タグが含まれている
Big `<big>`
Typewriter  `<tt>`

### 要望
エディタの色指定の無効化はサイト毎に指定できるが、
サイトによってタグの利用可不可は異なるものとしたい為、他のボタンの指定もある程度設定できると良い。
あるいは、config.jsで指定したconfig.removeButtonsの指定とCMSによるremoveButtons設定値をマージしてエディタ起動とする。

日本語での利用予定の場合、必要とは思えないスタイル。

- スタイルボタン自体を無効にするか
- 日本語環境として適切な内容に差し替えて提供するか
- config.js差し替えをサイトごとに設定できる

上記のいずれかが可能であるとと良い。

**Comment by y-teraz** [comment]
「スタイル」ボタン無効化するか、項目を設定できるUIをCMSにて提供を検討願います。
初期設定で入っている内容が、HTML5廃止タグが含まれている件を先に説明しましたが、

"Special Container"が非常に扱いに困ります。
これを使うと、スタイルがdivに埋め込まれ、classも無いので扱いにくい。
`<div style="background:#eee;border:1px solid #ccc;padding:5px 10px;">テスト&nbsp;Special Container</div>
`
公開時の配色変更をcssの切り替え指定で行う場合、
cssに"Special Container"用の上書き調整の定義を追加する必要が発生しますが、classが無いのでセレクター指定しづらい。(style属性値で特定するしか無い)

結局、廃止タグや"Special Container"を利用されることを防ぐには、styles.jsを差し替える必要があるにもかかわらず。
シラサギには、このためのUIが無い。
シラサギのコア内、エディタの該当ソースを入れる変えることで差し替えられることはわかっているが、

複数サイト運用時、スタイルの内容をサイト別に変えたくても、変えることができない
というところが、たいへん悩ましい為、重ねて検討願います。

**Comment by sunny4381** [comment]
そもそも CKEditor4 は HTML5 に未対応である（a タグ内に div タグを入られれない）が、
次の順で改修を検討する。

1. CKEditor4 の設定ファイルを改変し、HTML5 廃止タグが挿入できないようにする。
2. CKEditor5 へのアップグレードを検討する。
3. 他の WYSIWYG エディタの利用を検討する。
4. 独自の WYSIWYG エディタの開発を検討する。

1 の対応は限定的で a タグ内に div タグを入れられないという制限は残る。
2 〜 3 は、完全 HTML5 対応。

**Comment by sunny4381** [comment]
v1.13.0 から CKEditor の設定を変更し HTML5 で無効となったタグを削除しました。
また、FAQ を改善しました。
