### ISSUE TITLE
ユーザファイルにuploadした画像がNot Foundと表示される

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#2970]
シラサギ ver. 1.11.1　にて確認。

### 手順
※ Vagrant 自治体サンプルサイトにても同現象確認できた為、この場合の手順

1. 記事ページ編集画面　定型フォーム「ブロック入力」を選択
2. [自由入力]ブロック追加
3. 追加した[自由入力]ブロックの[ユーザファイル]→画像ファイルを選択して[保存]
4. [自由入力]ブロックの下、本来画像サムネイルと操作ボタンが表示されるところにNot Foundと表示される。
 
![ss-edit-Not Found2019-06-24](https://user-images.githubusercontent.com/50577719/59984934-159f3a80-9669-11e9-870e-26eeec6be4c8.png)

なお、[ユーザファイル]を再び開くと追加した画像はパネル内に表示される。
[共有ファイル]へ画像を保存すると、画像サムネイルもNot Foundも表示されない。
[アップロード]ボタンから、画像保存した場合は、ブロック下部に画像サムネイルと操作ボタンが表示される。

### 備考
定型フォーム「既定のフォーム」のとき、同様の現象は発生していない。
定型フォーム「ブロック入力」でも、「イメージ」「添付ファイル」の場合に同様の現象は発生していない。

**Comment by itowtips** [comment]
修正しました。
#3085
