### ISSUE TITLE
サブディレクトリのサイトで[関連記事を選択する]ボタンでリンク不正

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#2981]
本文のエディタの下にある[関連記事を選択する]ボタンで別のページのリンクを作ると、リンクのパスにサブディレクトリが含まれておらず、不正なリンク=404エラーになる。

### 不具合の詳細
サイトのサブディレクトリ=/sub/
サイト内のページ　about/info.html (公開URL /sub/about/info.html)

リンク先の指定としては、`<a href="/sub/about/info.html">` となってほしいが、
実際には`<a href="/about/info.html">`となった。

### 補足
関連記事の機能で記事を選択追加した場合には、サイトのサブディレクトリは反映されている。

**Comment by sunny4381** [comment]
@486621d79ae4bd3aa52ebac40bb11872171e68f2 で修正済み。
