### ISSUE TITLE
連絡先選択のモーダルウィンドウ

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#305]
記事作成画面の連絡先を選択するモーダルウィンドウですが複数のグループが存在する場合にページネーションがでません。

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/commit/47fe014a08eb672a648cc9b0aaafef3d49f3b120
* ページネーションを付与
* グループ選択時に tel , fax, email の入力内容を上書きするように修正
