### ISSUE TITLE
IEで日本語ファイル名をもつ添付ファイルのダウンロードで文字化け

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#306]
#216

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/commit/3c49ea029874ba3c6a9d4e9d57f29ce5514bf86a
* send_data を file_filterでラップしました

**Comment by tany** [comment]
@itowtips Railsオーバーライドするなら変数名同じにしたほうがいいかと。
あとsuperの引数いりますっけ？

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/commit/55e34a4f5c321d329b111ec7b248b9569187e373

* Railsのsend_dataは  `send_data(data, options = {}) `  だと思われるので、これに合わせて引数を調整しました。
https://github.com/rails/rails/blob/2d743b528cf8ee2a8dc016a5dd0d54bf7cbc34e4/actionpack/lib/action_controller/metal/instrumentation.rb#L56

* superの引数を省略しました

**Comment by itowtips** [comment]
#369
* Gemを入れてみました。

**Comment by sunny4381** [comment]
https://github.com/yukihr/ungarbled/blob/master/lib/ungarbled/railtie.rb
規定値として `config.ungarbled.default_lang = :ja` が設定され、
`ActionController` が `Ungarbled::ActionControllerExt` で拡張されるようです。

`Ungarbled::ActionControllerExt` では、`alias_method_chain` で（Rails 内部の？）`send_file_headers!` メソッドを書き換えています。

そのせいで、追加で設定をしなくても、IE で正しくファイルをダウンロードできるのかも？

内部メソッドを書き換えているので、将来、動作しなくなるかも？

**Comment by itowtips** [comment]
railsアップデートの時に注意することにします。

**Comment by sunny4381** [comment]
@itowtips 時間があればテストを書いてみてください。
テストがあれば、目視でチェックしなくても良くなるので、少し安心できると思います。
