### ISSUE TITLE
文書の並び順のツールチップの説明

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#310]
文書の並び順のツールチップの説明が間違っている。

✕「数字が大きいほど一覧ページの上位にリンクが表示されます。」
○「数字が小さいほど一覧ページの上位にリンクが表示されます。」

メールフォームの並び順も同様に対応。

**Comment by itowtips** [comment]
https://github.com/shirasagi/shirasagi/pull/312
説明を調整しました。
