### ISSUE TITLE
IDの重複するユーザーを登録したい

### ISSUE THREAD

**Issue by ghost** [shirasagi/shirasagi#3104]
同じIDのユーザーが登録できない。
登録できないのはいいが、マルチテナントで運用している場合に、他のサイトのユーザーと重複していると、サイトの管理者ではなぜ登録できないの判断できない。

できればサイトが違えば、IDが重複しても登録できるといいが、ユーザー作成の画面でIDやメールアドレスを入力する項目に登録可能かどうかをチェックする仕組みがあると助かる。
CSVでの取り込みの際もなぜ登録できないかを明示してほしい。

**Comment by itowtips** [comment]
こういった場合に職員番号の利用が考えられる。
現状、職員番号のみではユーザーが登録できないので、登録できるようにできないか。

**Comment by sunny4381** [comment]
v1.13.0 から職員番号のみでユーザー登録できるようになりました。
 職員番号は、所属組織が異なれば重複しても登録できるようになりました（同一組織での職員番号の重複は不可）。

なお、ログインに際しては所属組織専用のログインを利用する必要があります。
例: /.g1/login や /.s1/login など。

**Comment by sunny4381** [comment]
v1.13.0 で修正しました。
