### ISSUE TITLE
ページ複製機能で複製した記事のファイル名

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#317]
複製すると、新ファイル名が "copy...html" となってしまう。

通常、ユーザは何もチェックせずにそのまま公開してしまい、URL に "copy" がついてしまう。
マズい。

記事の新規作成と同様、連番が望ましい。

**Comment by itowtips** [comment]
優先で対応します。

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/commit/4ac28c1b19e98c01821a7626207bc1e9dea33126
* 承認申請時にcopy-のファイル名の場合は、ファイル名変更のメッセージが表示されて承認が進められなくなる。
* 編集前のファイルがcopy-のファイル名の場合は、ファイル名を空で保存したとき
に連番のファイル名になる。
* 複製したファイル名のままで保存しようとすると警告がでる。「ファイル名が複製後の状態となっています。」

**Comment by tany** [comment]
複製は新規作成と同じようなものなのでファイル名は通常通りの連番でよいと思います。

**Comment by itowtips** [comment]
複製した記事がわからなくなるので、この仕様としていましたが、
連番にするロジックは作成します。

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/commit/40478aa0e4f315c1dfa61c126197696e40a493c9
* 複製時にファイル名を連番とする。

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/commit/fac67b6c775f6f5d0ecee5b94d1a984f8fdc4b1c
* コピー時のフォームに【複製】をタイトルに付ける
* そのまま保存しタイトルに【複製】が付いたまま保存すると警告を表示

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/commit/726146eaeb94e3096b89532fce45f989a6dfdf3d

*  【複製】 を [複製] に変更
*  [複製] がタイトルにある状態では承認申請できない。
*  公開保存時に警告を表示

**Comment by tany** [comment]
@itowtips　細かいですが ] の後に半角スペースが欲しいです。

**Comment by itowtips** [comment]
https://github.com/shirasagi/shirasagi/commit/8d8fa374420685c74b133e322f03060ac99de71d
* 複製時、] の後に半角スペースを追加
