### ISSUE TITLE
history_backups/history_logs の肥大化対応

### ISSUE THREAD

**Issue by snkmr** [shirasagi/shirasagi#3177]
・history_backups と history_logs コレクションについて、期間を指定して削除する仕組みを設けたい
   - ファイル復元機能のファイルが削除されずに残る
   - ss:daily のような1日に1回実行するタスクを作成し、一定の期間を削除する
   - 月に1回だと一度に大量のログを削除することになるので、1日1回の方が良さそう
   - history 系のログ削除のタスクを追加する

**Comment by sunny4381** [comment]
v1.13.0 で定期的に削除するようにしました。
