### ISSUE TITLE
グループ機能の検討

### ISSUE THREAD

**Issue by tany** [shirasagi/shirasagi#323]
機能
- ポータル画面
- メッセージ共有（掲示板 or ツイート or チケット or Etc.）
- ファイル共有
- スケジューラー（日程管理）
- 設備予約

**Comment by tany** [comment]
URL
- /.g123
- /.g123/bbs
- /.g123/files
- /.g123/schedule
- /.g123/facilities

**Comment by tany** [comment]
## 設計
グループ単位
- ルートグループ # どの階層でも対応できたらおもしろい

Routing ex.
```
gws "schedule" do
  resources :actions # /.g123/schedule/actions/:id
end
```

## 実装
Riot.js!?

## ポータル画面
- /.g123 # /..g123
- メニュー
- 自分のスケジュール
- 掲示板の新着
- etc.

## ファイル共有/ss_files
- グループ間でファイルを管理する

## スケジュール/Schedule
- 個人
  - 日, 週, 月 
- グループ間
  - 日, 週
- 拡張
  - 繰り返し
  - 編集権限
  - 公開範囲
  - etc.

## 設備予約/Reservation
- 設備
  - 日, 週, 月
- 拡張
  - 繰り返し
  - 終日
  - 設備グループ

## 掲示板/Board
  - スレxレス
  - 削除
  - 新着レスが上位に

**Comment by sunny4381** [comment]
管理画面を開発していて、既定で定義されている CSS で何ができるのか分からないので、独自に定義していいものかどうかちょくちょく迷います。

グループウェア開発を契機に、CSS を CSS ライブラリとして、形式化 / 体系化できればいいんですが :grin:

**Comment by tany** [comment]
@sunny4381 CSSは近々書き直す予定です。

**Comment by kaosf** [comment]
`gws`ブランチで作業を進める．

**Comment by kaosf** [comment]
各モデルは一応 `SS::Document` をincludeする．

**Comment by tany** [comment]
GWS 手動マージ中です。
https://github.com/shirasagi/shirasagi/tree/gws-merge

対応済み
- 新デザイン適用
- 構成変更（サブモジュール化）
- カレンダー色

未対応
- DB定義修正/org_idが必要なコレクション
- 権限調整
- 日本語化
- spec

不明点
- plan: ajax_params

**Comment by tany** [comment]
GWS機能 #674
