### ISSUE TITLE
[CMS] ユーザーの削除

### ISSUE THREAD

**Issue by ghost** [shirasagi/shirasagi#3271]
ユーザー一覧画面で「削除する」ボタンの左にある全チェックをONにしてから、「削除する」を押すと全ユーザーが消える。
操作できなくなるので管理権限を持つユーザーは残したい。

**Comment by sunny4381** [comment]
v1.13.0 からユーザーごとに「削除状態」として「削除不可」を設定できるようになりました。重要なユーザー（管理権限を持つユーザー）の削除状態を「削除不可」に設定することで、操作できなくなる問題を防止することができます。

**Comment by sunny4381** [comment]
v1.13.0 で修正をリリースしました。
