### ISSUE TITLE
不要な警告ログの非表示

### ISSUE THREAD

**Issue by tany** [shirasagi/shirasagi#335]
Overwriting existing field の警告が出るfieldを修正しました。
https://github.com/shirasagi/shirasagi/commit/d602eef385e4021d2185669919f8e9780639f359

**Comment by tany** [comment]
Creating scope Overwriting existing は logger を消さないとダメっぽいです。

vi /usr/local/rvm/gems/ruby-2.2.1/gems/mongoid-4.0.2/lib/mongoid/scopable.rb
```
      def check_scope_name(name)
        if _declared_scopes[name] || respond_to?(name, true)
          if Mongoid.scope_overwrite_exception
            raise Errors::ScopeOverwrite.new(self.name, name)
          else
            if Mongoid.logger
              Mongoid.logger.warn(
                "Creating scope :#{name}. " +
                "Overwriting existing method #{self.name}.#{name}."
              )
            end
          end
        end
      end
```

**Comment by sunny4381** [comment]
override する/したい scope は、scope として実装するのではなく criteria を返すメソッドとして実装した方がいいんですかね？

例: search メソッド
* https://github.com/shirasagi/shirasagi/blob/master/app/models/concerns/cms/content.rb#L55-66
* https://github.com/shirasagi/shirasagi/blob/master/app/controllers/ads/banners_controller.rb#25

**Comment by sunny4381** [comment]
現状、`public` という scope でしか警告が出ていないので、次のような修正でもいけそうです。

```
if !_declared_scopes[name] && !respond_to?(name, true)
    scope :public, ->(date = nil) {
      if date.nil?
        where state: "public"
      else
        date = date.dup
        where("$and" => [
          { "$or" => [ { state: "public", :released.lte => date }, { :release_date.lte => date } ] },
          { "$or" => [ { close_date: nil }, { :close_date.gt => date } ] },
        ])
      end
    }
end
```

**Comment by tany** [comment]
scopeは返り値がnilの時にcriteriaを返すだけの違いですかね。
メソッド実装でよさそうです。
http://kotatu.org/blog/2014/10/11/why-should-use-scopes-over-class-methods/

**Comment by tany** [comment]
メソッドに変更しました。
https://github.com/shirasagi/shirasagi/commit/dc1491f20d8fdc4b2f89d26498517398e9663c89
