### ISSUE TITLE
メールフォームのパーツ「フィードバック」のパーツ詳細画面でHTMLの編集ができる

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#3362]
パーツ属性 メールフォーム/フィードバック
パーツの詳細画面なのに、上部HTMLと下部HTMLが編集不可でなく、編集可能です。
保存できるわけではないですが、
編集可能だったので、編集画面と間違え[保存]がなくて混乱します。

デモでも確認できます。 https://demo.ss-proj.org/.s1/cms/parts/48

**Comment by sunny4381** [comment]
v1.13.0 で修正をリリースしました。
