### ISSUE TITLE
[CMS]管理画面[サイト内検索]-[ファイル一覧]記事名が重なる

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#3368]
デモサイトにても確認できました。
確認ブラウザは、Chrome,FireFox

記事名が長いものに添付ファイルが有ると重なって、次の項目の記事名が読めません。

![スクリーンショット 2020-01-09 12 25 24](https://user-images.githubusercontent.com/50577719/72035632-ca363c00-32db-11ea-8505-c6b95360be38.png)

**Comment by sunny4381** [comment]
v1.13.0 で修正をリリースしました。
