### ISSUE TITLE
お問い合わせフォーム(メールフォーム) 画像認証が機能していない

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#3373]
発見環境 ver. 1.12.1 
デモ環境 ver. 1.12.3にても同様のようです。

メールフォーム「認証」設定 https://demo.ss-proj.org/.s1/cms161/conf
画像認証[使用する] 選択されているが、

メールフォーム https://demo.ss-proj.org/inquiry/
画像認証が生成されていない。

環境上、「画像認証」が提供不可であれば、フォームの設定として選択提供されないのが望ましいです。
あるいは、サイト設定かシステム設定、追加インストールなど必要であれば、ヘルプ等に記載願います。

**Comment by sunny4381** [comment]
デモサイトでは、お問い合わせの確認画面で画像認証が表示されていますのでご確認ください。

なお、改善計画として、画像認証自体、最近の AI なら簡単に突破してしまうので、
reCAPTCHA のようなチェックを入れるだけのチューリングテストを導入することを検討しつつ、管理画面でプラットフォームがサポートしているかどうかをテストする機能を追加するなどを検討したいと思います。

**Comment by y-teraz** [comment]
回答ありがとうございます。

「確認画面」にて、画像認証があることを確認いたしました。
勘違いをしており、申し訳有りません。

認証の改善について、期待しております。よろしくお願いいたします。
