### ISSUE TITLE
カレンダー月別表示で表示形式切り替えが使えない場合がある

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#3378]
前の月への切り替えが無効になる、表示の最終月(一年前?)にて、[リスト形式][表形式]の切り替えがリンクになっていない。
該当ページは404ではないのに、リンクされていないのは奇妙です。

デモサイトの現時点での同現象確認可能ページは下記です。
https://demo.ss-proj.org/calendar/201901/table.html
https://demo.ss-proj.org/calendar/201901/list.html

**Comment by sunny4381** [comment]
現在では前月を示す以下の URL にアクセスすると 404 になります。

- https://demo.ss-proj.org/calendar/201812/table.html
- https://demo.ss-proj.org/calendar/201812/list.html

**Comment by y-teraz** [comment]
分かりづらい表現をしてしまい申し訳ありません。
>現在では前月を示す以下の URL にアクセスすると 404 になります。
指摘事項は、[前月]へのリンクではありません。ので、再検討願います。

その下の、[リスト形式][表形式]の切り替えのリンクのことです。
![スクリーンショット 2020-01-17 17 58 26](https://user-images.githubusercontent.com/50577719/72598378-0eb47e00-3953-11ea-9036-3c6f82069c59.png)

**Comment by sunny4381** [comment]
v1.13.0 で修正をリリースしました。
