### ISSUE TITLE
お問い合わせフォームをキーボード操作で送信できない

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#3384]
お問い合わせフォーム(メールフォーム機能)にて、
キーボード操作で[確認画面へ]送信ボタン(input[type="submit"])フォーカス時Enterで送信動作ができない。
デモサイトの該当 https://demo.ss-proj.org/inquiry/

### キーイベント
public.jsによりEnter(キーコード値13)を捨てているようです。

input全部でなく対象指定で、送信ボタン[type="submit"]を対象外とするか、
別途、送信ボタンからclickを発火させるかしてください。

該当の元ソース、下記のようです。
https://github.com/shirasagi/shirasagi/blob/master/app/assets/javascripts/inquiry/lib/form.js
```
Inquiry_Form.prototype.render = function() {
  $('.inquiry-form input').on('keypress', function (ev) {
    if ((ev.which && ev.which === 13) || (ev.keyCode && ev.keyCode === 13)) {
      return false;
    } else {
      return true;
    }
  });
```
上記のセレクター`.inquiry-form input:not([type="submit"])`とすることを検討願います。

### 回避策
フォーム使用のレイアウトまたは、読み込ませているjsファイルにて、
下記jsコード追加して、clickを発火させることで回避しました。
```
$(document).ready(function() {
//メールフォーム キーボード操作
	$('.inquiry-form input[type="submit"]').on('keydown', function (ev) {
		if(ev.keyCode==13){
			$(this).trigger('click');
		}
	});
});
```

### (参考)WCAG 2.0  解説書
キーボード: 達成基準 2.1.1 を理解する
https://waic.jp/docs/UNDERSTANDING-WCAG20/keyboard-operation-keyboard-operable.html

**Comment by sunny4381** [comment]
v1.13.0 で修正をリリースしました。
