### ISSUE TITLE
イベントカレンダー月別ページの形式切替後ページタイトル重複

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#3386]
表形式とリスト形式で、URLが異なりますが、ページのタイトル(titleタグ)が同一です。

表形式 https://demo.ss-proj.org/calendar/202001/table.html
リスト形式 https://demo.ss-proj.org/calendar/202001/list.html
いずれか、あるいは両方に形式名もtitleタグに含めていただければと考えます。

以前に、月別/日別のページタイトル重複解決していますが、同様の問題です。
[カレンダーに関する要望 #1476](https://github.com/shirasagi/shirasagi/issues/1476)
> 月別/日別の一覧ページのタイトル(同一タイトルの解消)

### (参考)WCAG 2.0 解説書
ページタイトル: 達成基準 2.4.2 を理解する
https://waic.jp/docs/UNDERSTANDING-WCAG20/navigation-mechanisms-title.html

**Comment by sunny4381** [comment]
v1.13.0 で修正をリリースしました。
