### ISSUE TITLE
意図せずパーツが格納フォルダから移動してしまう

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#3401]
あるフォルダ内にパーツ設置している場合に、以下の手順で、最上位へ移動してしまいました。

### 手順
パーツ画面に切り替えて、「このフォルダ以下から」検索で、フォルダ以下のパーツも検出。
検出したフォルダ以下のパーツを編集し保存すると、
元のフォルダ内から出て最上位へ移動してしまう。
※このとき、パーツ編集時の管理画面内でのパンくずが、「パーツ」となっており格納フォルダに置き換わらなかった。

event/test.part.html が在ったとき、test.part.htmlに移動してしまう。
レイアウトの指定パスも合わなくなりパーツが使用できなくなる。

### 移動手段
勝手に移動することも問題ですが、
パーツを元の位置に戻す移動手段は無いでしょうか。
戻し方がわからず、再作成しました。

**Comment by sunny4381** [comment]
v1.13.0で修正しました。
