### ISSUE TITLE
特定の文字が含まれていると「ふりがな」で閉じタグが壊れる

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#3404]
本文に&times;(乗算記号)が含まれていると、「ふりがな」でタグの閉じタグが壊れたページを生成します。

### 手順
本文にて&times;を入れる。
![スクリーンショット 2020-01-23 9 12 14](https://user-images.githubusercontent.com/50577719/72946092-38412f80-3dc1-11ea-8ced-3f136fad1cc0.png)

下書き保存/公開保存→プレビュー→[ふりがなをつける]
![スクリーンショット 2020-01-23 9 12 52](https://user-images.githubusercontent.com/50577719/72946134-5dce3900-3dc1-11ea-9135-f73fbc4893a7.png)

```
<div class="u-menu">
  <nav>
   <a class="smart" href="/.s1/preview/mobile.html">スマホ・<ruby>携帯<rp>(</rp><rt>けいたい</rt><rp>)</rp></ruby>イト</a>
   <a class="inquiry" href="/.s1/preview/inquiry/">お<ruby>問い合わせ<rp>(</rp><rt>といあわせ</rt><rp>)</rp></ruby>/a>
   <a class="sitemap" href="/.s1/preview/sitemap/">サイトマップ</a>
   </nav>
   </div>
```

ソース確認すると「問い合わせ」のA閉じタグが不完全になっている。
同様に閉じタグが不完全な箇所が複数発生していた。

### 備考
乗算記号を &#215;と記載してみても変わらなかった。
また、エディタにより乗算記号は&times;に置き換えられる。

なお、他の記号類についてはとくに検証していません。

**Comment by sunny4381** [comment]
v1.13.0で修正しました。
