### ISSUE TITLE
ページャのリンクにて、同一ページへの異なるリンクテキスト

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#3434]
Validationツールにより、
ページャーのリンクで、現在ページが最初のページ場合、「2」と「次のページ」が同一ページへの異なるリンクテキストとして警告となる場合があります。

確認時使用ツール Total Validator

リンクの目的 (コンテキスト内):達成基準 2.4.4 を理解する
https://waic.jp/docs/UNDERSTANDING-WCAG20/navigation-mechanisms-refs.html

**Comment by sunny4381** [comment]
当該リンクの両方ともに `rel="next"`（意味は「連続した文書における次の文書」）が設定されており、リンクテキストは異なるがその実体は同じものであることが示されています。
本件、シラサギでの対応が必要とは思えず、Total Validator のバグ（過剰検出）ではないでしょうか？

**Comment by y-teraz** [comment]
なるほど、確かに過剰検出ですね。
回答ありがとうごさいます。
