### ISSUE TITLE
nav要素の'aria-label'属性が無いものがある

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#3436]
記事リストのページャのnav要素には、aria-labelがありますが、その他のnav要素にaria-labelが設定されいない。
`<nav class="pagination" aria-label="pager">`

イベントカレンダー周りにて、以下の aria-labelの無いnav要素を確認しています。

- カテゴリフィルターnav.event-pages-filter
- カレンダーのナビゲーション nav.event-date
- パーツ属性   イベント/カレンダーにて作成したミニカレンダーのnav.calendar-nav

### H97: nav 要素を使用して、関連したリンクをグループ化する
https://waic.jp/docs/WCAG-TECHS/H97
※事例 2: 多くの nav 要素

**Comment by itowtips** [comment]
merged at 43c584c53db464789a203044a
