### ISSUE TITLE
記事リストなどの複数ページに渡る場合のページタイトル重複

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#3437]
記事リスト、カテゴリ、ページリスト、フォルダリスト、グループ別ページリストなどの
表示件数指定により、複数ページに改ページしている場合、
改頁してもページタイトル(titleタグ)の内容が同一です。

同じページタイトルなので、スクリーンリーダーを使用していると、どこを見ているかわからなくなります。
見えていても、ページャーが一番下なので、表示件数が多い場合は、分かりにくいかもしれません。

「●●件中の●件」、あるいは「●ページ目」など、テキストを追加することを検討願います。

### 例)デモサイト 記事
https://demo.ss-proj.org/docs/ 
https://demo.ss-proj.org/docs/index.p2.html
いずれも
`<title>記事 - 自治体サンプル</title>`

### ページタイトル:達成基準 2.4.2 を理解する
https://waic.jp/docs/UNDERSTANDING-WCAG20/navigation-mechanisms-title.html

**Comment by itowtips** [comment]
merged at fd6d645bb4e4912b772791
