### ISSUE TITLE
お問い合わせフォームのメールアドレス確認用入力欄labelが無い

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#3438]
メールアドレスの確認用入力欄にlabelがありません。
チェックツールにより、警告もしくはエラーとなる場合があります。

- miCheckerでは「問題の可能性大」
- Total Validatorでは、エラー検出されます。

https://demo.ss-proj.org/inquiry/
デモサイトのフォームの場合は、input#item_3_confirmが相当 

### 参考
ラベル又は説明:達成基準 3.3.2 を理解する
https://waic.jp/docs/UNDERSTANDING-WCAG20/minimize-error-cues.html

ARIA17: 関連するフォームコントロールを特定するために、グルーピングロールを使用する
https://waic.jp/docs/WCAG-TECHS/ARIA17

**Comment by itowtips** [comment]
merged at 43c584c
