### ISSUE TITLE
SS::Migration

### ISSUE THREAD

**Issue by kaosf** [shirasagi/shirasagi#344]
* kaosf/shirasagi migration ブランチで実装中 https://github.com/kaosf/shirasagi/tree/migration
* `SS::Migration.filepaths`, `SS::Migration.filenames`, `SS::Migration.filetimestamps` をテストとドキュメントを充実させながら作ってみた
* migration の実装方法を検討した
  * `SS::MigrationYYYYMMDDHHMMSS` というクラスの change メソッドを使うようにする
  * 大まかな形を以下にメモしておく

```
# app/models/ss/migration.rb
class SS::Migration
  class << self
    def migrate
      filepaths.each do |filepath|
        require filepath
        "SS::Migration#{filepath}".constantize.new.change
      end
    end
  end
end

# lib/migration/mod1/20150401000000_a.rb
class SS::Migration20150401000000
  def change
    # do something
  end
end

# lib/migration/mod1/20150401000001_a.rb
class SS::Migration20150401000001
  def change
    # do something
  end
end
```

**Comment by sunny4381** [comment]
参考
https://github.com/adacosta/mongoid_rails_migrations

**Comment by sunny4381** [comment]
参考その2
http://stackoverflow.com/questions/8570705/managing-mongoid-migrations

※スマホからだと上の投稿を編集できないので、使いづらいですね。

**Comment by kaosf** [comment]
Mongoid用のmigrationではなくてShirasagi全体のmigrationが出来る仕組みを提供するという発想で作ってたのでその辺を使おうとしてませんでしたね．

車輪を盛大に再発明していることはさておいて，任意のRubyスクリプトを`lib/migrations/*/YYYYMMDDHHMMSS_*.rb`の形で保存して，rakeのtaskとして実行し，なおかつ一度適用した変更はMongoDB上に記録して二度と適用しないようにする，それだけに専念する，ということで．

うーん，また次回の打ち合わせ時に確認したいですね．一回SS::Migrationが本流に入ると，以降未来永劫影響を与える機能になりそうですので．

**Comment by kaosf** [comment]
NOTE:

```ruby
gem 'mongoid_rails_migration', '1.1.0'
```

```sh
#rails generate mongoid:migration your_migration_name_here
rails g mongoid:migration your_migration_name_here
# e.g.
#rails g mongoid:migration ezine_member_default_enabled

db:migrate
db:rollback
```

**Comment by sunny4381** [comment]
SS::Migration の設計や実装の参考になるかと思い、コメントした次第です。
車輪の再発明という意図はありませんでした。
