### ISSUE TITLE
メタ情報「概要」のmeta descriptionにて属性値が適切にエスケープされない

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#3440]
メタ情報「概要」にて、`"`(ダブルコーテーション)を含むテキストがある場合、
meta descriptionのcontent属性にそのまま出力されてしまい、タグとして不正になる。
`<meta name="description" content="テスト"テスト"です" />`

### 確認環境
ver. 1.12.1
デモサイト(ver. 1.12.3)にても同一症状を確認

### 発見時詳細
本文冒頭に、`"`(ダブルコーテーション)で囲んだテキストあり。
概要自動設定: [有効]により、メタ情報「概要」に`"`(ダブルコーテーション)で囲んだテキストが自動設定

meta descriptionのcontent属性値が`"`により不正な記載となる。

### 備考 OGP
OGPのdescriptionでは`"`(ダブルコーテーション)`&quot;`に変換され正常に処理されていた。

**Comment by sunny4381** [comment]
v1.13.0で修正しました。
