### ISSUE TITLE
meta og:imageの重複

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#3441]
同一画像のog:imageが重複する場合がある。
チェックツールにより同一コードの重複として警告される場合があります。

### 確認環境
シラサギver. 1.12.1

### 詳細
サイト設定-Facebook設定-OpenGraph[記事]
記事にて、規定のフォーム(エディタ)を使用

本文中、画像Aを複数回使用あり
本文中の画像Aの出現回数分、meta og:imageの画像Aのコードが繰り返される。

### 要望
本文のimgタグ分がそのままmeta og:imageへ変換されているのでしょうか。
画像が同一のものをフィルタリング(ユニーク化)してから、meta og:imageとしていただきたいです。
検討願います。

**Comment by itowtips** [comment]
merged at 43c584c53db464789a203044a5e0c23fc3d392f5
