### ISSUE TITLE
イベントカレンダー リスト形式カテゴリによるフィルターのアクセシビリティ対応

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#3442]
フィルターボタンの実装が`<a  data-id="{id値}" href="#">`ですが、
チェックツールにより単にリンクと判断され、警告対象となります。

検出ツール Total Validator

> 異なるリンクテキストで同じ場所への隣接リンクがある場合、ユーザーを混乱させる可能性があります。 これらを1つのリンクに結合し、冗長なリンクテキストを削除することを検討する必要があります。

### イベントカレンダー リスト形式カテゴリによるフィルター
下図の青枠の箇所 [全て]〜[スポーツ]のボタン形状のリンク
![screenshot-demo ss-proj org-2020 02 05-11_09_03](https://user-images.githubusercontent.com/50577719/73805879-3b014300-480b-11ea-9c44-7fab005d0971.png)

### 要望
`<a href="#">`でなく、`<button>`タグ
`<a>`でも`<a href="#{カテゴリID}">`あるいは`<a href="?category={カテゴリID}">`など、機械的にチェックされる場合の回避は可能ではないでしょうか。

[nav要素の'aria-label'属性](https://github.com/shirasagi/shirasagi/issues/3436)の件と合わせてご検討願います。

**Comment by itowtips** [comment]
merged at 43c584c
