### ISSUE TITLE
 イベント/イベント検索フォームのアクセシビリティ対応

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#3443]
イベントカレンダーのイベント検索
デモサイトの場合 https://demo.ss-proj.org/calendar/search/

「施設」と「キーワード」にて、
miCheckerにて、「問題あり」とされます。

### キーワード
キーワードがfieldsetでくくられているのに、その中にlegendがありません。
fieldset要素には、そのグループの説明を含めたlegend要素を指定してください。

#### 参考
ラベル又は説明:達成基準 3.3.2 を理解する
https://waic.jp/docs/UNDERSTANDING-WCAG20/minimize-error-cues.html

H71: fieldset 要素及び legend 要素を使用して、フォームコントロールのグループに関する説明を提供する
https://waic.jp/docs/WCAG-TECHS/H71.html

### 施設
legend 要素はありますが、`<input type="text" name="facility_name" id="facility_name">`に対応するlabel要素がありません。
フォーム・コントロールにlabel要素およびtitle属性が関連付けられていません。

#### 参考
ラベル又は説明:達成基準 3.3.2 を理解する
https://waic.jp/docs/UNDERSTANDING-WCAG20/minimize-error-cues.html

H44: テキストラベルとフォームコントロールを関連付けるために、label 要素を使用する
https://waic.jp/docs/WCAG-TECHS/H44.html

H65: label 要素を使用できない場合に、フォームコントロールを特定するために、title 属性を使用する
https://waic.jp/docs/WCAG-TECHS/H65.html

**Comment by itowtips** [comment]
merged at 43c584c
