### ISSUE TITLE
イベントカレンダー表形式tableのcaptionとscope属性不足

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#3444]
https://demo.ss-proj.org/calendar/
フォルダー属性 イベント/イベントリスト
表形式=table要素ですが、アクセシビリティのチェックツールにて
以下の不足が指摘されますので、対応を検討願います。

- caption要素
- thのscope属性

### 参考

H39: データテーブルのキャプションとデータテーブルを関連付けるために、caption 要素を使用する
https://waic.jp/docs/WCAG-TECHS/H39

H63: データテーブルで見出しセルとデータセルを関連付けるために、scope 属性を使用する
https://waic.jp/docs/WCAG-TECHS/H63

**Comment by itowtips** [comment]
merged at 43c584c
