### ISSUE TITLE
descriptionとSNS用descriptionが不統一

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#3448]
「メタ情報」の「概要」欄に入力すると、meta descriptionに反映されます。
しかし、og:descriptionとtwitter:descriptionの内容は、本文からの自動抽出で規定字数に切り詰められるだけとなり、meta descriptionと異なります。
統一することを検討願います。

### 「メタ情報」の「概要」欄に入力がある場合の現状
```
<meta name="description" content="概要入力値 要約した文章に差し替えできる" />
<meta property="og:description" content="画像のタイトル 画像の説明文 本文を入力してください。本文を入力してください。本文を入力してください。本文を入力してください。 テキスト 本文を入力してください。本文を入力してください。&quot;本文&quot;を入力してください。本文を入力してください。 本文を入力してください。本文を入力してください。本文を入力してください。本文を入力してください。本文を入力してください。本文を入力してください。本文を入力..." />
```

meta descriptionは「メタ情報」の「概要」欄により内容の調整ができるが、
**og:descriptionとtwitter:descriptionの内容は調整が全くできない**。

### 要望

「メタ情報」の「概要」欄に入力がある場合、
og:descriptionとtwitter:descriptionの内容も「概要」欄を優先し、
meta descriptionと同一にしてはどうでしょうか。

「メタ情報」の「概要」欄が未入力の場合は、現状同様に本文の自動抽出のまま。

**Comment by sunny4381** [comment]
@ash0411-maker 
再現しないということで私が預かっていましたが、「既定のフォーム」だと再現します。定型フォームの場合は再現しないようです。
修正できそうなら対応をお願いします。

**Comment by itowtips** [comment]
merged at 6cfad21a0c5edb7d1406106e71743cef8fc8
