### ISSUE TITLE
デモデータの施設検索で地図表示がずれる

### ISSUE THREAD

**Issue by ShinjiTanimoto** [shirasagi/shirasagi#3475]
デモサイトの施設検索のフォルダー名を変更したり、フォルダーを複製したりすると地図表示がずれる。
style.scss で`#body--institution-map`を使用しているため、フォルダー名が`institution`から変更すると style.scss の修正も必要になる。

**Comment by sunny4381** [comment]
v1.13.0 で修正をリリースしました。
