### ISSUE TITLE
ブランチアドオン　画面修正

### ISSUE THREAD

**Issue by tany** [shirasagi/shirasagi#359]
作成ボタンの下に余白ができている。
![screen shot 2015-04-06 at 14 41 53](https://cloud.githubusercontent.com/assets/1378275/7001011/46e63dda-dc6b-11e4-825d-8cfba5a901b3.png)

ブランチ一覧のリンクが`_blank`なのでタブがどんどん増えていってしまう。

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/commit/bf924be5ee369a6244986dc421a50130af6c5fd0
* 余白を非表示に変更
* _blank を削除
