### ISSUE TITLE
GWS スケジュールモデルと設備予約モデル

### ISSUE THREAD

**Issue by kaosf** [shirasagi/shirasagi#368]
メモ代わりに使う．

**Comment by kaosf** [comment]
## スケジュール関連モデル名

モジュール名 `Schedule`
クラス名 `Schedule::Plan`

## 設備予約関連モデル名

モジュール名 `Reservation`
クラス名 `Reservation::Plan`

**Comment by kaosf** [comment]
@tany とりあえずスケジュールと設備予約の基礎となるクラス名は `Plan` でいいでしょうか？

**Comment by kaosf** [comment]
## 要件

* タイトルと本文がある
* 添付ファイル(複数)を設定可能
* 開始日時・終了日時がある
* 開始日時と終了日時が日を跨ぐことも出来る
* 終日という特殊な時刻設定が出来る
* 未定という特殊な時刻設定が出来る(未定でも日付は決めないとダメ)
* スケジュールは複数人に関連付けすることが出来る
* スケジュールは複数の施設を同時に持つことが出来る(has_many :reservation_plans的な)
* 同一設備の利用時間が衝突してはいけない
* 繰り返しのスケジュールを作成することが出来る
* 公開範囲が設定出来る
* 編集権限が設定出来る(閲覧不可，閲覧可能，編集可能)

### MではなくVCよりの要件

* スケジュールの引用作成が出来る

**Comment by kaosf** [comment]
## 設備要件

* 管理者的なユーザが作成，破棄出来る

**Comment by kaosf** [comment]
## フィールド名

コードのサンプルを書いてみる

```ruby
class Schedule::Plan
  include Mongoid::Document

  field :title, type: String
  field :body, type: String
  field :start_at, type: DateTime
  field :end_at, type: DateTime

  # 終日と未定 案 1
  #field :allday, type: Integer # (0: false, 1: 終日 2: 未定)

  # 終日と未定 案 2
  field :allday, type: Boolean
  field :mitei, type: Boolean # TODO: mitei -> 正しい単語に

  #field :repeat, type; Boolean # NOTE: 繰り返しを考えるならこういうのが要る

  #belong_to :user
  #field :user_id, type: BSONObjectId
  # TODO: 作成者に関連付ける

  has_many :users
  has_many_and_belongs_to :users
  # 予定に関連する人を関連付ける
  # NOTE: 多対多を実現する
end
```

**Comment by kaosf** [comment]
## スケジュールの衝突について

`Schedule::Plan#collide_to?` というメソッドでスケジュール同士(※設備同士の場合も同じようなものを考える)の衝突判定が出来るとして，恐らく以下のようなテストケースを書いていく必要がある．

```
describe "#collide_to?" do
  subject { plan1.collide_to? plan2 }

  context "" do
    let(:plan1) do
      create :schedule_plan,
        started_at: DateTime.new(2015, 4, 1, 0, 0),
        ended_at: DateTime.new(2015, 4, 1, 1, 0)
    end

    let(:plan2) do
      create :schedule_plan,
        started_at: DateTime.new(2015, 4, 1, 1, 0),
        ended_at: DateTime.new(2015, 4, 1, 2, 0)
    end

    it { is_expected.to be_falsy }
  end

  context "" do
    let(:plan1) do
      create :schedule_plan,
        started_at: DateTime.new(2015, 4, 1, 0, 0),
        ended_at: DateTime.new(2015, 4, 1, 1, 0)
    end

    let(:plan2) do
      create :schedule_plan,
        started_at: DateTime.new(2015, 4, 1, 0, 59),
        ended_at: DateTime.new(2015, 4, 1, 2, 0)
    end

    it { is_expected.to be_true }
  end
end
```

スケジュールの衝突がいつ起こるべきなのか，起こらないべきかのか，は今後詳細に考える．

**Comment by kaosf** [comment]
繰り返しスケジュールについて，`Schedule::Plan` をまとめる `Schedule::PlanGroup` のようなモデルが存在し，

`Schedule::Plan` `belongs_to` `Schedule::PlanGroup`

`Schedule::PlanGroup` `has_many` `Schedule::Plan`s (ここで `dependent: :destroy` にする)

のような関係になっているとする．

子となる全てのモデルが削除された場合に親となるモデルにも消えて欲しいという要件を実現する方法として，https://github.com/kaosf/rails-belongs-to-destroy-experiment/blob/03f888eab096858055227df59392ec5b99587013/app/models/item.rb#L4-L7 のような実装方法がある．

もし以下のように

```ruby
after_destroy do
  if item_group.items.count == 0
    item_group.destroy
  end
end
```

とすると無限再帰が発生してしまう．`item_group`を`after_destroy`の時点で取得取得し直す(新しいActiveRecordインスタンスを生成する)必要がある．

Mongoidの場合どうなるのかはまだ調べていない．

**Comment by mizoki** [comment]
## 繰り返しスケジュールの登録についてのメモ

- 繰り返しの種類は？
    - 毎日、毎週、毎月、毎年、毎月曜日、毎火曜日、毎水曜日、毎木曜日、毎金曜日、毎土曜日、毎日曜日
    - 営業日を考慮した繰り返しは必要？
- 繰り返しのスケジュールの終了日を指定する？
    - 終了日を指定しない場合、いつまで作る？
- 繰り返しスケジュールの登録のタイミングは？
    - 案1
        - 最大の終了日を設定して、その日付までのスケジュールを最初に登録する。
    - 案2
        - 最初に決められた数のスケジュールを作って、あとは定期的にタスクを走らせて、スケジュールの更新を行う。
    - 案3
        - カレンダーの表示前に、繰り返しの情報を読んで、作られていなかったら作成する。
- 毎日と毎年では登録されるスケジュール数が違うので、同列に扱ってもいいものか？
