### ISSUE TITLE
サイトマップ機能　URLリスト出力

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#374]
「URLリスト出力」を押下した際、フォルダの並び順に沿って出力が出来ないでしょうか

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/commit/0ff261061c9f63d989ca0f61da11bdfa405fb887
* フォルダの並び順にてソートするよう修正。
* 同じ親フォルダ下にて並び替えをおこうなうようにしました。

**Comment by itowtips** [comment]
例)

|URL　　　　　　　　　　　　　 |並び順|
|------------------------------|------------|
|/docs/1.html                  | 10          |
| /docs/2.html                 | 0          |
| /kurashi/aaa.html　　　  |  100     |
| /kurashi/bbb.html　　　   |  1       |


↓

|URL　　　　　　　　　　　　　 |並び順|
|------------------------------|------------|
|/docs/2.html                  | 0            |
| /docs/1.html                 | 10          |
| /kurashi/bbb.html　　　  |    1         |
| /kurashi/aaa.html　　　   |  100      |

**Comment by MasakiInaya** [comment]
このように並ぶようにできないでしょうか。

/kurashi/
/kurashi/aa/
/kurashi/aa/cc/
/kurashi/dd/
/kurashi/bbb/

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/commit/43ac35b5872d297e61ff3c85afcff861a3cb7513
* 親フォルダの間に子孫を差し込んでいくような並び替えに変更
