### ISSUE TITLE
メンバー登録フォームのメールフォームとの差異

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#3784]
メンバー登録はアクセシビリティ対応が不足しています。
　#1177 同様に性別ラジオボタンのfieldset要素が不足

また、メールフォームとclassが微妙に違うため、styleを統一しにくい状態でした。

メールフォームと登録フォームのいずれが誤記なのではないでしょうか?
メールフォームは入力欄のラッパー `fieldset.column `または` dl.column`ですが、
メンバー登録は、`dl.colum`と、揺れているように見えます。

**Comment by y-teraz** [comment]
同様に、ログイン後のプロフィールもコード差異が多く、styleの調整が辛いです。

具体的には、誕生日の入力セットが`dl.birthday`でくくられていましたが、
プロフィール編集時にはこれが有りません。

**Comment by sunny4381** [comment]
堪能な限り調整しました。多少の差異は、過去との互換性もありこれ以上の調整は難しいです。
