### ISSUE TITLE
パーツの親フォルダー名表示　プレビュー時不具合

### ISSUE THREAD

**Issue by itowtips** [shirasagi/shirasagi#385]
#93 で追加した #{parent_name} がプレビューで表示すると展開されない
検索条件の#{request_dir}も同様

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/commit/8c1898890d975d00d0eb89d19141418c59125a38
* 該当箇所でpreviewのpathを置換するように変更

**Comment by tany** [comment]
@cur_path自体を書き換えた方がよいのでは？

**Comment by itowtips** [comment]
>@cur_path自体を書き換えた方がよいのでは？

previewのコントローラーで@cur_pathを書き換えている箇所を見つけましたが、
これが呼ばれる前にレイアウトを展開しているのでしょうか。それとも全く見当違いでしょうか。
https://github.com/shirasagi/shirasagi/blob/master/app/controllers/cms/preview_controller.rb#L17-23

**Comment by tany** [comment]
/previewや/mobile関係なく@cur_pathを利用できるのが理想です。
そうしないと至る所に置換処理を挟む必要がありますし、request.pathと同じになります。
