### ISSUE TITLE
[CMS][ページ検索] ダウンロード結果に他サイトの情報が含まれる場合がある

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#3872]
再現手順:

1. デモサイトの管理画面 <https://demo.ss-proj.org/.mypage> にログインする。
2. 「子育て支援サンプル」サイトの news フォルダーのタイトルを「子育ての新着情報」などと変更する。
3. docs フォルダー内で「子育ての新着情報」に関連づけた記事ページを作成する。
4. サイト内検索のページ検索で、カテゴリーに「子育ての新着情報」を選択し、検索する。
5. 検索結果をダウンロードする。
6. ダウンロードされた CSV を開くと、カテゴリ列に「ニュース」と表示される。

**Comment by itowtips** [comment]
merged at b22b50a2799a646bdfbe5e8cb839c79ffba
