### ISSUE TITLE
アップローダー　一括削除スクリプトが動作していない

### ISSUE THREAD

**Issue by tany** [shirasagi/shirasagi#389]
ファイル一覧画面で`すべて削除`のリンクが表示されない。
http://demo.ss-proj.org/.demo/uploader159/files/css

表示自体は下記修正で出力されるがその後が動作しない。
https://github.com/shirasagi/shirasagi/blob/master/app/assets/javascripts/ss/lib/list_ui.coffee.erb#L7
```
- if $(this).attr("href")[-7..-1] == "/delete"
+ if $(this).attr("href")[-6..-1] == "delete"
```

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/commit/59cc0d687e3bf98f1d5e3c35ab78dde81308976e
*  `すべて削除`　動作するよう修正
