### ISSUE TITLE
[CMS][緊急災害レイアウト] サイト設定のモバイルの状態が「無効」の場合、フォルダーを開くとエラーになる

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#3895]
標記の通り。再現手順

1. CMS へログインしサイト設定を編集する。
2. モバイル設定の状態を「無効」に設定し、保存する。
3. 緊急災害レウアウトフォルダーを開く。

**Comment by itowtips** [comment]
merged at 7526ba9b634b3750c7b62b472c1d
