### ISSUE TITLE
自動インストール時に nginx が起動しない

### ISSUE THREAD

**Issue by kto2038** [shirasagi/shirasagi#3913]
CentOS 7.9 で、install.sh を使用して自動インストールすると nginx が起動しません。
/var/log/nginx/error.log を確認すると以下のメッセージが出ています。
`2021/05/28 11:43:50 [emerg] 8540#8540: "map" directive is not allowed here in /etc/nginx/conf.d/header.conf:1`

/etc/nginx/conf.d/header.conf の 7e56d7d で変更された箇所を元に戻し、
systemctl start nginx すると起動しました。

**Comment by sunny4381** [comment]
@ff38ff5d049156de6a299fca2af885fda7ddaf51 で修正

**Comment by kto2038** [comment]
nginx の設定ファイルが修正され、nginx が起動することを確認しました。
