### ISSUE TITLE
[CMS] クイック編集機能が欲しい

### ISSUE THREAD

**Issue by wt-nakajima** [shirasagi/shirasagi#3931]
並び順を設定することが多いが、修正が多岐に渡ると編集画面→並び順指定→保存の流れが結構面倒。
WordPressならクイック編集という機能があり詳細画面まで行かなくても一覧で編集が可能。
→固定ページの一覧では、並び順が表示されておらず名前順で並んでいることもわかりにくいので、並び順の表示も実装されると嬉しい。

**Comment by tamatips** [comment]
@sunny4381 

- 「一覧用タイトル」も編集できたら便利という意見がありますが、ニーズとしては低めで、画面表示にも余裕がなさそうなので、今回は見送ります。
- 本機能が使用できるのは、フォルダーの編集権限がある人だけという認識です。
- そもそものイシューの内容は記述内容を見るに固定ページの一覧と読み取れますが、対象は固定ページ一覧画面とフォルダー一覧画面でしょうか。
- 「並び順が表示されておらず名前順で並んでいることもわかりにくい」と記載されていて、表示順が現在「名前順」になっている様ですが、一見何順になっているか分からないのと、「名前順」と「並び順」切り替えができると尚よいと思いました。（修正イメージを添付します。）

![スクリーンショット 2024-07-01 16 02 42](https://github.com/shirasagi/shirasagi/assets/87358283/994565f1-e835-43d8-8e01-a1f3b105f982)

**Comment by sunny4381** [comment]
@tamatips 
- 対象は、フォルダーのみ - しかもカテゴリーフォルダーのみ - となります。
- 添付された画像は Quick 編集とは無関係ですよね。そして、ソートは、MongoDB の弁慶の泣き所とでもいう機能なので、すみませんが、見送らさせていただきます。
