### ISSUE TITLE
there is no workflow_state naming convention 

### ISSUE THREAD

**Issue by TQuy** [shirasagi/shirasagi#4018]
I think there is a mess between adjective, verb past tense and verb
  WORKFLOW_STATE_PUBLIC = "public".freeze
  WORKFLOW_STATE_CLOSED = "closed".freeze
  WORKFLOW_STATE_REQUEST = "request".freeze
  WORKFLOW_STATE_APPROVE = "approve".freeze
  WORKFLOW_STATE_PENDING = "pending".freeze
  WORKFLOW_STATE_REMAND = "remand".freeze
  WORKFLOW_STATE_CANCELLED = "cancelled".freeze
  WORKFLOW_STATE_OTHER_APPROVED = "other_approved".freeze
  WORKFLOW_STATE_OTHER_REMANDED = "other_remanded".freeze
  WORKFLOW_STATE_OTHER_PULLED_UP = "other_pulled_up".freeze

**Comment by sunny4381** [comment]
Thanks for sharing your idea and we know you are right, but we decide to reject because we need to apply lots of migration.
