### ISSUE TITLE
自動インストール時に sks-keyservers.net にアクセスできずエラー

### ISSUE THREAD

**Issue by kto2038** [shirasagi/shirasagi#4023]
CentOS 7.9 で install.sh を使用して自動インストールすると hkp://pool.sks-keyservers.net のところでエラーとなり止まってしまいます。
sks-keyservers.net はサービスが停止したようです。

事前に以下を行っておくとインストールが継続できました。
`curl -sSL https://rvm.io/mpapis.asc | gpg --import -`
`curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -`

**Comment by itowtips** [comment]
https://github.com/shirasagi/shirasagi/pull/4030 にて修正しました。
