### ISSUE TITLE
サンプルユーザーに uid を登録してほしい

### ISSUE THREAD

**Issue by tany** [shirasagi/shirasagi#410]
デモサイト等で簡単にログインできるようにしたいため。

sys@example.jp → sys
admin@example.jp → admin

**Comment by sunny4381** [comment]
以下で uid を設定していますがダメですか？

* https://github.com/shirasagi/shirasagi/blob/master/db/seeds/users/load.rb#L67
* https://github.com/shirasagi/shirasagi/blob/master/db/seeds/users/load.rb#L96-L101

**Comment by tany** [comment]
@sunny4381 ソースについては了解です。

デモサイトと公式サイトの更新が必要です。

**Comment by sunny4381** [comment]
シラサギ 0.7.0 をリリースして、その際に uid を登録する感じですか？

**Comment by tany** [comment]
そうですね。
開発とは直接関係ないですが、サイトは当プロジェクトの管理なので念のため。

**Comment by tany** [comment]
公式サイトは下記ページを更新。
http://www.ss-proj.org/download/demo.html
