### ISSUE TITLE
config/*.yml の初期値

### ISSUE THREAD

**Issue by tany** [shirasagi/shirasagi#412]
`config/samples/*.yml` の値を初期値にしたら便利じゃないでしょうか？

**Comment by sunny4381** [comment]
賛成!
前から同じことを思っていました。

**Comment by tany** [comment]
階層が複雑になっている設定ファイルは初期値の上書きが面倒な予感がします。
全て一階層なら単純明快なんですが。

**Comment by tany** [comment]
## config/defaults
`{Module}::Config` クラスを削除しました。
`config/defaults/{module}.yml` が初期値になります。
`config/{module}.yml` を置くと上書きできるのは以前と同じです。

## config/samples
samples には以下のファイルが残りました。
```
multiple-dbs/mongoid.yml
mongoid.yml
secrets.yml
unicorn.rb
```
`multiple-dbs/` は `cp` でコピーされないようにフォルダーに入りました。
他の3ファイルは Rails の起動に必要です。

## 確認事項
以下の設定が静的な値ではなかったので確認ねがいます。
とりあえずデフォルト値のパス(String)に置き換えました。
```
config.kana.root #Kana::Dictionary
config.voice.root #Voice::File
```

更新手順の差分追加 `cp -n config/samples/* config/` は不要になります。

**Comment by tcmaru** [comment]
tany様、はじめまして。
Rubyも書けない単なるシステムユーザーなのですが、こちらにコメントさせて頂きました。
既にクローズしてあるldap.ymlなのですが、昨日からshirasagiのopendataを試用させて頂いております。
ユーザーをldapサーバからインポートしようとしたのですが、
「問題が発生しました。
次の項目を確認してください。
    Ldap::BindError」
と出まして、ldap.ymlの設定、あるいはshirasagiの他のyml設定が不足しているのか否か分からない状態に陥っております。お知恵をお貸し願えれば嬉しいです。

このldap.ymlには、ldapサーバのDNへのbindユーザ情報を設定していないのですが、あくまでもshirasagiにログインしているシステム管理者ユーザーがLDAP上に存在していれば良い、という前提で作業しているのですが、既存のLDAPサーバ（openLDAP）の管理者アカウントと同一のアカウントをshirasagiに新規追加して、そのユーザーでshirasagiにログインした状態でも、上記の「Ldap::BindError」が出てしまいます。

お忙しいところと思いますので、お時間のあるときにコメント頂けると幸いです。

**Comment by kaosf** [comment]
@tcmaru 新しいIssueを遠慮なく立てても良いですよ．https://github.com/shirasagi/opendata の方に立てても良いですし．

**Comment by tany** [comment]
@tcmaru ldap.yml にはLDAPサーバのホストを設定し、DN(Base DN)はグループに設定するようになっています。
各グループにDNを設定すれば解決するかと思います。
また、ユーザーもDNを持っていて、ログイン時にはこれを参照しています。
https://github.com/shirasagi/shirasagi/blob/master/app/models/concerns/ldap/addon/user.rb#L19
