### ISSUE TITLE
アップロードするファイル名に使用できる文字種の制限

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#415]
## 背景

シラサギ標準としては、ファイル名に使用できる文字種は、英数字のみが好ましいが、とあるサイトでは日本語も OK だが、とあるサイトでは日本語 NG で英数字のみという状態である。
## 実装案
- config/*.yml の設定で、ファイル名に使用できる文字種を指定できるようにする。
- 既定値は英数字のみ。
- 日本語 OK のサイトでは、config/*.yml を設定し、日本語 OK とする。
- 英数字のみの正規表現パターンは: `/^[\w\-]+\.[\w\-.]+$/`
- 日本語のみの正規表現パターンは、今後検討する。
## 参考
- #306
- #307
- #351

**Comment by tany** [comment]
２種類の設定が可能。
https://github.com/shirasagi/shirasagi/blob/master/config/defaults/environment.yml

~~~
# multibyte filename validation
#   underscore - replace multibyte characters to underscore
#   sequence - replace filename to sequence id if filename include multibyte characters
multibyte_filename: underscore
~~~
