### ISSUE TITLE
Rails Engine を利用したモジュールの分割

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#419]
## 参考

いきなりですが、まず参考ページをあげます。

* [Mountable Engine だらけの Rails アプリ開発](http://blog.onk.ninja/2014/12/02/mountable_engine.html)
* [TaskRabbit: 複数のRails 4 Enginesで構成したアプリ](http://wazanova.jp/items/1026)
* [Railsエンジンの組み合わせでアプリを大きくする3つのメリットとデメリット](http://blog.mah-lab.com/2013/12/27/rails-engine-3-merit-demerit/)

## SHIRASAGI に適用した場合のメリットとデメリット

現時点で考えられるメリット・デメリット。

Pros

* モジュールの規模を小さく保ちやすく、管理しやすくなる。
* GW やオープンデータなどを別 Engine として開発することで、
  プラグイン管理をしやすくなる。

Cons

* モジュールが分割することにより、開発速度が低下するかも。
* ソースのコピペが多数発生し、DRY 度が低下するかも。
* 一つの機能開発に、複数の Gem / Engine などを修正しなければならなくなり、開発が面倒になるかも。

**Comment by sunny4381** [comment]
個人的にも実現性にちょっと問題がアリそうなアイデアで、
誰からもコメントがなかったので、閉じます。

**Comment by kaosf** [comment]
個人的にはまずは「gemに切り分け」から取り掛かりたいなーと思ってます．
