### ISSUE TITLE
[CMS] ゴミ箱から添付ファイルを復元する際、ファイル名を変更できるかのようなUIだが、実際は変更できない

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#4219]

**Comment by tamatips** [comment]
◯問題点
１）記事を作成し、記事内にファイルを添付
２）１）の記事を削除
３）管理画面のゴミ箱から１）の記事内の添付ファイルを選択

![スクリーンショット 2024-05-30 15 51 04](https://github.com/shirasagi/shirasagi/assets/87358283/7d364a9c-f985-4084-b764-d338613fb305)

４）画面上部の「元に戻す」をクリック

![スクリーンショット 2024-05-30 15 48 47](https://github.com/shirasagi/shirasagi/assets/87358283/f6117bfe-9dde-49d6-813d-d79fdd2b0e4d)

５）ファイル名が２つ並んでおり、下のファイル名はおそらく「ファイル名（英数）」のことと思われるが表記が「ファイル名」に変わってしまっており、結果的に同じ項目名が２つ並んでしまっている状態。
下のファイル名の右に「変更する」ボタンがあり、ファイル名が変更できるように見えるためクリック

![スクリーンショット 2024-05-30 15 49 04](https://github.com/shirasagi/shirasagi/assets/87358283/9422994b-24bd-4faf-887a-32fa5e7b1d2d)

６）ファイル名を編集して画面下部の「元に戻す」をクリック

![スクリーンショット 2024-05-30 15 49 13](https://github.com/shirasagi/shirasagi/assets/87358283/cd77189d-6ca2-4d5b-9f13-dd1c99b5f1bd)

７）該当ファイルが「共有ファイル」に復旧されるがファイル名は元のファイル名のままになっている

![スクリーンショット 2024-05-30 15 49 38](https://github.com/shirasagi/shirasagi/assets/87358283/0b65a527-7a61-4ef0-8554-d2f9b376a9f0)

◯改善案
そもそも上記の５）に記載の通り、「ファイル名」が２つ並んでしまっているので、下の方の「ファイル名」を「ファイル名（英数）」に修正する

また、下記２案のどちらかで修正を行う。
シンプルにB案でもよいかもしれません。

A案)「ファイル名」と「ファイル名（英数）」の両方の右に「変更する」ボタンを用意して、
元に戻す際に両方をファイル名変更できるようにする

B案）「変更する」ボタンを削除して、ファイルの復旧時にはファイル名を変更できないようにする。

**Comment by sunny4381** [comment]
添付ファイルをゴミ箱から復元すると、共有ファイルとして復元されます。
対して、共有ファイル側をチェックすると、「ファイル名（英数）」は表示されていませんし、編集することもできません。

ゴミ箱内の添付ファイルで、「ファイル名（英数）」を表示したり、編集したりすることができましたが、「ファイル名（英数）」を非表示とし、編集ることもできないようにしました。
