### ISSUE TITLE
Mongo の field 上書き警告ログが出るようになった。

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#428]
次のようなログが、また、出るようになった。

```
W, [2015-05-13T17:19:42.228131 #20703]  WARN -- : Overwriting existing field upper_html in class Facility::Node::Search.
```

`Facility::Addon::SearchResult` クラスの `upper_html` フィールドに `overwrite: true` の指定が必要。
もしくは、`Facility::Addon::SearchResult` クラスの `upper_html` フィールドを別の名前に変える。

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/commit/7c377fc3dd79111b09058d84ad0ec230262aaddc
このフィールドの名前は`upper_html`で良いと思うので、`overwrite: true`を付けました。
