### ISSUE TITLE
ファイルアップロード時の Content Type

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#434]
現在は、ブラウザが送ってきた Content Type を保存しているが、ブラウザによって送ってくる Content Type が異なる場合がある。

例えば `.js` ファイルの場合、

| Browser | Conten Type |
|---------|-------------|
| IE      | application/octet-stream |
| Chrome  | application/javascript |
| FireFox | application/x-javascript |

このような違いが、まれに障害を生じる。

そこで、ブラウザが送ってきた Content Type ではなく、サーバで判断した Content Type を保存するようにする。

**Comment by sunny4381** [comment]
Rails にはファイル名から MIME Type を検索するクラス/メソッド `::MIME::Types.type_for(path).first.content_type` がある。

| 拡張子 | Mime Type |
|--------|-----------|
| .bmp | image/x-bmp |
| .css | text/css |
| .csv | text/comma-separated-values |
| .doc | application/msword |
| .docx | application/vnd.openxmlformats-officedocument.wordprocessingml.document |
| .gif | image/gif |
| .html | text/html |
| .jpg | image/jpeg |
| .js | application/javascript |
| .json | application/json |
| .jtd | _unregistered_ |
| .lzh | application/x-lzh-compressed |
| .mht | _unregistered_ |
| .mp3 | audio/mpeg |
| .odt | application/vnd.oasis.opendocument.text |
| .pdf | application/pdf |
| .png | image/png |
| .ppt | application/powerpoint |
| .pptx | application/vnd.openxmlformats-officedocument.presentationml.presentation |
| .rtf | application/rtf |
| .txt | text/plain |
| .wma | audio/x-ms-wma |
| .wmv | audio/x-ms-wmv |
| .xls | application/excel |
| .xlsx | application/vnd.openxmlformats-officedocument.spreadsheetml.sheet |
| .zip | application/zip |

`.jtd` と `.mht` が登録なし。
`.wmv` が `audio/x-ms-wmv` となっているが、正しくは `video/x-ms-wmv`。

**Comment by sunny4381** [comment]
基本的に `::MIME::Types.type_for(path).first.content_type` を使えば良さそうだが、設定ファイルなどで変更できるようにしておいたほうが吉。

次のような順で Mime Type を検索する。

1. 設定ファイルから Mime Type を取得。
2. 1 が失敗した場合、Rails 方式で取得。
3. 2 が失敗した場合、ブラウザが送ってきた Content Type を保存する。

**Comment by sunny4381** [comment]
関連: #435

**Comment by sunny4381** [comment]
設定ファイルとして `environment.yml` を用い、`SS::MimeTypes` クラスを新規作成し、`SS::MimeTypes` クラスでMime Type を検索しようと思います。

**Comment by sunny4381** [comment]
Migration を追加しましたが、サーバに保存されているファイルを強制的に変更するので、冗長・やり過ぎかもしれません。
この Migration に関して、コメントいただければと思います。

**Comment by tany** [comment]
なくてもいいかなと思います。

**Comment by sunny4381** [comment]
migration を削除しました。
