### ISSUE TITLE
[CMS] ブロック入力の表 編集画面での見出しセルの配色

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#4348]
編集画面にて、ブロック入力の表の見出しセルthの配色を調整願います。

入力時は問題ありませんが、
入力後のセル配色が文字色#333の背景色#777のため、コントラスト不足で視認性が悪いです。

下図、左1列目のth入力済み、2列目が入力中
![スクリーンショット 2022-01-07 11 02 57](https://user-images.githubusercontent.com/50577719/148480080-bb2278f8-0ef6-4608-b5b3-8bb59b831600.png)

![スクリーンショット 2022-01-07 11 10 36](https://user-images.githubusercontent.com/50577719/148480063-2506ff7a-862e-45fd-8890-986c3e84de7c.png)

**Comment by tamatips** [comment]
◯修正案

本来であればCMSでよく使われている色である、黒、赤褐色（オレンジ？）、灰色、白とその濃淡色バリエーションのうち使用されていない赤系統を使用したいところでしたが、シラサギ管理画面では入力中のフォームの色がピンクになる仕様になっているため、
他の色で検討した結果、比較的近い色として淡い黄色（カラーコード：#fff5e5）がよいように思います。

![スクリーンショット 2024-05-20 23 17 32](https://github.com/shirasagi/shirasagi/assets/87358283/942d0fd7-2299-4a3b-aa5b-257557cbbfef)

淡い黄色（カラーコード：#fff5e5）であれば赤褐色と遠くなく、
また実際に画面に使用しても違和感がないと思います。
