### ISSUE TITLE
添付ファイルの静的化

### ISSUE THREAD

**Issue by itowtips** [shirasagi/shirasagi#435]
現在、添付ファイルは記事のように静的に書き出されているわけではなく
全て動的に処理されている。これを静的に書き出されるようにする。

**Comment by itowtips** [comment]
書き出されたファイルはサイトごとに分けて保存するため、
パスは次のような感じで考えました。
` public/sites/w/w/w/_/fs/26/image.png `
※ルートに/fs/というフォルダーは作れないようにしなければならない

**Comment by itowtips** [comment]
フォルダーに添付ファイルを付与する使い方はしていないので
添付書き出しはページ書き出しのタイミングを想定し
対象となるファイルは以下で全部でしょうか。
*  ページの添付ファイル
* バナーの画像
* 施設の画像

**Comment by tany** [comment]
Model によっては動的に表示させたい場合もあるので、
書き出す/書き出さないは Model で操作できるほうがよいです。

**Comment by itowtips** [comment]
@tany わかりました。

**Comment by sunny4381** [comment]
OD では、日本語のファイル名があります。日本語のファイル名の場合の静的に書き出しの仕様はどうなりますか？
※日本語ファイル名の場合は書き出せない、という制限でも、個人的には良いかと考えています。

**Comment by itowtips** [comment]
>OD では、日本語のファイル名があります。日本語のファイル名の場合の静的に書き出しの仕様はどうなりますか？
>※日本語ファイル名の場合は書き出せない、という制限でも、個人的には良いかと考えています。

以前ＭＴでも話題に出ましたが、日本語ファイル名は使わない方針になっていっているので、
「日本語ファイル名は書き出されない」は良いと思います。
しかし、そもそも日本語ファイルをアップできることがおかしいということであれば、これを書き出し時のロジックを入れるかは悩みます。

**Comment by sunny4381** [comment]
OD で日本語ファイルがアップされているのが、悩ましいですね。
参考: #415

**Comment by itowtips** [comment]
ひとつ実装を作成
https://github.com/itowtips/shirasagi/commit/50d2a3309bd2549835f63667b9584af9578563b2

* `generate_relation_files :files` でコールバックを設定し添付ファイルを書き出す。
  *  別案 `embeds_files :files, class_name: "SS::File", generate: true` のようなメソッドを作りオプションを設ける
*  ss_fileにsite_idが設定されていなければ書き出されない。
*  バナー、施設画像はそのまま動的。
*  日本語ファイル名を書き出さないように `basename.ascii_only?`を付けてみました。

**Comment by tany** [comment]
`generate: true` overwrite field はあまりしたくないので
`#sever_static_file?` のように別途定義できたほうがよいと思います。

**Comment by tany** [comment]
`SS::Relation::File`
自分で持っていない `files` を扱うのはおかしい気がします。
限定的な使用なら直接書くか、 `Relation::Files` を考えるとか。

`#validate_filename`
`super` は呼んでいるだけなら、新たに `vavlidate` を追加した方がいいのでは？

`#generate_relation_file`
コールバックを設定するだけのような処理なら直接 `after_generate_file` 書いた方が早いのでは？

`::File.open(path, 'wb') { |f| f.write(data) }`
`File.binwrite` メソッドもあります。

**Comment by tany** [comment]
広告管理はフィールド定義時に指定できると便利です。
```
belongs_to_file :file, public_file: true
```

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/commit/baea4741baf4d3cb831633a9cc62543ebfc15f75

`SS::Relation::File`
ここで `embeds` されている `files` を扱うのをやめました。

`#validate_filename`
`#validate_node_filename` を新しく追加しました。

`#validate_filename`
直接 `after_generate_file` をモデル側に書きました。

`::File.open(path, 'wb') { |f| f.write(data) }`
`File.binwrite` を使うようにしました。

`belongs_to_file :file, public_file: true`
`belongs_to_file` を拡張し `public_file` オプションを追加しました。

**Comment by itowtips** [comment]
すみません上のコミット `dump` が残ってしまいました。
次が修正コミットです。
https://github.com/itowtips/shirasagi/commit/cb897b41a7ed46a8e973fa1310df37bdc15be033

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/commit/92f35b804b78e37808ab7645035f7628ffbaf6c4
MT指摘個所を修正

**Comment by tany** [comment]
自動的に呼ばれないなら
`def generate_relation_public_file(field)`
のように定義した方がいいようにも思いますが、全体通して推敲お願いします。

**Comment by itowtips** [comment]
@tany わかりました。

**Comment by tany** [comment]
とりあえず ‘define_method("generate_relation_public_#{name}")` は `if` なしで作っておいて
処理は個別になんとかしてもらうとか。

**Comment by tany** [comment]
`find_by_field` は↑のノリですけど、廃止になったのは思想が違ったということかも？

**Comment by itowtips** [comment]
belongs_to で自動生成される build_association や create_association のようなものと考えれば、
確かに public_file true のような option は不要で、勝手に使ってもらうのがいいかと思います。

**Comment by itowtips** [comment]
サムネイル画像の保存
実装が追い付いていませんが、次のような感じで試行中

■DB
元画像　　　  `{ id: 1, thumb_id: 2, filename: "abc.jpg" }`
サムネイル　`{ id: 2, filename: "abc.jpg" }`

■クラス
<pre>
SS::File
　model "ss/file"
   belongs_to_file :thumb, class_name: "SS::ThumbFile"
SS::TempFile
　model "ss/temp_file"
SS::ThumbFile
　model: "ss/thumb_file"
</pre>

■サムネイル保存
<pre>
item = SS::File.where(filename: /\.jpg/).first
item.save_thumb(100, 80) #default 120x90
</pre>
 
■動的表示
`fs/1/abc.jpg`　元画像そのまま表示
`fs/2/abc.jpg`　サムネイル画像そのまま表示
`fs/1/thumb/abc.jpg`　サムネイル表示
`fs/2/thumb/abc.jpg`　サムネイル画像そのまま表示

■公開側静的path
`fs/1/abc.jpg`
`fs/2/thumb/abc.jpg`

**Comment by tany** [comment]
所感です。（深くは考えていない）
- サムネイル側にオリジナルIDかフラグを持ってないと、オリジナル紛失時に掃除できるかどうか。
- サムネイルにIDを持てるなら、DIR `/thumb/` は無くせるなら無くした方がいい。

**Comment by itowtips** [comment]
> サムネイル側にオリジナルIDかフラグを持ってないと、オリジナル紛失時に掃除できるかどうか。

これは `ss_files `の `model `が `ss/thumb_file `になるので掃除はできると考えていました。

**Comment by itowtips** [comment]
rake taskでの添付ファイル書き出しを止めるコミット
https://github.com/itowtips/shirasagi/commit/9cc07e36d6254322699770d690b28b0f17d52f4a

以前マージされたコミットはtaskで添付ファイルを書き出すので、書き出しが遅くなりました。
 `rake cms:generate_pages site=www`
の時は添付ファイルは書き出さず、
 `rake cms:generate_pages site=www attachment_files=generate`
のようにオプションを付けた時に書き出すようにします。

**Comment by itowtips** [comment]
問題点
callbackで実装しているので書き出すか書き出さないかのフラグが必要
`attr_accessor :serve_static_relation_files`

taskのオプションをコントローラー側で拾う方法が分からなった
<pre>
#@generate_relation_files = (params[:attachment_files] == "generate")
@generate_relation_files = (ENV["attachment_files"] == "generate")
</pre>

**Comment by itowtips** [comment]
genarete_fileのcallbackにgenerate_relation_filesを入れるのをやめて
別々にafter_saveを書いたほうがいいのかもしれない。(ss_relationの問題もあるので)
ただtask側で呼び出す仕組みが必要。

**Comment by itowtips** [comment]
> taskのオプションをコントローラー側で拾う方法が分からなった

これは解決
https://github.com/itowtips/shirasagi/commit/fbbfd124f346ee34662428181d354ea76503c3ba

**Comment by itowtips** [comment]
https://github.com/shirasagi/shirasagi/commit/1d095adf533df99afdee726c33b2fca477caa83d
cms/addon/file で画像のサムネイルを作成
