### ISSUE TITLE
[CMS] ページ移動時、定型フォームの"バナー"ブロックのリンクが追従しない

### ISSUE THREAD

**Issue by ShinjiTanimoto** [shirasagi/shirasagi#4369]
1. 定型フォームに"バナー"ブロックを用意する
2. ページ作成時、バナーの URL を設定する
3. ページ移動、フォルダー移動を実行する

**Comment by itowtips** [comment]
"バナー"ブロックというのは無い。

定型フォーム内のリンクは、ページ移動、フォルダー移動で追従することを確認した。
