### ISSUE TITLE
テンプレート機能

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#439]
CKEditor のテンプレート一覧に、ユーザ定義のテンプレートを追加する機能。

**Comment by sunny4381** [comment]
[TinyMCE](http://www.tinymce.com/wiki.php/Plugin:template)にもテンプレート機能がある。
CKEditor と共通化できれば良い。

**Comment by sunny4381** [comment]
## 対象機能

次の機能が対象。

* 記事ページ
* メールマガジンフォルダ
* など

## サイトごとのテンプレート

ページ・ノード毎に利用できるテンプレートを設定できるのは便利そうでいて、逆に運用が面倒になるで、サイト単位でテンプレートを管理する機能を提供する。

## URL 設計

例えば `doc/413.html` を編集しているとき、`doc/413/templates.js` のような URL にアクセスすれば、CKEditor/TimeMCE 用のテンプレートを読み込めるようにしようと思う。
TimeMCE では、さらに 、`doc/413/template1.html` のような URL も必要そう。

**Comment by tany** [comment]
TinyMCE ですね。
標準は CKEditor なので TinyMCE は余裕があればでいいと思います。

**Comment by sunny4381** [comment]
CKEditor のテンプレートに表示するサムネイル画像の既定値は "/assets/img/editor_template.png" で、
config/cms.yml で変更できるようにしました。
