### ISSUE TITLE
jquery.form.js と 'jquery-form-rails' gem について

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#440]
OD で障害発生。

    ０．アプリ登録→
    関連データセット→データセットを選択する。
    データセットを検索
    絶対にある言葉を入れても，エラーが出る。 

原因は、

    マイページ、アプリ登録画面を開いたときに、app/views/opendata/agents/nodes/my_app/_form.html.erb　の11行目でpublic/assets/js/jquery.form.jsを参照しているが、存在しないので「× GET http://ouropendata.jp/assets/js/jquery.form.js」というエラーがでています。
    マイページ、アプリ登録画面の関連データセットから開く、モーダルのデータセット検索画面でデータセットを検索ボタンを押したとき、「× Uncaught TypeError: $(...).ajaxSubmit is not a function」というエラーがでています。
    このエラーはapp/assets/javascripts/opendata/opendata.coffee.erbの227行あたりの「$(this).ajaxSubmit(」で起きています。この「ajaxSubmit」というのがpublic/assets/js/jquery.form.jsに定義しているもののようです。

**Comment by sunny4381** [comment]
see 417784a3

**Comment by tany** [comment]
プロダクト別に、例えば `od/public.js` などの中核ファイルを作って
それを読み込む手もあります。
