### ISSUE TITLE
定型フォームの必須入力が未入力の場合に下書き保存ができない

### ISSUE THREAD

**Issue by tamatips** [shirasagi/shirasagi#4461]
定型フォームで必須入力の項目について、
記事作成時に未入力の状態で下書き保存しようとするとエラーとなってしまうので、
記事を公開・非公開に関係なく保存ができない。
「一部の必須項目について後から入稿されるため現時点では入力できない」といった場合に、
記事の作成すらできないのが現状。

◯改善案
下書き保存時は必須チェックを行わず、必須入力が未入力でも保存ができるようにしてほしい。
公開時のみ、現状同様必須入力項目の入力チェックを行うようにしてほしい。

**Comment by sunny4381** [comment]
必須入力が未入力の場合、次の動作になるように修正する。

- 下書き保存は OK。単なる保存もOK。
- 公開保存はエラー。
- 承認申請はエラー。
- 差し替えページの作成はエラー。
