### ISSUE TITLE
SHIRASAGI 開発マニュアル 逆引きリファレンスにてサムネイルのコードが古いままになっている

### ISSUE THREAD

**Issue by tamatips** [shirasagi/shirasagi#4522]
◯問題点

SHIRASAGI 開発マニュアル 逆引きリファレンス
https://shirasagi.github.io/features/liquid/reverse_reference.html

`#{thumb.src}`
についてのLiquidコードが
`{% assign thumb_src = page.thumb.thumb_url %}`
になっています。
こちらだとぼやけます。

◯改善案
`{% assign thumb_src = page.thumb.url %}`
にすべきとのことですので、修正をお願いいたします。

**Comment by sunny4381** [comment]
修正しています。
