### ISSUE TITLE
[CMS]ループHTML(Liquid 形式)にて連絡先の所属を利用できない 

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#4607]
連絡先欄に設定された「所属」のグループ名を利用したいのですが、表示されません。

[SHIRASAGI 開発マニュアル/Liquid 形式 リファレンス](https://shirasagi.github.io/features/liquid/reference.html)
> page.contact_group | ページに設定された連絡先の所属

カテゴリ/ページリストにて、下記で所属グループの指定をしても何も表示されません。

```
{% for page in pages %}
  {{page.contact_group}}
{% endfor %}

```

変数名が違うのでしょうか。(マニュアルのとおりですが)
group型として`{{page.contact_group.name}}`と書いても表示されません。

### 確認環境
ver. 1.15.0
ver. 1.16.1

**Comment by sunny4381** [comment]
https://github.com/shirasagi/shirasagi/commit/36d0f32cbb966567135f8692d97c3d4369a0da79 で導入された不具合でした。 2021/05/20 に導入されたことから、v1.15.0 より前には存在せず、v1.15.0 以降に存在すると思われます。
