### ISSUE TITLE
[CMS]公開予約による公開時に更新履歴が空欄になる

### ISSUE THREAD

**Issue by tamatips** [shirasagi/shirasagi#4709]
◯問題点
公開予約を設定し、定期実行で自動で公開された場合に更新履歴のユーザー部分が空欄になる。
System jobs some times touch the page and a history is record with null to operation user.
In that case editing history shows blank in operation user.
![スクリーンショット 2022-11-09 21 35 01](https://user-images.githubusercontent.com/87358283/200832173-b869e1e1-e2df-4822-b9d1-9cc7587b732e.png)

◯解決策
下記の表示にする。
・「公開予約設定時」：ユーザー名
・「公開予約による書き出し時」：「公開開始予約による自動公開」「公開終了予約による自動終了」

![スクリーンショット 2022-11-09 21 36 02](https://user-images.githubusercontent.com/87358283/200832201-6faa5c00-5cc0-4a4b-8f52-05aefea8bfaa.png)

**Comment by sunny4381** [comment]
@tamatips 
実行した条件やジョブによる表示分けは難しいので、まずは、固定で "-- システムによる操作 --" のような表示とさせていただければと思います。
