### ISSUE TITLE
SS Migration リカバリ

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#471]
SS Migration に失敗した場合のリカバリ。

例えば、次のコマンドを実行すると、1 件だけ取り消す:

```
rake ss:reset_migration -1
```

例えば、次のコマンドを実行すると、全件取り消す:

```
rake ss:reset_migration -all
```

このようなオプション指定が可能かどうかは要調査。

**Comment by kaosf** [comment]
`rake db:migrate`に合わせる形で`rake ss:migrate`にしている．
`rake db:migrate`に対応する修正コマンドは`rake db:rollback`である．
`rake db:rollback --step 1`のようにいくつ巻き戻すかを指定可能である．省略した場合は`1`とみなされる．

以上より，実装するべきコマンドは`rake ss:rollback --step 1`が良い．

**Comment by kaosf** [comment]
続いての問題で，`SS::MigrationYYYYMMDDHHMMSS`クラスは`change`メソッドを持ち，それを実行するように実装してある．

ここで本来の`rake db:migrate`で用いる`change`メソッドは，その中に自動で巻き戻す方法が明らかであるメソッドしか用いられていない．もしも巻き戻す方法が判別不能な場合は，個別に`up`メソッドと`down`メソッドを実装し，`migrate`時には`up`が，`rollback`時には`down`が実行されるようになっている．

巻き戻しを考えたいと思う場合には，まず`up`と`down`を実装するように修正する必要があると思う．

**Comment by kaosf** [comment]
もしも

```rb
require filepath
"SS::Migration#{timestamp}".constantize.new.change
create version: timestamp
```

という処理のために`change`メソッドで何が起こっても`create version: timestamp`が実行されてしまうことが問題だとしたら，例外を発生させて`create ...`を抑止する，のような対処が考えられる．

**Comment by kaosf** [comment]
rollbackをきちんとするのは無理．

* 冪等になる
* 例外を吐いて死ぬ

を満たすように**気をつけて**作る必要はある．

ただし，`versions`を指定した件数消して，もう一度migrationを行えるようにする，という機能はあっても良い．

なので，

* rollbackコマンドは「rollbackは出来ません」と表示する
* reset_migrationコマンドでversionを指定した件数消す

ということが出来るようにする．

**Comment by tany** [comment]
無しで。

**Comment by kaosf** [comment]
了解です
