### ISSUE TITLE
関連記事の設定モーダル内の検索が動かない

### ISSUE THREAD

**Issue by itowtips** [shirasagi/shirasagi#474]
jquery-form-railsの導入によりajaxのgetができずpostしてしまう

**Comment by itowtips** [comment]
https://github.com/shirasagi/shirasagi/commit/e7e3f5a47cf79cbb3ff748925bba629f25f7f84a
postのrouteを追加

**Comment by tany** [comment]
分ける意味がとくにないなら `match via:` でいいんじゃないでしょうか。

**Comment by itowtips** [comment]
マージしてしまいましたが、上にしておきます。
