### ISSUE TITLE
[CMS] サイトのお問い合わせフォームの公開画面が書き出されない

### ISSUE THREAD

**Issue by itowtips** [shirasagi/shirasagi#4755]
サイト設定＞お問い合わせフォーム に既定のフォームを設定する。
既定のフォームに既に index.html があると、過去の表示が残ってしまう。

**Comment by sunny4381** [comment]
再現手順:

1. お問い合わせフォームを作成する。
2. フォルダー書き出しを実行する。1で作成したフォルダーのindex.htmlが作成される。
3. サイト設定のお問い合わせフォームに1で作成したお問い合わせフォームを設定する。
4. ページ（例: 記事ページ）を作成し、連絡先を表示する設定にし、適切にグループと連動するようにする。
5. 4で作成したページを公開する。
6. 4で作成したページの公開画面にアクセスし、ページに表示されている「お問い合わせフォーム」というリンクをたどる。
7. 2のindex.htmlが表示される。正しい動作であれば、「グループ名」へのお問い合わせのようにタイトルが変わるはず。

※4で設定するグループには、事前に連絡先を作成し、その連絡先を「主」にしておくこと。

**Comment by sunny4381** [comment]
サイト設定＞お問い合わせフォーム に既定のフォームを設定後、次のフォルダー書き出しで正しく動作するようになります。
