### ISSUE TITLE
[GWS]共有ファイルでまとめてダウンロードするときの日本語ファイル名に問題

### ISSUE THREAD

**Issue by nak-srck** [shirasagi/shirasagi#4806]
日本語ファイル名を含んだ複数のファイルを同時にダウンロードしたときのZIPファイルに以下の問題があります。
・日本語ファイル名の拡張子がなくなります。

**Comment by nak-srck** [comment]
デモサイトでデモデータをダウンロードしたときに上記が発生します。
デモサイト上で新規にアップロードしたデータをダウンロードしたものは、拡張子の問題は発生しませんが、Windowsで展開したファイルは文字化けが残ります。

**Comment by sunny4381** [comment]
seedで登録したファイルは、現在はダウンロードできなくなっている。
画面上から登録したファイルは、ダウンロード可能。
