### ISSUE TITLE
[GWS][設備予約][v1.17.0] 設備予約のスケジュール一覧にて表示される設備予約と日時が一致しない現象

### ISSUE THREAD

**Issue by tatsuyasenbom** [shirasagi/shirasagi#4842]
# 現象
1. Google Chrome や Microsoft Edge にて、
    * ![image](https://user-images.githubusercontent.com/87968771/220223864-4982fca3-7a50-4460-992d-54b8f028d909.png)
    * ![image](https://user-images.githubusercontent.com/87968771/220224502-c428e53f-062f-44e4-8b01-541889b3e37e.png)
2. `2023/02/24`で作成した設備予約が、
    * ![image](https://user-images.githubusercontent.com/87968771/220223815-5ef1bf51-302d-426d-9c9d-acde9ff241f6.png)
3. `2023/02/21`の一覧として表示されることと、
    * ![image](https://user-images.githubusercontent.com/87968771/220223353-6981b850-05b3-45f1-9814-e4822340dadb.png)
4. 上記3の設備予約をクリックすると、上記2で作成した設備予約の詳細画面へ遷移することを確認しました。
5. ページやリロードしたり、画面遷移を繰り返すと、上記1～4の症状が見られなくなること、及び、どうやら設備の`カテゴリー`切替のセレクトボックスの値を切り替え後に、上記1～4現象が再現するように思えます。
    * ![image](https://user-images.githubusercontent.com/87968771/220224541-713de494-7379-4986-aba7-347742cc2a10.png)

**Comment by tatsuyasenbom** [comment]
本日、デモサイトにて上記で報告させていただいた操作とは、異なる操作で同じ現象が発生することを確認しました。

* https://demo.ss-proj.org/.g15/schedule/facilities?calendar%5Bdate%5D=2023-02-28&calendar%5Bview%5D=timelineDay&calendar%5BviewAttendance%5D=inactive&calendar%5BviewFormat%5D=default&calendar%5BviewTodo%5D=inactive

# 現象を再現するための操作
1. `グループ > スケジュール > 設備予約`にて`設備予約 会議室101 2023/02/27 15:00 - 16:00`を作成
2. `グループ > スケジュール > 設備予約`の`2023年2月27日（月）`の一覧に上記1の設備予約が表示されていることを確認
3. 上記2の設備予約をクリックし日付を`2023/02/27`から`2023/02/28`へと編集し保存
    * ![image](https://user-images.githubusercontent.com/87968771/221457284-bbccf049-db0a-4b22-b594-5728b72c063e.png)
5. `グループ > スケジュール > 設備予約`の`2023年2月27日（月）`上に、上記3の設備予約が表示されていることを確認
    * ![image](https://user-images.githubusercontent.com/87968771/221456729-d580e51b-7e69-4a74-8a0e-bd9437286358.png)
6. タブを`2023年2月28日（火）`に切り替えるも上記3で日付を変更した設備予約が表示されていないことを確認
    * ![image](https://user-images.githubusercontent.com/87968771/221457212-ec1152f6-82c2-48b8-b302-e3556caf5e50.png)

**Comment by sunny4381** [comment]
#5089 で修正しました。修正は v1.18.2 でリリース済みで、現在のデモサイトでは再現しなくなっています。

**Comment by tatsuyasenbom** [comment]
ご連絡いただきありがとうございます。
本現象について、解決している事を v1.18.2 で確認しました。
