### ISSUE TITLE
【CMS】サイトマップに表示される固定ページタイトルについて

### ISSUE THREAD

**Issue by horiuchioioi** [shirasagi/shirasagi#4861]
リダイレクトURLを持った固定ページをサイトマップ表示した場合、固定ページのタイトル名で表示されません。

固定ページAへリダイレクトする固定ページBをサイトマップに表示させた場合、
固定ページBのタイトル名ではなく固定ページAのパス（URL）が表示されるのようになる。
固定ページBのタイトル名（もしくはタイトル一覧名）が表示されるべきかと思うのですが、
ご確認をよろしくお願いします。

**Comment by sunny4381** [comment]
いくつか条件を変えながら試してみましたが、現在は再現しないようです。
