### ISSUE TITLE
Please update bundler

### ISSUE THREAD

**Issue by tany** [shirasagi/shirasagi#489]
Add "BUNDLED_WITH" specification to Gemfile.lock #487

**Comment by itowtips** [comment]
Gemfile.lockに書いてあるバージョンと全くおなじバージョンでbundle installしないと
差分ができてしまい、git pullできなくなるので注意です。

ローカルでbunlderを更新してみたら、
bundlerが1.10.2から1.10.3になったようで、
この状態でbundle installすると差分ができてしまいました。

1.10.xでこのGemfile.lockに差分ができてしまうと
git checkout Gemfile.lock や手動でGemfile.lockを書き換えても
勝手にもどされてしまい、Gemfile.lockが常にmodifiedになるので
pullできなくなります。

https://github.com/bundler/bundler/issues/3697

**Comment by kaosf** [comment]
結構炎上してる感じのそのIssueを頑張って読んでみましたら，Ownerが折れて(というか「もうこれでいいだろフリーソフトウェアに何をそんなに文句つけてるんだ」って感じで投げやりに)1.10.3に更新して，それ以降はもしも

```
BUNDLED_WITH
   1.10.4
```

とか書かれてた場合でも警告だけを出すようにした(Gemfile.lockが書き換わったりはしない)，とのことです．

で，GitHub上でもTwitter上でも色んな意見もらったし，バージョン2.0出すときにはもっとちゃんと考えるから，もうこれでこのIssueおしまいな，と言ってコメント制限掛けられてしまったようです．

なので，Bundler 1.10.3に上げておけば，これ以上悩まなくても大丈夫かと思います．

**Comment by kaosf** [comment]
あ，それで実際に Gemfile.lockにBUNDLED_WITH 1.10.4とかBUNDLED_WITH 1.11.0とか書いてから`bundle install`してみると，警告が出るだけでGemfile.lock自体は書き換わりませんでした．

**Comment by kaosf** [comment]
すみません問題の本質を勘違いしてました．

これ，Bundlerをインストールするときにバージョンを指定する以外方法が無いですね．勝手に新しいのになっちゃうと，Gemfile.lockがどうしても勝手に書き換わってしまいますね．

ただ上述の通り，Gemfile.lockに指定されたものより古いBundlerを使う限りは問題が無いので，インストールマニュアルにあるコマンドを以下のように変更しておけば良いと思います．

```diff
- gem install bundler
+ gem install bundler -v 1.10.3
```

※もうこの際なので1.10.3には追従する．

※PR #496 にこの変更の追加コミットをしておきました．

**Comment by kaosf** [comment]
そのIssueでも少し言及されてましたが，もしどうしても1.9系のBundlerを使わなければならない，という場合には，複数のバージョンのBundlerがインストールされている状態でも，

```sh
gem list | grep bundler #=> bundler (1.10.3, 1.9.9)

bundle version #=> 1.10.3
bundle _1.9.9_ version #=> 1.9.9
```

のように`_1.9.9_`をコマンドに付随させれば特定バージョンのBundlerを使うことが出来るんですね(そういやそんな仕様あったなぁ…レベルでした)(この仕様，どこに記載されてたか覚えてないし，今見つけられない)．

**Comment by itowtips** [comment]
>結構炎上してる感じのそのIssueを頑張って読んでみましたら
最後まで把握できなかったので助かりました。

>Bundler 1.10.3に上げておけば
とりあえず、次のコミットは早く入れておいた方がよさそうなのでマージしようと思います。
https://github.com/kaosf/shirasagi/commit/4ddf80e902de536424da63b309a538615270a4bc

PR含め、コメントありがとうございました。
