### ISSUE TITLE
管理画面サイト内記事検索機能

### ISSUE THREAD

**Issue by itowtips** [shirasagi/shirasagi#492]
サイト内ページの検索機能を作成する

**Comment by itowtips** [comment]
https://github.com/itowtips/shirasagi/commit/f8b731618e69e291f280c809bb742a9ceb435ac2
サイト内検索 > ページ検索
を作成

以下の項目を設定し検索が可能
* タイトル
* ファイル名
* カテゴリー
* 管理グループ
* 公開日時
* 更新日時
* ステータス（公開、非公開）

**Comment by sunny4381** [comment]
要望 3 点。

* デモサイトで、記事がどのフォルダーにあるのか調べるためにサイト内検索を利用しましたが、name が検索対象ではないため、ヒットしませんでした。name を検索対象に加えてください。
* event ページの content, venue, contact が検索対象外のため、イベント情報がヒットしません。これらを検索対象に加えてください。
* opendata からの要望で、アイデアの text、comment を検索対象としたいです。検索対象を設定ファイルで変更できるようになりませんか？

**Comment by itowtips** [comment]
サイト内検索は二つあります。
1.HTMLの検索と置換
→ #250
2.サイト内のページ検索
→　このissue、まだマージしていません

> デモサイトで、記事がどのフォルダーにあるのか調べるためにサイト内検索を利用しましたが、name が
> 検索対象ではないため、ヒットしませんでした。name を検索対象に加えてください。

こちらは２の方をマージして使ってもらえたらと思います。

**Comment by itowtips** [comment]
上記要望は別issueへ #513
