### ISSUE TITLE
【CMS】印刷パーツ・クリップボードへコピーパーツについて

### ISSUE THREAD

**Issue by horiuchioioi** [shirasagi/shirasagi#4926]
印刷パーツ・クリップボードへコピーパーツは現状「パーツ名」がボタンのテキスト部分として出力されているかと思いますが、「パーツ名」とボタンのテキスト部分を別々のテキストにしたい場合に不便です。
できれば別枠で設定できるようにして欲しいです。
またアップローダーに上げている画像のパスを入力するなどし、アイコンなども設定できるようになれば嬉しいです。

**Comment by sunny4381** [comment]
現状は、別々のテキストにしたい場合はJSで動的に書き換え、アップローダーに上げている画像を利用したい場合は CSS で調整で可能かなと思います。

**Comment by horiuchioioi** [comment]
印刷パーツ・クリップボードへコピーパーツに限らずですが、
例えばお問い合わせフォームの「確認画面へ」など、すでにリンクボタンの文言が決まったものが他機能にもあります。
その場合、おっしゃる通りJSで書き換えるのがよろしいかと思うのですが、
翻訳機能などを使用すると翻訳した英語の上からJSで指定した文言で書き換えてしまうこともあります。
また、お客様によっては「確認画面へ進む」などのわかりやすい文言に変えていきたいなどあるのですが、
それらを全てJSで賄うとサイトのパフォーマンスにも関わるので、
個別で設定できればという背景があります。
（今回の件はパーツ名とは別枠にしてほしいとのことなので、少しニュアンスが異なりますが）

画像の件は某チャットbotアプリに、管理者ユーザー（構築者とは別）が気軽にチャットbotのアイコン部分を変更できる機能があり、シラサギもフォルダの詳細画面から簡単に設定できれば使いやすいのかなと思っただけなので、優先度はかなり低いです。

どちらも優先度が低いということでしたら、それでも構いません。
