### ISSUE TITLE
【CMS】記事の「関連記事」について

### ISSUE THREAD

**Issue by horiuchioioi** [shirasagi/shirasagi#4928]
記事作成時に「関連記事」を設定し、リンクを貼れると思うのですが、複数テナントがある組織の場合、テナントを跨いだ選択ができないので不便です。
提携サイトにされているテナントに限り、関連記事の選択項目に表示することができるようにしていただけないでしょうか
記事のフォルダー設定で関連記事に出すサイトを切り替えもできればなお良いと思います。

**Comment by sunny4381** [comment]
提携サイトをタブで表示し、他サイトの記事を選択できるようにする。

![image](https://github.com/shirasagi/shirasagi/assets/3593466/64b3982c-a5c2-459e-85dc-94bedff2fd2b)

他、非公開時のリンクチェックをマルチテナント対応にする必要あり。
