### ISSUE TITLE
Potential vulnerability - Private reporting 

### ISSUE THREAD

**Issue by Sim4n6** [shirasagi/shirasagi#4938]
Hi, I may have identified a security vulnerability in your codebase. I would like to report it in private please.

Could you please consider enabling [private vulnerability reporting for this repository](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository).

Thank you in advance
@Sim4n6

**Comment by sunny4381** [comment]
@Sim4n6 
Sorry for our late acknowledgement.

We enabled "Private vulnerability reporting".
So, would you mind reporting a security vulnerability.

**Comment by Sim4n6** [comment]
Thank you, it is nothing fancy , I will write the report today...

**Comment by Sim4n6** [comment]
Hi @sunny4381 

The report of a low-severity vulnerability is submitted [here](https://github.com/shirasagi/shirasagi/security/advisories/GHSA-xr45-c2jv-2v9r). 

Please keep me posted.
Regards
@Sim4n6

**Comment by Sim4n6** [comment]
Hi @sunny4381, any update about the private security report, please?

**Comment by Sim4n6** [comment]
Perfect, it is done. Thank you
