### ISSUE TITLE
[CMS] 更新履歴の「変更前の状態と比較」で変更箇所が一部しか表示されない

### ISSUE THREAD

**Issue by tamatips** [shirasagi/shirasagi#4958]
◯問題点
記事一覧画面の更新履歴欄の「変更前の状態と比較」ボタンをクリックした際に、
記事編集時の変更箇所が全て表示されない。
（ブロック入力記事の場合）

・変更箇所
各項目の末尾に「２」を追加

![スクリーンショット 2023-07-05 15 12 50](https://github.com/shirasagi/shirasagi/assets/87358283/2ac999b4-589d-4aba-8570-d83907de2d7c)

・「変更前の状態と比較」ボタンをクリックした画面

![スクリーンショット 2023-07-05 15 13 18](https://github.com/shirasagi/shirasagi/assets/87358283/bbc5de84-b4e0-42b9-8c36-374b56dd663a)

◯解決策
下記のように全ての変更箇所が表示される

<img width="845" alt="スクリーンショット 2023-07-05 15 24 13" src="https://github.com/shirasagi/shirasagi/assets/87358283/e2340955-ca8b-435e-ae14-485e6fcee9be">

**Comment by itowtips** [comment]
修正PR https://github.com/shirasagi/shirasagi/pull/5001

経緯としては、履歴表示機能の後から定型フォーム機能を追加しており、元々考慮できていなかった為です。
その後、固定の定型フォームには対応しましたが、ブロック入力型の方は、項目が都度変わるため対応できていませんでした。（上記のように先頭の項目のみ表示される）

改善
- 定型フォームの部分を2カラムにして、項目全て表示するようにしました。
- 途中項目が変わったとしても、単純にテキスト比較するようにしました。
- 黄色のセルは変更した箇所を表示していますが、後から差分表示を足したため、わかりづらくなっています。
  -  そもそも変更された箇所しか表示されないようなので、黄色表示はやめて、全て差分表示にしてみました。
  -  ただし、数値データの差分表示はあまり綺麗には表示されません。（変更箇所がわかれば良いといった程度です）
