### ISSUE TITLE
[CMS] 定型フォームの初期ブロックに設定されている項目を削除するとエラー

### ISSUE THREAD

**Issue by ShinjiTanimoto** [shirasagi/shirasagi#5112]
1. 定型フォームをブロック入力で作成する
2. 適当な項目を作成する
3. 項目を初期ブロックに追加する
4. 項目を削除する
5. 定型フォームの使用時などにエラーが発生する

**Comment by sunny4381** [comment]
This issue is fixed at #5113

**Comment by sunny4381** [comment]
v1.18.2で修正済み
