### ISSUE TITLE
[CMS] アクセシビリティツールを複数設置すると動かない

### ISSUE THREAD

**Issue by tamatips** [shirasagi/shirasagi#5115]
◯事象
デザイン的にPC画面とSP画面で１つのアクセシビリティツールを共有するのが難しい場合に、
PC用とSP用で別にアクセシビリティツールを設置したところ動かなかった

現状`#ss-theme`や`#ss-medium`、`#ss-large`、`#ss-small`などのid指定になっているものについて処理をしているとのこと。

基本的に同じidはページ内に１つしか使えないため、id指定では複数設置できない。

◯解決策
`.ss-theme`や`.ss-medium`、`.ss-large`、`.ss-small`などクラス名指定を許容する。
複数設置できるなら他の解決策でも構いません。

**Comment by sunny4381** [comment]
This issue is fixed in #5256
