### ISSUE TITLE
[CMS]記事フォルダ　公開終了間近ページの改善要望

### ISSUE THREAD

**Issue by horiuchioioi** [shirasagi/shirasagi#5119]
記事フォルダ＞公開終了間近のリストページにて、一覧で公開終了予定日時を確認したいです。
検討をよろしくお願いいたします。

例
<img width="1098" alt="スクリーンショット 2023-11-29 10 21 41" src="https://github.com/shirasagi/shirasagi/assets/114460682/d3b36435-8b54-47b3-97c6-1679297731d8">

**Comment by yujiplusw** [comment]
`公開終了日:YYYY/MM/DD hh:mm
`

**Comment by sunny4381** [comment]
HTML Coding will be 

~~~
<span class="close_date">公開終了日: <%= ss_time_tag item.close_date %></span>
~~~
