### ISSUE TITLE
【CMS】広告管理のリンク方法を個別に設定したい

### ISSUE THREAD

**Issue by horiuchioioi** [shirasagi/shirasagi#5152]
現状「広告管理」のリンク方法は広告バナーパーツから「同タブ」「別タブ」の一括設定しかできなくなっていますが、
リンク方法を個別に設定できるようにしていただきたいです。

【提案】
バナー登録時に、同じタブ、別タブを個別で選択できるようにし、
パーツで「同じタブで表示」「別タブで表示」「個別設定」で選べる運用。

パーツは初期設定は「個別設定」にしておき、バナーで個別に登録できる部分のツールチップに
「広告バナーパーツが「個別設定」になっている場合に適用されます」などの文言があればわかりやすいと思います。

**Comment by sunny4381** [comment]
In the Shirasagi demo site, part "広告バナー" is located under folder "ad", and banner whose type is page is also located under folder "ad".

- folder "ad": https://demo.ss-proj.org/.s1/ads172/banners
- part "広告バナー": https://demo.ss-proj.org/.s1/cms172/parts/40
- banner:
  - https://demo.ss-proj.org/.s1/ads172/banners/59
  - https://demo.ss-proj.org/.s1/ads172/banners/60
  - https://demo.ss-proj.org/.s1/ads172/banners/61
  - https://demo.ss-proj.org/.s1/ads172/banners/62
  - https://demo.ss-proj.org/.s1/ads172/banners/63
  - https://demo.ss-proj.org/.s1/ads172/banners/64

【提案】
バナー登録時に、同じタブ、別タブを個別で選択できるようにし、

![image](https://github.com/shirasagi/shirasagi/assets/3593466/bdceb525-0464-49ac-a6d5-382065b02d80)

パーツで「同じタブで表示」「別タブで表示」「個別設定」で選べる運用。

![image](https://github.com/shirasagi/shirasagi/assets/3593466/855f9a6a-af01-4576-aee7-579dcf8836d6)

![image](https://github.com/shirasagi/shirasagi/assets/3593466/41216ff1-d083-42e1-ad9e-be89bd2a5511)

**Comment by sunny4381** [comment]
controller and view file of part "広告バナー"

- controller: https://github.com/shirasagi/shirasagi/blob/master/app/controllers/ads/agents/parts/banner_controller.rb
- view: https://github.com/shirasagi/shirasagi/blob/master/app/views/ads/agents/parts/banner/index.erb
