### ISSUE TITLE
[CMS]記事の詳細画面と一覧画面で、差し替え元ページ記事削除可否が異なる

### ISSUE THREAD

**Issue by tamatips** [shirasagi/shirasagi#5195]
◯問題点
差し替えページがある場合に差し替え元ページの方の記事を削除する場合、
記事の詳細画面から削除しようとすると削除できないようになっているが、
記事一覧画面にてチェックボックスにチェックを入れると特にアラートが表示されるわけでもなく削除できてしまい、
挙動が一貫していない。
こちらについては削除不可、あるいはアラート表示を必ず表示させるか、統一していただけますでしょうか。

◯解決策
記事の詳細画面、一覧画面で動作を統一する。

**Comment by sunny4381** [comment]
削除対象の確認画面を次のように修正する。
Modify the confirmation screen for the deletion target as follows.

![image](https://github.com/shirasagi/shirasagi/assets/3593466/51594189-701b-4c05-9d95-2363166d7dee)

- 「削除」ボタンは表示する。 / The "Delete" button shall be displayed.
- 「差し替えページが作成されているため削除できません。」という情報・エラーを表示する。 / Display information/error "差し替えページが作成されているため削除できません。"
- 図のように当該ページのチェックボックスを disabled にするか、チェックボックスそのものを非表示とする。 / As shown in the figure, disable the checkboxes on the page. Or hide the checkboxes themselves.
