### ISSUE TITLE
メールフォームの画像認証への全角数字入力対策

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#5240]
メールフォームの確認画面での画像認証の入力にて、半角数字でなく、全角数字を入れるとエラーになります。

![スクリーンショット 2024-05-17 10 02 13](https://github.com/shirasagi/shirasagi/assets/50577719/9d4cbc85-7d69-41b4-be26-db45bb2ea48a)

この件で、利用者からお問合せを受けました。
注意文にも半角でという記載がないため、全角入力をしてしまい、
何度送ってもエラーで送れないという現象になったそうです。

エラー通知も「画像の数字が正しくありません」となり、
画像認証は新しいものになり、前の入力が残らないので余計に気づきにくい様です。

# 調整要望
公開サイトの利用者へ半角数字を求めていることを、わかりやすい様にしていただきたいです。

送付時かチェック時に数字を半角に自動置換するか、半角数字でという注意書きを入れる。
あるいは、エラー通知にて全角であったことの指摘をするなど、

ご検討願います。

**Comment by sunny4381** [comment]
修正方法

1. inputタグを変更する（pattern と inputmode を併用）

~~~html
<input title="半角数字4桁でご入力ください。" pattern="\d{4}" inputmode="numeric" type="text">
~~~

2. 説明テキストを変更する

~~~
画像の数字を入力してください
~~~

　↓

~~~
画像の数字を半角で入力してください
~~~
