### ISSUE TITLE
 イベント検索フォームのアクセシビリティ対応不足

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/shirasagi#5269]
### イベント検索
https://demo.ss-proj.org/calendar/
https://demo.ss-proj.org/calendar/search/

対応するlabel要素のないinput要素がある為、アクセシビリティのチェックツールなどでエラーとなります。

「キーワード」と「施設」の入力欄=inputに、対応label要素またはtitle属性がない。
```
 <form class="event-search" action="/calendar/search/" accept-charset="UTF-8" method="get">
   <fieldset class="keyword">
   <legend>キーワード</legend>
   <input type="text" name="search_keyword" id="search_keyword" />
   </fieldset>
  /*中略*/  

<fieldset class="event-date-range">
   <legend>開催期間</legend>
   <div class="dates location">
   <input type="text" name="event[][start_date]" class="start date js-date" title="開始" />
   - <input type="text" name="event[][close_date]" class="close date js-date" title="終了" />
   </div>
   </fieldset>
    
   <fieldset class="event-facility">
   <legend>施設</legend>
   <input type="text" name="facility_name" id="facility_name" />
   </fieldset>
```

「開催期間」の開始と終了は、代替的にtitle属性がある。

#### 関連

[イベント/イベント検索フォームのアクセシビリティ対応 #3443](https://github.com/shirasagi/shirasagi/issues/3443)

上記にて、fieldsetとlegendの対応はされていたようですが、
同時に施設について下記の指摘が見過ごされたか、対応巻き戻っているのではないでしょうか?

> legend 要素はありますが、`<input type="text" name="facility_name" id="facility_name">`に対応するlabel要素がありません。
> フォーム・コントロールにlabel要素およびtitle属性が関連付けられていません。

####  解説
 
ラベル又は説明:達成基準 3.3.2 を理解する
https://waic.jp/docs/UNDERSTANDING-WCAG20/minimize-error-cues.html

H44: テキストラベルとフォームコントロールを関連付けるために、label 要素を使用する
https://waic.jp/docs/WCAG-TECHS/H44.html

H65: label 要素を使用できない場合に、フォームコントロールを特定するために、title 属性を使用する
https://waic.jp/docs/WCAG-TECHS/H65.html

**Comment by sunny4381** [comment]
#5295 で修正されました。修正は次期バージョンでリリースされます。
