### ISSUE TITLE
[CMS] 非公開権限がない場合に、一覧ページにて非公開ができてしまう

### ISSUE THREAD

**Issue by tamatips** [shirasagi/shirasagi#5293]
非公開権限がない場合に、詳細ページでは非公開にできないものの、一覧ページでは非公開ができてしまうこと

◯問題点
非公開権限がない場合に、記事の詳細画面から非公開にしようとするとできないようになっているが、
記事一覧画面にてチェックボックスにチェックを入れて「非公開にする」ボタンを押下すると非公開確認画面が出るが、
削除できてしまい、挙動が一貫していない。

下記Issueと類似している問題と思います。
https://github.com/shirasagi/shirasagi/issues/5195

◯解決策
記事の詳細画面、一覧画面で動作を統一する。

**Comment by sunny4381** [comment]
修正案 / Proposal:

1. copy "app/views/cms/crud/_list_head.html.erb" to "app/views/cms/pages/_list_head.html.erb". To make bulk publish and bulk close exclusive to the pages.
2. remove "公開" and "非公開" from "app/views/cms/crud/_list_head.html.erb".
3. create "publish_all" and "close_all" action to specific controllers.
4. call "publish_all" on clicking "公開" button on "app/views/cms/pages/_list_head.html.erb" and also call "close_all" on clicking "非公開" button on "app/views/cms/pages/_list_head.html.erb".
5. In action "publish_all" and/or "close_all", do appropriate authority checks and properly show errors.
