### ISSUE TITLE
【CMS】記事/定型エクスポートのCSV、jsonの項目追加

### ISSUE THREAD

**Issue by horiuchioioi** [shirasagi/shirasagi#5298]
記事/定型エクスポートで作成されるCSV、jsonに取得した記事のURLを出力していただきたいです。

[hinanjo.json](https://github.com/user-attachments/files/16051802/hinanjo.json)
[hinanjo.csv](https://github.com/user-attachments/files/16051803/hinanjo.csv)

**Comment by sunny4381** [comment]
@horiuchioioi 「記事/定型エクスポート」とな何でしょう？
すみませんが、管理画面の URL など示すことは可能でしょうか？

**Comment by horiuchioioi** [comment]
@sunny4381 
デモサイトにこの機能を使ったデモがないのでURLはご提示不可です。
フォルダーの機能になります。
![スクリーンショット 2024-11-06 10 36 49](https://github.com/user-attachments/assets/0a5ced75-53f9-4a17-92da-82dfa3c1f556)
