### ISSUE TITLE
[CMS] 定型フォームの日付入力を使用している記事の「変更前の状態と比較」押下で500エラー

### ISSUE THREAD

**Issue by tamatips** [shirasagi/shirasagi#5302]
◯問題点
デモサイトにて、下記手順A、B 、Cでいずれも500エラーになります。

A１）新規で定型フォームを作成し、”日付入力”の項目を作成しておく
A２）記事の定型フォームにA１の定型フォームを指定して”日付入力”の項目を入力して公開保存
A３）記事詳細画面にて、「変更前の状態と比較」押下で500エラーになる
A４）記事を編集して公開保存し、再度記事詳細画面にて、「変更前の状態と比較」押下で500エラーになる

B１）新規でブロック入力を作成し、”日付入力”の項目を作成しておく
B２）記事の定型フォームにB１のブロック入力を指定して”日付入力”の項目を入力して公開保存
B３）記事詳細画面にて、「変更前の状態と比較」押下で500エラーになる
B４）記事を編集して公開保存し、再度記事詳細画面にて、「変更前の状態と比較」押下で500エラーになる

C１）定型フォームを使用している記事を用意しておく
C２）C１の記事の定型フォームに”日付入力”の項目を追加
C３）C１の記事を編集して日付入力の項目を入力して公開保存
C４）記事詳細画面にて、「変更前の状態と比較」押下で500エラーになる

◯期待する結果
上記の各パターンで「変更前の状態と比較」押下でエラーにならない。
（通常の記事、すなわち日付入力を使用しないときの動作に揃える）

**Comment by sunny4381** [comment]
@tamatips 最新版では修正済みかも。

**Comment by sunny4381** [comment]
@tamatips 
#5001 で（おそらく）修正済み。
