### ISSUE TITLE
【CMS】キービジュアルにテキスト（タイトル・説明など）を出力する機能が欲しい

### ISSUE THREAD

**Issue by horiuchioioi** [shirasagi/shirasagi#5313]
キービジュアルの画像に公開画面で設定したテキストを表示させたいです。

説明テキスト（HTML対応）の項目を新たに追加。
タイトルか説明テキスト、またはその両方を表示できるように「表示」の項目で調整

<img width="852" alt="スクリーンショット 2024-02-07 11 52 58" src="https://github.com/user-attachments/assets/af1011be-a5b6-4cf8-9713-689b2bb23465">

例
相模原市
https://www.city.sagamihara.kanagawa.jp/
大阪市
https://www.city.osaka.lg.jp/

**Comment by itowtips** [comment]
これは対応中です。

**Comment by itowtips** [comment]
https://github.com/shirasagi/shirasagi/pull/5316 にて対応済み
