### ISSUE TITLE
Ruby on Rails 4.2.2

### ISSUE THREAD

**Issue by kaosf** [shirasagi/shirasagi#536]
ref. http://weblog.rubyonrails.org/2015/6/16/Rails-3-2-22-4-1-11-and-4-2-2-have-been-released-and-more/

特殊なXMLでDoS攻撃を引き起こす可能性が修正されています．RSSリーダ機能が関係しているかも？

Hashのインスタンスに対して`.to_json`を行うとき，適切なエスケープが行われていなかった点が修正されています．もしもそのハッシュの内容にユーザの入力によって提供されるものがあり，それがHTMLに出力されていたら危険だということでした．と言ってもShirasagi内に該当してそうな箇所はありませんでした．

**Comment by tany** [comment]
Updated.

**Comment by kaosf** [comment]
thx :+1:
