### ISSUE TITLE
[CMS]サイト複製で複製したサイトの記事に付与されていたカテゴリーが外れている

### ISSUE THREAD

**Issue by tamatips** [shirasagi/shirasagi#5386]
◯問題点
１）v1.19.0αリリースのシラサギにて、システム設定からサイト複製する際に「複製する項目」欄の「記事、その他ページ」にチェックを入れてサイト複製を実行
２）複製されたサイトに記事は複製されていたが、カテゴリーが付与されていなかったため、該当カテゴリーの記事一覧を表示する箇所に記事が表示されていなかった

◯改善案
複製したサイトに移行された記事のカテゴリーについては、
複製元サイトの同記事と同じカテゴリーを保持してほしい

**Comment by itowtips** [comment]
#5383
