### ISSUE TITLE
例えば「（あ)」でグループを検索すると 500 Internal Server Error

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#552]
http://demo.ss-proj.org/.demo/cms/groups?utf8=%E2%9C%93&s%5Bkeyword%5D=%EF%BC%88%E3%81%82%29

**Comment by sunny4381** [comment]
## 正規表現の `\Q`、`\E` は Ruby ではサポートされていない疑惑

検索は、内部では `/\Q#{w}\E/i` という正規表現でデータベースを検索することで実現している。

ここで、[Ruby のリファレンスマニュアル](http://docs.ruby-lang.org/ja/2.2.0/doc/spec=2fregexp.html) をみても `\Q` と `\E` に関する記述は見つからない。
Perl の正規表現では、`\Q` と `\E` に関する記述が容易にいくつも見つかる。

[鬼車の公式文書](http://www.geocities.jp/kosako3/oniguruma/doc/RE.txt)によると、`\Q` と `\E` のサポートは、Perl と Java のみのように読める。


Rails Console では、次のようになる。

```ruby
> w = ""
=> ""
> /\Q#{w}\E/i =~ "Q#{w}E"
=> 0
```

```ruby
> w = "abc"
=> "abc"
> /\Q#{w}\E/i =~ "Q#{w}E"
=> 0
```

`\Q` と `\E` が Ruby でサポートされているかどうか、詳しい人、教えて下さい。

**Comment by sunny4381** [comment]
## MongoDB でも `\Q`、`\E` がサポートされていない疑惑

### 事例1

```
> db.cms_pages.count();
233
> db.cms_pages.find({filename: /\Q\E/}).count();
233
> db.cms_pages.find({filename: /\Q/}).count();
233
> db.cms_pages.find({filename: /\E/}).count();
233
> db.cms_pages.find({filename: /\P/}).count();
0
> db.cms_pages.find({filename: /\C/}).count();
233
> db.cms_pages.find({filename: /\N/}).count();
233
> db.cms_pages.find({filename: /\A/}).count();
233
```

\P を検索した際になぜ 0 になるかは不明。

### 事例2

```
> db.cms_pages.find({filename: /23.html/}).count();
3
> db.cms_pages.find({filename: /\Q23.html/}).count();
3
> db.cms_pages.find({filename: /\Q23.html\E/}).count();
3
> db.cms_pages.find({filename: /23.html\E/}).count();
3
```

### 事例3

```
> db.cms_pages.find({filename: /\Q|\E/}).count();
0
> db.cms_pages.find({filename: /\Q(\E/}).count();
...    → なぜか継続行になる。
> db.cms_pages.find({filename: /\Q)\E/}).count();
2015-06-25T16:18:39.137+0900 SyntaxError: Invalid regular expression: /\Q)\E/: Unmatched ')'
```

`\Q` と `\E` で挟み込んでも、メタ文字はエスケープされないっぽい。

**Comment by sunny4381** [comment]
## 予想

Ruby Side:
`w = "abc"` のとき、`/\Q#{w}\E/i` は `/\Qabc\E/i` にコンパイルされ、`/\Qabc\E/i` をMongoDB に送る。

MongoDB Side:
MongoDB では `\Q`、`\E` が未知のエスケープシーケンスのため無視され、単に `abc` が検索される。

**Comment by tany** [comment]
Mongoid がやってくれているのでは？
`?*` などのメタ文字で正常に文字列検索してくてれいるようにみえます。

**Comment by sunny4381** [comment]
スラッシュは既定でエスケープされるようなので、ソースコード中、スラッシュしか入ってきそうにない場合はそのままとした。

```ruby
[1] pry(main)> w = "a/b"
=> "a/b"
[2] pry(main)> /#{w}/
=> /a\/b/
```

スラッシュ以外のメタ文字はNG。エスケープしないと行けない。

```ruby
[3] pry(main)> w = "a|b"
=> "a|b"
[4] pry(main)> /#{w}/
=> /a|b/
```

=> "a" または "b" を検索してしまう。

```ruby
[5] pry(main)> w = "a(b"
=> "a(b"
[6] pry(main)> /#{w}/
RegexpError: end pattern with unmatched parenthesis: /a(b/
from (pry):6:in `<main>'

[7] pry(main)> w = "a)b"
=> "a)b"
[8] pry(main)> /#{w}/
RegexpError: unmatched close parenthesis: /a)b/
from (pry):8:in `<main>'
```

=> Internal Server Error が出てしまう。

```ruby
[10] pry(main)> w = "a.b"
=> "a.b"
[11] pry(main)> /#{w}/
=> /a.b/
```

=> 拡張子 "b" を持つドキュメントを検索できるが、"b" の直前がピリオド以外のドキュメントも検索してしまう。

スラッシュ外のメタ文字が入ってきそうな箇所を網羅的に対策し、プリリクを送付。

**Comment by sunny4381** [comment]
## MongoDB 追試

```
> db.cms_pages.find({name: /\Q.\E/}).count();
1
> db.cms_pages.find({name: /./}).count();
233
```

=> `\Q` と `\E` でピリオドを挟むと、エスケープされてそう。

```
> db.cms_pages.find({name: /\Q*\E/}).count();
0
> db.cms_pages.find({name: /*/}).count();
2015-06-25T18:09:15.134+0900 SyntaxError: Unexpected token ILLEGAL
```

=> アスタリスクもエスケープされてそう。

```
> db.cms_pages.find({name: /\Q(\E/}).count();
... 
> db.cms_pages.find({name: /\Q)\E/}).count();
2015-06-25T18:09:29.764+0900 SyntaxError: Invalid regular expression: /\Q)\E/: Unmatched ')'
```

=> 開き括弧、閉じ括弧はダメ。開き括弧は、なぜか継続行になり、閉じ括弧は Syntax Error となる。
