### ISSUE TITLE
添付ファイルのstateに関する問題

### ISSUE THREAD

**Issue by itowtips** [shirasagi/shirasagi#564]
SS::Model::File の state の default が closed になった
(Fs::FilesControllerはstateで制限するようになった）
ため以下の問題を把握しています。

1. 新規添付ファイルをアップロードし記事を保存する前に添付貼付すると500
    (まだファイルがpublicになっていない為FilesControllerの検索が失敗する)
2. 記事を下書き保存にしたが、添付ファイルはpublicのまま

**Comment by tany** [comment]
temp の保存時、temp への複製時に public を設定しました。
