### ISSUE TITLE
文字列フィールドの strip と、blank フィールドの remove

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#615]
仕様案:

* 文字列フィールドを strip し、グループ名やユーザー名に余分なスペースが入力されていても自動的に取り除く。
  * ただし、html フィールドや text フィールドのような複数行フィールドは strip しない。
* `SS::Model::User` の `email` フィールドなどの一部のフィールドで、""（空文字列） を保存すると、インデックス重複エラーになるので、blank の場合 remove する。
  * ただし、`default: []` のような指定で、既定値として blank を与えている場合がある。この場合は、remove しない。

`SS::Model::User` の `email`, `uid` フィールドや、`Cms::Model::Member` の `email` フィールドでやっているような処理の共通化。

**Comment by sunny4381** [comment]
プルリクを送りました。内容は次のようになっています。

文字列の strip:

* 文字列の長さが 2 以上の場合 strip します。
* フィールド名に "html", "text" を含む場合は strip しません。
* `metadata: { normalize: false }` が設定されたフィールドも strip しません。

blank フィールドの remove

* データ型に関係なく blank であれば remove します。
* `default: []` や `default: -> { [] }` のような default value の指定がある場合、remove しません。

**Comment by tany** [comment]
text も strip していいかも？
モ●ゲーとかそういう仕様だったような。

**Comment by sunny4381** [comment]
html と text の例外処理を削除しました。html も text も strip します。
