### ISSUE TITLE
記事検索機能

### ISSUE THREAD

**Issue by snkmr** [shirasagi/shirasagi#62]
記事検索機能を、作成しました。
個人リポジトリに反映しています。

https://github.com/snkmr/shirasagi/commit/44104a0f89158ff69d60070285ae7f3bc581bd3d

・/docsにカテゴリーの選択プルダウンと件名検索のテキストBOXを追加しています。 
・検索押下で、記事検索画面（/docs/docs-search/）に遷移します。 
・カテゴリーの一覧は１階層目のみ対象としています。
・検索は、選択カテゴリー以下のカテゴリーを全て検索対象としています。

**Comment by itowtips** [comment]
・記事リストフォルダーに search.:format のルートを追加
・フォルダーの設定で検索フォームを表示するか等の検索条件を設定する。
以上を作成してみました。
Addon SearchSettingをincludeし検索フォーム設定を追加しています。

https://github.com/itowtips/shirasagi/commit/6c4c6562cc7085776cd24ca4bce8d85482280d19
