### ISSUE TITLE
Gravatar

### ISSUE THREAD

**Issue by tany** [shirasagi/shirasagi#628]
Gravatar の画像を利用する。

16進数のID部分，MD5．
```
require 'digest'
size = 150
"https://gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{size}"
```

**Comment by kaosf** [comment]
一応こういう helper

- https://github.com/kaosf/shirasagi/commit/c5bfd6ee2ef65dfd4c351d3628449add5254cc39
- https://github.com/kaosf/shirasagi/commit/fc8165f860f881e4db644a1fa6ef9f8c3641b1a8

を作ったので，これを何処か出したいところで使ってもらえれば．

```ruby
gravatar_image_tag @cur_member.email, 150
```

のように．

**Comment by sunny4381** [comment]
@kaosf Gravatar に画像が登録されていない場合にシラサギで持っている "No Image" 的な既定のアイコンを表示したい場合、何か手がありますかね？

**Comment by kaosf** [comment]
https://ja.gravatar.com/site/implement/images/

Default image の設定が出来るようです．

これ対応しますわ．

**Comment by kaosf** [comment]
```html
<img src="http://www.gravatar.com/avatar/00000000000000000000000000000000?d=http%3A%2F%2Fexample.com%2Fimages%2Favatar.jpg" />
```

**Comment by itowtips** [comment]
今回の要件として以下の画像のように、ページにGravatar画像を表示したいとのことです。
（投稿者名 + 赤の四角がGravatar画像）
![glav](https://cloud.githubusercontent.com/assets/6094043/14845676/bc9cb03a-0c9a-11e6-8b02-1f38bb797c61.png)

**Comment by itowtips** [comment]
ということで、
Gravatar画像の公開側表示と設定を作成する必要が有ります。

設定は以下の仕様を考えています。
こちらをまず検討ください。

■Gravatar用アドオンの追加
管理画面のページ系にGravatar用のアドオンを追加する
以下設定項目
１. 画像表示ステータス
　「表示しない」
　「ページ作成者の画像を表示する」
　「Gravatar用メールアドレス欄に記載した画像を表示する」

２. Gravatar用メールアドレス

３.投稿者表示名

■ページ作成者
Cms::Page系であればuser_idで紐づいています。

■No image
メールアドレスからGravatar画像が取得できない場合
helper側で"No image"画像を返却しサポートする

**Comment by kaosf** [comment]
現状 https://github.com/kaosf/shirasagi/commit/34071b54900fdc7cb619dbcd5caecdeb068b47e7 こういう感じでまだ途中ですので，明日も引き続きやります．報告まで．

公開側の表示する場所を探すのに手間取ってます．

**Comment by sunny4381** [comment]
addon の場合、管理側 view を置いているディレクトリに `view` というディレクトリ作成し、`view` ディレクトリに `index.html.erb` を作成します。`index.html.erb` が公開側の view となります。

参考: `app/views/cms/agents/addons/additional_info/view/index.html.erb`
