### ISSUE TITLE
シラサギのサブディレクトリへの割り当て

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#649]
要望:
`http://localhost:3000/subdir/` にアクセスすると、トップページが見えるようにしたいです。

システム設定のサイトのドメインを `localhost:3000/subdir/` にしてみましたが、
書き出しでエラーになりました。

**Comment by snkmr** [comment]
redmineの例となっていますが、下記の記事参考になるでしょうか。
http://blog.nazylabs.net/2013/07/06/124/

**Comment by sunny4381** [comment]
@snkmr :+1: 

添付記事を参考に、SHIRASAGI を "/sudachi" にデプロイしてみましたが、
無変更・無修正では無理そうです。

## 修正箇所

`Cms::PublicFilter#set_request_path` に次のコードを挿入

```
@cur_path = @cur_path.sub(/^#{relative_url_root}/, '/')
```

`SS::Model::Site` を次のように修正:

```
    def relative_url_root
      ret = ActionController::Base.relative_url_root.nil? ? "/" : ActionController::Base.relative_url_root
      ret = "#{ret}/" unless ret.end_with?("/")
      ret
    end

    def url
      domain.index("/") ? domain.sub(/^.*?\//, relative_url_root) : relative_url_root
    end

    def full_url
      "http://#{domain}/".sub(/\/+$/, relative_url_root)
    end
```

この修正で、（おそらく）レイアウトで固定パスを記述している箇所以外は、"/sudachi" がつくようになりました。`/fs` にも "/sudachi" がついています。

## 問題点

* `RAILS_RELATIVE_URL_ROOT=/sudachi bundle exec rake cms:generate_nodes` コマンドを実行した所、エラーになりました。

```
# サイト名
/sudachi/index.html
/sudachi/404.html
-- Error
undefined method `filename' for nil:NilClass
/home/vagrant/sudachi/app/controllers/concerns/cms/public_filter/layout.rb:51:in `render_layout'
/home/vagrant/sudachi/app/controllers/concerns/cms/public_filter/node.rb:49:in `generate_node'
/home/vagrant/sudachi/app/controllers/concerns/cms/public_filter/node.rb:59:in `generate_node_with_pagination'
/home/vagrant/sudachi/app/controllers/article/agents/tasks/node/pages_controller.rb:6:in `generate'
/usr/local/rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/usr/local/rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:198:in `process_action'
/usr/local/rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:10:in `process_action'
/usr/local/rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
```

**Comment by sunny4381** [comment]
引き続き調査しました。

ページ書き出し時に `@cur_path` を作成している箇所（cms/public_filter/node.rb と cms/public_filter/page.rb）に、`Cms::PublicFilter#set_request_path` と同様の修正を入れた所、動作するようになりました。

**Comment by tany** [comment]
別フィールドにした方がいいと思います。
```
field :subdir, type: String
```

**Comment by sunny4381** [comment]
@tany `SS::Model::Site` に `subdir` を追加して、file.rb、thumb_file.rb の "/fs" もサブディレクトリ対応を実施しました。

こうすると `public_filter.rb` の index メソッドの最後の else 節に到達し、404 となりました。
そこで、次のように変更:

```ruby
        raise "404" if @cur_site.subdir.blank?
        raise "404" if request.env['ss.reroute']

        # /subdir/fs を正しい route を通らせるため env を書き換えて、再処理させる。
        env = request.env.dup
        env['REQUEST_PATH'] = env['REQUEST_PATH'].sub(@cur_site.normalized_subdir, '/')
        env['PATH_INFO'] = env['PATH_INFO'].sub(@cur_site.normalized_subdir, '/')
        env['REQUEST_URI'] = env['REQUEST_URI'].sub(@cur_site.normalized_subdir, '/')
        env['ss.reroute'] = true

        Rails.application.endpoint.call(env)
```

問題点や他にいい案があれば連絡ください。

**Comment by sunny4381** [comment]
/assets や /asserts-dev のサブディレクトリ化も必要なことがわかりましたが、ちょっと、どうやればいいのか不明です。
Rails アプリを subdir にデプロイするのは無理なのかもと思ったり。

**Comment by sunny4381** [comment]
少し補足すると:

"/assets/cms/public.css" のコントローラーは何か調査してみると:

```
2.2.2 :001 > Rails.application.routes.recognize_path("/assets/cms/public.css", method: "GET")
 => {:controller=>"cms/public", :action=>"index", :public_path=>"assets/cms/public", :format=>"css"}
```

このように "cms/public" が得られることから、低レベルな Rack レベルでルーティングが処理されていそうです。
2 つ上に掲載しているようなコードで re-routing を行っても、自分に戻ってきて 404 となりました。

**Comment by tany** [comment]
`config.assets.prefix = "/subdir/assets"' として
views などの `/assets` 固定の箇所を `#{subdir}/assets` みたいに変更でダメでしょうか。
書き出される場所は変わらないので
nginx で /subdir/assets のロケーション設定しておけば大丈夫のような。

**Comment by sunny4381** [comment]
当面「サブディレクトリへの割り当て」が不要になったため、クローズします。
