### ISSUE TITLE
CSS 問題点

### ISSUE THREAD

**Issue by tany** [shirasagi/shirasagi#686]
### field_with_errors > input, textarea
入力エラー時に display: inline になるので input, textarea の width が聞かなくなる。

### button
&lt;button> に デザインがあたっているため、サードパーティライブラリ使用時に問題が発生する可能性がある。

**Comment by MasakiInaya** [comment]
### field_with_errors > input, textarea
field_with_errorsをinlineにし、input, textarea はinline-blockに変更しました。

### button
buttonタグへの指定を解除し、classへ指定に変更しました。
