### ISSUE TITLE
unicorn.stderr.log に「X-Accel-Mapping header missing」が大量出力される。

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#694]
unicorn.stderr.log に「X-Accel-Mapping header missing」が大量出力される。

**Comment by tany** [comment]
document root に静的ファイルが存在しないときにログが出力されます。

example)
```
http://ss.vm/fs/7/4/6/_/a47f02b0.jpg
http://ss.vm/.s1/preview/fs/7/4/6/_/a47f02b0.jpg
```

`X-Accel-Mapping` ヘッダーを設定すればログはなくなります。
`proxy_set_header X-Sendfile-Type X-Accel-Redirect;` 設定しなくてもよさそう。

```
server {
    location @app {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header X-Sendfile-Type X-Accel-Redirect;
        proxy_set_header X-Accel-Mapping /var/www/ss/private/files/ss_files/=/fs/;
    }
    location /fs/ {
      internal;
      alias /var/www/ss/private/files/ss_files/;
    }
}
```

上記の `=/fs/` の設定は `=/fs2/` でも `=/fs3/` でも動作するようで、
ここのパスは URL ではなく内部変数的なものなのかな？？

**Comment by tany** [comment]
`internal` も指定しなくても動作しました。
`/var/www/ss` は `/var/www/shirasagi` に置換してください。

**Comment by tany** [comment]
開発マニュアルを編集しました。
http://shirasagi.github.io/installation/nginx.html
ついでに、標準設定(httpd.conf)を追加してvirtual.conf を分割しました。（マルチドメイン設定時に楽なため）

**Comment by tany** [comment]
`/assets/` 配下で問題が発生するようなので再検討します。

**Comment by tany** [comment]
マニュアルを編集しました。

```
proxy_set_header X-Accel-Mapping /var/www/shirasagi/private/files/=/private_files/;
```
`/var/../files/` へのリクエストを内部リクエスト `/private_files/` にリダイレクトする。

```
location /private_files/ {
    internal;
    alias /var/www/shirasagi/private/files/;
}
```
/private_files/ へのリクエストを受け付ける。
internal の指定があるので、内部リクエストのみを受け付ける。 [#internal](http://nginx.org/en/docs/http/ngx_http_core_module.html#internal)
`/var/../files/` にあるファイルを返す。[#alias_root](https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/)

以下の記述があると unicorn にリダイレクトされるので削除しました。
```
location ~* \.(ico|css|js|gif|jpe?g|png)$ {
    try_files $uri @app;
}
```

**Comment by tany** [comment]
```
proxy_set_header X-Accel-Mapping /var/www/shirasagi/private/files/=/private_files/;
```
と限定すると、他のパスで x-sendfile が動作しなくなるので範囲を拡大。

```
location @app {
    proxy_set_header X-Accel-Mapping /var/www/shirasagi/=/private_files/;
}
location /private_files/ {
    internal;
    alias /var/www/shirasagi/;
}
```

**Comment by tany** [comment]
sever { } 内で proxy_set_header を設定すると、
http { } 内で設定しているヘッダーが全て消えてしまう。
sever { } 内で再定義するか、X-Accel-Mapping を http 内に書く必要がある。

例えば virtual.conf に書く。

virtual.conf
```
server {
    include conf.d/server/shirasagi.conf;
    listen 80;
    server_name example.jp;
    root /var/www/shirasagi/public/sites/w/w/w/_/;
}
proxy_set_header X-Accel-Mapping /var/www/shirasagi/=/private_files/;
```

shirasagi,conf
```
location @app {
    if ($request_filename ~ .*\.(ico|gif|jpe?g|png|css|js)$) { access_log off; }
    proxy_pass http://127.0.0.1:3000;
}
location / {
    try_files $uri $uri/index.html @app;
}
location /assets/ {
    root /var/www/shirasagi/public/;
    expires 1h;
    access_log off;
}
location /private_files/ {
    internal;
    alias /var/www/shirasagi/;
}
```

**Comment by tany** [comment]
補足） proxy_set_header を複数記述すると下記の警告が発生することがある。
```
nginx: [warn] could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
```

[#proxy_headers_hash_bucket_size](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_headers_hash_bucket_size)

```
Syntax: 	proxy_headers_hash_bucket_size size;
Default: 	proxy_headers_hash_bucket_size 64;
Context: 	http, server, location
```

値を拡張すればとりあえず警告は消える。
```
proxy_headers_hash_bucket_size 256;
```
