### ISSUE TITLE
ページ移動後、「詳細へ戻る」リンクの押下で移動先のフォルダーへ移動しない。

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#716]
移動する
↓
移動先フォルダーを指定
↓
保存
↓
詳細へ戻る
↓
ファイル名（URL）は変更になっているが、
移動先のフォルダーへ移動せず
そのまま編集すると移動元に戻る。
この画面で編集せずに移動先フォルダーから操作を行った場合は問題なし

**Comment by tany** [comment]
一覧画面に遷移するように変更しました。（暫定

**Comment by tany** [comment]
親フォルダーが変更された場合はURLも適切に変更する。
