### ISSUE TITLE
施設検索フォルダーの検索HTMLなどの記述方法

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#719]
レイアウト内に記述するパーツの呼び出し構文の記述方法が変更になっているが
施設検索フォルダーの検索HTMLなどの記述方法は旧仕様のみ記述可能となっている。

**Comment by itowtips** [comment]
https://github.com/shirasagi/shirasagi/commit/18273b520708b9726b594cb4a6d202707fb7d1f5
#{canvas} のような構文としました。
