### ISSUE TITLE
一覧ページやパーツに表示する記事タイトルを変更したい

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#723]
記事自体のタイトルと一覧ページやパーツなどの一覧リンクに表示するタイトルを分けたい。

**Comment by MasakiInaya** [comment]
一覧用のタイトル入力フィールドを追加する。

**Comment by MasakiInaya** [comment]
記事の詳細画面では表示されるが、編集画面に表示されない

**Comment by kaosf** [comment]
おかしいですね．`_form.html.erb` にも追加はしてあるはずなのですが…

https://github.com/shirasagi/shirasagi/pull/889/commits/e396c7c2306b4cb52f058a1828702cbe23cc4478

**Comment by kaosf** [comment]
その後のファイル名フィールドを展開可能にする件の実装で個別に `_form.html.erb` を追加したものが7つあった．そこに `index_name` 用のものが追加されていなかった．

詳細表示ではあるのに編集画面にはない，という不思議な現象もこれで納得．
