### ISSUE TITLE
メールフォームのメール通知の文面の編集

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#732]
個人情報が入力されることもあるので、通知文面の内容に回答内容を掲載しないようにしたい。

**Comment by MasakiInaya** [comment]
通知文面の内容を決めるフィールドを追加する

■通知内容
・通知のみ
・投稿内容を含む

※以下の文章を文頭に入れる
新しい投稿がありました。
下記のURLから投稿内容を確認してください。
URL

**Comment by MasakiInaya** [comment]
自動返信メールの設定を拡張する。
返信テキストの他に、回答内容の設定を追加する。
　　通知する、管理者のみ通知する、通知しない（リンクのみ）
　　リンクは必ず表示する。（管理者のみ）

**Comment by itowtips** [comment]
#896

**Comment by kaosf** [comment]
#899
