### ISSUE TITLE
サイト内に登録されている全コンテンツ一覧を出力したい

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#753]
運用状況把握の為、サイト内のコンテンツ一覧をCSVでダウンローできる機能が欲しい。

■出力する内容案は以下の通り
・管理グループ名
・コンテンツID
・容量
・コンテンツ名
・公開日時
・最終更新日
・公開終了日
・状態
・登録種別（ページ属性等）
・カテゴリー
・地図使用の有無

**Comment by MasakiInaya** [comment]
複数フォルダ内の記事を一括で出力したい。
インポートの必要はない。
記事インポート/エクスポート機能とは別に出力機能を実装する。

**Comment by kaosf** [comment]
NOTE

## 容量

静的ファイルとして出力されるHTMLファイルのファイルサイズ．

`basename`と`filename`からファイルパスは分かるので，そこのファイルに対して

```sh
du -b 403.html | cut -f 1
```

```sh
stat $FILENAME | grep Size: | awk '{print $2}'
```

などしてやれば良い．Rubyでやるなら以下のように．

```ruby
File.stat(filename).size
```

これでバイト数が取れる．

## カテゴリ(フォルダ属性)で何を使っているか

`Cms::Page` の `category_ids` フィールド (※embeds_idsで用意されているもの) の内容を確認すれば良い．

## 地図を使用しているかどうかの判定

`Cms::Page` がincludeしている `Map::Addon::Page` に存在するフィールド `map_points` が空であるかどうか．

**Comment by kaosf** [comment]
> ■出力する内容案は以下の通り
> ・管理グループ名
> ・コンテンツID
> ・容量
> ・コンテンツ名
> ・公開日時
> ・最終更新日
> ・公開終了日
> ・状態
> ・登録種別（ページ属性等）
> ・カテゴリー
> ・地図使用の有無

以下に変更されている．

- URL
- 管理グループID
- 管理グループ名
- コンテンツID
- 容量
- コンテンツ名
- コンテンツの作成日時
- 公開日時
- 最終更新日時
- 公開終了日時
- 状態
- 登録種別 (ページ属性等)
- カテゴリ
- 地図使用の有無
- 添付ファイルの有無

**Comment by kaosf** [comment]
出力するのは `Cms::Page` と `Cms::Node` だけでいいですか？

**Comment by kaosf** [comment]
「日時」と「日」の出力については，これで本当に合っていますか？

- コンテンツの作成「日時」
- 公開「日時」
- 最終更新「日」
- 公開終了「日」

**Comment by MasakiInaya** [comment]
'
<div class="addon-views">
  <div class="addon-view" id="addon-basic">
    <div class="addon-head"><h2>サイト内コンテンツ全出力</h2></div>
    <div class="addon-body">
      <p>サイト内の全コンテンツを出力します。</p>

    </div>
  </div>
</div>
<footer class="send">
  <input name="commit" value="削除" class="btn-danger delete" type="submit">
  <button name="button" type="reset" class="btn-default" onclick="location.href='/.s1/article155/pages/47'; return false;">キャンセル</button>
</footer>
'

**Comment by MasakiInaya** [comment]
1．「URL」は絶対パス（フルパス）に変更
2．「コンテンツ名」を「タイトル」に変更
