### ISSUE TITLE
ファイル名欄の展開

### ISSUE THREAD

**Issue by itowtips** [shirasagi/shirasagi#754]
ファイル名は自動で連番になる為、ファイル名欄を展開して入力できるようにしたい。

**Comment by MasakiInaya** [comment]
入力が必須ではない場合、入力欄を非表示にしておく。
指定したい時は、表示用のリンクをクリックして入力欄を表示する。

**Comment by MasakiInaya** [comment]
記事ページの編集画面のツールチップが「タイトル」の内容になっている
