### ISSUE TITLE
承認　internal server error 表示の改善

### ISSUE THREAD

**Issue by tany** [shirasagi/shirasagi#803]
承認時、承認者にメールアドレスが登録されていないとエラーダイアログが表示される。

```
== Error ==
Internal Server Error
```

適切なメッセージを表示してほしい。
とのこと。

**Comment by tany** [comment]
案） メールアドレスなしで送信できるようにし、
　　　送信画面でメールアドレスがないことが分かるようにする。

**Comment by ShinjiTanimoto** [comment]
[Modify]Approve without approvers email address #1452
