### ISSUE TITLE
MongoDB / Authentication

### ISSUE THREAD

**Issue by tany** [shirasagi/shirasagi#835]
以下の環境で認証動作を確認。
- MongoDB 3.2.3 x mongoid 5.1.1
- MongoDB 3.0.3 x mongoid 5.1.1

mongoid.yml は一部変更あり。
~~~
development:
  clients:
    default:
      database: ss
      hosts:
        - localhost:27017
      options:
        #user: username
        #password: password
~~~
`sessions` は `clients` に変更。
username, password は上記の通り、`options` に含む。
https://docs.mongodb.org/ecosystem/tutorial/mongoid-installation/#anatomy-of-a-mongoid-config

**Comment by sunny4381** [comment]
[MONGOID-4041](https://jira.mongodb.org/browse/MONGOID-4041?jql=project%20%3D%20MONGOID%20AND%20text%20~%20%22auth%22)のコメントに

```
Mongoid is not going to support MongoDB 3.x with authentication until Mongoid 5
```
