### ISSUE TITLE
インストーラ

### ISSUE THREAD

**Issue by kaosf** [shirasagi/shirasagi#908]
https://github.com/kaosf/install

このリポジトリの所有者を shirasagi に移したかったのですが admin 権限が必要なようです．

https://github.com/shirasagi/install

リポジトリを作って，私の所有している install リポジトリをそのまま push して下さい．(forkではなく)

**Comment by sunny4381** [comment]
議論の余地はあるかと思いますが、`config/secret.yml` は毎回書き換えたいです。
このファイル、システム既定のを使いまわしていると重大なセキュリティ・ホールを生じそうで怖いです。

**Comment by kaosf** [comment]
Shirasagi本体の手入れが必要ですね．

私も `config/secret.yml` の，production環境の `secret_key_base` はソースに埋め込むべきではないと思います．

というか，今Railsを使って普通に `rails new` すると，ここは環境変数を使うコードがデフォルトであります．

```ruby
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

test:
  secret_key_base: yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
```

**Comment by kaosf** [comment]
ところでひとまずリポジトリを shirasagi/install に移してもらえませんか？

**Comment by tany** [comment]
`bin/install.sh` に写しました。
rake 系や cron 設定は入ってないですよね？

**Comment by snkmr** [comment]
素のCentOS7で走らせてみました。
 curl https://raw.githubusercontent.com/shirasagi/shirasagi/master/bin/install.sh | bash -s (VM-IP)

nginxまで入っているので、80番ポートアクセス前提で確認しましたが、
下記について気になりました。
・インストール完了後、80番ポートにアクセスしても、404エラー画面。
　.mypageもcssが当たっていない状態。　ログイン不可。
　これはnginxのrootの設定が、public/sites～の指定だが、このディレクトリがないため。
　インストーラ内で自治体サンプルをrakeで投入しておくべきでは。
・インストーラ内でfirewalldの3000ポートを許可としているが、
　firewalld on前提なら、80番ポートも許可とすべきでは。
　もしくは、インストーラの先頭に、SeLinux off firewalld off 前提を記述しておくか。
