### ISSUE TITLE
ページとフォルダの移動

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#91]
作成したページの属するフォルダーを移動することはできないでしょうか。

**Comment by tany** [comment]
仕様案

## role
フォルダー移動権限 move を追加する。

## action-menu
編集の下に移動リンクを追加する。
<%= link_to :move, action: :move if @model.allow?(:move) %>

**Comment by tany** [comment]
## ロール編集画面
すべてチェックするのが大変なのでモジュールごとに"すべて選択"があるといい。

**Comment by itowtips** [comment]
###ページとフォルダーの移動を作成中
■https://github.com/itowtips/shirasagi/commit/69d7cb908593999dac2e7c615f8b1ead4900617a

#### フォルダーの移動
* 標準機能(conf)の設定に移動を追加した
* conf と node modelにロジックを実装中
* 権限は標準フォルダーの移動のみ

#### ページの移動
* cms、article、event、faqページに移動を設置したい
* page filter と page modelにロジックを実装中
* cms/page以外をルートに置くことはできない
* 権限を検討中、すべてのモジュール(cms、article、event、faq)に移動権限を付ける方向に考えている

### 対応中の課題
* pageとnodeで纏められるコードを纏める
* ページ移動の権限
* リンクチェックの検索条件
* バリデーション時の権限チェック
* ページ保存時に親フォルダ（cid）が変わった時の対応をどう実装するか。

**Comment by itowtips** [comment]
■https://github.com/itowtips/shirasagi/commit/321f5f257bc071172405c20d0757e868e8934899
* リンクチェックの検索条件を調整
* ページ移動の権限 cms、article、event、faqに移動権限を追加
* ページ保存時のロジックを修正、親フォルダが変わった場合に対応

**Comment by itowtips** [comment]
■https://github.com/itowtips/shirasagi/commit/e4489544a1507c36285264cd65e63547a2b47c5d
* バリデーション時に親フォルダーの閲覧権限を確認

**Comment by itowtips** [comment]
■https://github.com/itowtips/shirasagi/commit/a87dc78231584fac8cd2fdafc3f7130ccea0054c
* viewのみ重複していたので纏めました。

**Comment by itowtips** [comment]
■https://github.com/itowtips/shirasagi/commit/66b2d30615693def29aba8047bd8988690d6b233
* リンクチェックの検索条件を調整、検索条件を ```  ="path ```  に

**Comment by itowtips** [comment]
マージしました。　リンクの置換と検索は #250
