### ISSUE TITLE
MongoDB / Mongoid のクエリ・キャッシュの問題

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#915]
MongoDB / Mongoid のクエリ・キャッシュで小一時間ハマったので、クエリ・キャッシュを無効にすることを提案します。

MongoDB / Mongoid のクエリ・キャッシュのキーは、次のようです：

  `[ collection.namespace, selector, limit, skip, projection ]`

* `collection.namespace` は、`Cms::Page` モデルであれば `ss.cms_pages`（※データベースが `ss` の場合）となります。
* `selector` は、検索条件のハッシュです。
* `limit` と `skip` はそれぞれ取得件数の最大値と、読み飛ばし数です。
* `projection` は何か分かりませんでした。aggregation を使用した時に何か入るかもしれません。

* 参考: mongoid-5.1.1/lib/mongoid/query_cache.rb

注意点として `selector` には、`order_by` で指定したソード条件は含まれていません。
このため、次のようにリリース日の最小値と最大値を取得しようとすると:

```ruby
min = Cms::Page.order_by(released: 1).first.released
max = Cms::Page.order_by(released: -1).first.released
```

min は期待通り最小値を取得できますが、max を取得しようとするとキャッシュにヒットしてしまうため min と同じ値になります。

クエリ・キャッシュはスレッド・ローカル変数に格納するという親切設計のため、
criteria のインスタンスが異なっていてもキャッシュにヒットします。

この問題、簡単に原因が判明するような問題ではなく、一度発生すると原因の究明がなかなか難しいので、クエリ・キャッシュを無効にすることを提案します。

**Comment by tany** [comment]
残念ですが無効にするしかないですかね。
ちなみに問題が発生したのはどういう仕様ですか？

**Comment by sunny4381** [comment]
記事のアーカイブ機能を提供したいと考えています。

アーカイブ機能はノードとパーツで構成され、パーツの方で、年の部分はドロップダウンで実現し、月の部分は1月～12月を固定でリンクを設置しておきます。

年のドロップダウンですが、存在する記事の範囲内で動的に表示したかったです。
※記事の存在しない年を表示しても仕方ないので。

そこで、上記の例のように min と max を取得して、年のドロップダウンを描画しています。

**Comment by tany** [comment]
cache_key に sort 条件を加えるというのは安直ですかね

~~~
module Mongoid
  module QueryCache
    module View
      private
      def cache_key
        #[ collection.namespace, selector, limit, skip, projection ]
        [ collection.namespace, selector, limit, skip, projection, sort ]
      end
    end
  end
end
~~~

**Comment by sunny4381** [comment]
sort は、次のように to_s の結果がいまいちなのでやめたほうが無難かと。

```
[17] pry(main)> Cms::Page.all.order_by(id: 1).sort
=> #<Mongoid::Contextual::Mongo:0x0000000f0ff758
 @cache=nil,
 @collection=#<Mongo::Collection:0x126350940 namespace=ss.cms_pages>,
 @criteria=
  #<Mongoid::Criteria
  selector: {}
  options:  {:sort=>{"_id"=>1}}
  class:    Cms::Page
  embedded: false>
,
 @klass=Cms::Page,
 @view=
  #<Mongo::Collection::View:0x126349840 namespace='ss.cms_pages' @filter={} @options={"sort"=>{"_id"=>1}}>>
[18] pry(main)> Cms::Page.all.order_by(id: 1).sort.to_s
=> "#<Mongoid::Contextual::Mongo:0x0000000f138648>"
```

代わりに options が使えそうです。

```
[19] pry(main)> Cms::Page.all.order_by(id: 1).options
=> {:sort=>{"_id"=>1}}
[20] pry(main)> Cms::Page.all.order_by(id: 1).options.to_s
=> "{:sort=>{\"_id\"=>1}}"
```

[MONGOID-3562](https://jira.mongodb.org/browse/MONGOID-3562) で、limit と skip を追加したみたいなんですが、options で行けたんじゃないかと：

```
Cms::Page.all.limit(1).skip(1).order_by(id: 1).options
=> {:limit=>1, :skip=>1, :sort=>{"_id"=>1}}
Cms::Page.all.limit(1).skip(1).order_by(id: 1).options.to_s
=> "{:limit=>1, :skip=>1, :sort=>{\"_id\"=>1}}"
```

なんで options を追加せずに、limit, skip を個別に追加したのか...。

**Comment by sunny4381** [comment]
@tany キャッシュ・キーに sort を追加したらいけました。
@6d869e8 では、確認用の spec を追加しました。

**Comment by tany** [comment]
こんな仕様も考えました。
_id 以外の selector がある、または limit 以外の options がある時はキャッシュを無効にする。
（ belongs_to :site のような場面のみキャッシュ有効）

~~~
module QueryCacheOnlyFind
  private
  def system_collection?
    return true if selector.reject { |k, v| k == '_id' }.present?
    return true if options.reject { |k, v| k == 'limit' }.present?
    super
  end
end
Mongo::Collection::View.__send__(:include, QueryCacheOnlyFind)
~~~

**Comment by sunny4381** [comment]
すべてのテストを Query Cache を有効にした状態で実行してみました（@036fa4f）。
2 箇所、Query Cache が有効な状態だとテストに失敗しました（@2ff7cdd）。この 2 箇所は、クエリキャッシュを向こうにしてテストを実行するようにしています。

次のようなループで、書き出し処理が完了するのを待機しています。

```ruby
loop do
  task = Cms::Task.where(name: "cms:generate_nodes", site_id: site.id, node_id: node.id).first
  break if task.state != "ready"
  sleep 0.1
end
```

`task` の内容が常にキャッシュの内容なので、いつまでたっても終わりません。
テストコードの問題といえば問題ですが気になります。

上のコメントのように、キャッシュを適用するクエリ条件を限定するのが良いのかもしれません。
