### ISSUE TITLE
一覧系パーツの検索条件（ページ一覧系パーツ）

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#92]
現在のページと同階層にあるページ一覧を表示するパーツを作成いただけないでしょうか

**Comment by itowtips** [comment]
■https://github.com/itowtips/shirasagi/commit/833883bc7887d7050b3c6520dbea57c4250ff96c
params直渡しをやめ、ロジックを少し修正しました。

**Comment by itowtips** [comment]
マージしました。
