### ISSUE TITLE
パーツの親フォルダー名表示（カテゴリーリストパーツ）

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#93]
ヘッダー部分に親のフォルダー名を表示することはできないでしょうか。

**Comment by itowtips** [comment]
■https://github.com/itowtips/shirasagi/commit/5fa21485eb052c60c0b6d4fbf8dfff8f566081bd
上部、下部ＨＴＭＬに記述するとパーツ名と親フォルダー名に置き換わるパターンを作成しました。
個人リポジトリにアップしています。

#{part_name}　→　パーツ名
#{parent_name}　→　親フォルダー名

**Comment by itowtips** [comment]
マージしました

**Comment by MasakiInaya** [comment]
パーツを置いているフォルダーの親フォルダー名ではなく、見ている画面の親フォルダー名を表示できないでしょうか。

**Comment by itowtips** [comment]
■https://github.com/itowtips/shirasagi/commit/9f221b739c154df36eba6a62f937cbb776c65d2d
パターンを追加してみました。個人リポジトリにアップしています。

#{request_dir_name}　→　見ているフォルダー名
#{request_dir_parent_name}　→　見ているフォルダーの親フォルダー名

**Comment by itowtips** [comment]
■https://github.com/itowtips/shirasagi/commit/6e67fbc66368267bfd0e7615bdc70cd311da2c60
パターンを変えてマージしました。

#{request_dir} →　見ているフォルダー名
#{request_parent_dir} →　見ているフォルダーの親フォルダー名

以下は外しました
#{part_name}　→　パーツ名
#{parent_name}　→　親フォルダー名

**Comment by tany** [comment]
’dir' がURLだったり名称だったり混在しているので整理する必要があります。
request_parent_dir の使いどころがよく分かりませんが、
名称なら page_name, node_name, parent_name など簡単に書ければよいと思います。

**Comment by itowtips** [comment]
■https://github.com/shirasagi/shirasagi/commit/b6a6dee41dd69367a74178a8503e5c3d88324dc6
パターンを変えました。
#{request_dir} 　　　      →  #{parent_name} 
#{request_parent_dir}  →  #{parent.parent_name}
