### ISSUE TITLE
デフォルトの表示画面（フォルダー「カテゴリー/ページリスト」）

### ISSUE THREAD

**Issue by MasakiInaya** [shirasagi/shirasagi#94]
管理画面でのデフォルトの表示画面をフォルダー内のページ一覧にすることは可能でしょうか。

**Comment by itowtips** [comment]
■https://github.com/itowtips/shirasagi/commit/70f56d00eab7b466bd868382600238895c77724f
デフォルトの表示画面を切り替える設定を追加しました。
個人リポジトリにアップしています。

フォルダーの設定項目「既定のモジュール」にてデフォルトの画面を決定します。

**Comment by itowtips** [comment]
マージしました
